// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dense_resource_0_0_1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dense_resource_0_0_1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dense_resource_0_0_1::ap_const_logic_0 = sc_dt::Log_0;
const bool dense_resource_0_0_1::ap_const_boolean_1 = true;
const bool dense_resource_0_0_1::ap_const_boolean_0 = false;
const sc_lv<32> dense_resource_0_0_1::ap_const_lv32_7 = "111";
const sc_lv<32> dense_resource_0_0_1::ap_const_lv32_13 = "10011";
const sc_lv<32> dense_resource_0_0_1::ap_const_lv32_14 = "10100";
const sc_lv<32> dense_resource_0_0_1::ap_const_lv32_2 = "10";
const sc_lv<32> dense_resource_0_0_1::ap_const_lv32_D = "1101";
const sc_lv<13> dense_resource_0_0_1::ap_const_lv13_1FDF = "1111111011111";
const sc_lv<2> dense_resource_0_0_1::ap_const_lv2_0 = "00";
const sc_lv<32> dense_resource_0_0_1::ap_const_lv32_10 = "10000";
const sc_lv<14> dense_resource_0_0_1::ap_const_lv14_3FDE = "11111111011110";
const sc_lv<17> dense_resource_0_0_1::ap_const_lv17_0 = "00000000000000000";
const sc_lv<5> dense_resource_0_0_1::ap_const_lv5_0 = "00000";
const sc_lv<3> dense_resource_0_0_1::ap_const_lv3_0 = "000";
const sc_lv<32> dense_resource_0_0_1::ap_const_lv32_6 = "110";
const sc_lv<6> dense_resource_0_0_1::ap_const_lv6_0 = "000000";
const sc_lv<32> dense_resource_0_0_1::ap_const_lv32_11 = "10001";
const sc_lv<8> dense_resource_0_0_1::ap_const_lv8_33 = "110011";
const sc_lv<19> dense_resource_0_0_1::ap_const_lv19_7FFF3 = "1111111111111110011";
const sc_lv<32> dense_resource_0_0_1::ap_const_lv32_12 = "10010";
const sc_lv<4> dense_resource_0_0_1::ap_const_lv4_0 = "0000";
const sc_lv<13> dense_resource_0_0_1::ap_const_lv13_1FDB = "1111111011011";
const sc_lv<20> dense_resource_0_0_1::ap_const_lv20_17 = "10111";
const sc_lv<21> dense_resource_0_0_1::ap_const_lv21_1FFE05 = "111111111111000000101";
const sc_lv<21> dense_resource_0_0_1::ap_const_lv21_2A = "101010";
const sc_lv<20> dense_resource_0_0_1::ap_const_lv20_13 = "10011";
const sc_lv<21> dense_resource_0_0_1::ap_const_lv21_1FFEE4 = "111111111111011100100";
const sc_lv<21> dense_resource_0_0_1::ap_const_lv21_1FFFD3 = "111111111111111010011";
const sc_lv<21> dense_resource_0_0_1::ap_const_lv21_2B7 = "1010110111";
const sc_lv<20> dense_resource_0_0_1::ap_const_lv20_16 = "10110";
const sc_lv<21> dense_resource_0_0_1::ap_const_lv21_158 = "101011000";
const sc_lv<21> dense_resource_0_0_1::ap_const_lv21_57 = "1010111";
const sc_lv<21> dense_resource_0_0_1::ap_const_lv21_1FFF93 = "111111111111110010011";
const sc_lv<21> dense_resource_0_0_1::ap_const_lv21_1FFFB5 = "111111111111110110101";
const sc_lv<20> dense_resource_0_0_1::ap_const_lv20_FFFE7 = "11111111111111100111";
const sc_lv<20> dense_resource_0_0_1::ap_const_lv20_FFFEB = "11111111111111101011";
const sc_lv<20> dense_resource_0_0_1::ap_const_lv20_FFFE3 = "11111111111111100011";

dense_resource_0_0_1::dense_resource_0_0_1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    example_mul_mul_1tde_U674 = new example_mul_mul_1tde<1,1,14,6,20>("example_mul_mul_1tde_U674");
    example_mul_mul_1tde_U674->din0(data_0_V_read);
    example_mul_mul_1tde_U674->din1(mul_ln1118_fu_1005_p1);
    example_mul_mul_1tde_U674->dout(mul_ln1118_fu_1005_p2);
    example_mul_mul_1mb6_U675 = new example_mul_mul_1mb6<1,1,14,10,21>("example_mul_mul_1mb6_U675");
    example_mul_mul_1mb6_U675->din0(mul_ln1118_52_fu_1012_p0);
    example_mul_mul_1mb6_U675->din1(mul_ln1118_52_fu_1012_p1);
    example_mul_mul_1mb6_U675->dout(mul_ln1118_52_fu_1012_p2);
    example_mul_mul_1ncg_U676 = new example_mul_mul_1ncg<1,1,14,7,21>("example_mul_mul_1ncg_U676");
    example_mul_mul_1ncg_U676->din0(mul_ln1118_53_fu_1019_p0);
    example_mul_mul_1ncg_U676->din1(mul_ln1118_53_fu_1019_p1);
    example_mul_mul_1ncg_U676->dout(mul_ln1118_53_fu_1019_p2);
    example_mul_mul_1tde_U677 = new example_mul_mul_1tde<1,1,14,6,20>("example_mul_mul_1tde_U677");
    example_mul_mul_1tde_U677->din0(mul_ln1118_54_fu_1026_p0);
    example_mul_mul_1tde_U677->din1(mul_ln1118_54_fu_1026_p1);
    example_mul_mul_1tde_U677->dout(mul_ln1118_54_fu_1026_p2);
    example_mul_mul_1mb6_U678 = new example_mul_mul_1mb6<1,1,14,10,21>("example_mul_mul_1mb6_U678");
    example_mul_mul_1mb6_U678->din0(mul_ln1118_57_fu_1033_p0);
    example_mul_mul_1mb6_U678->din1(mul_ln1118_57_fu_1033_p1);
    example_mul_mul_1mb6_U678->dout(mul_ln1118_57_fu_1033_p2);
    example_mul_mul_1ocq_U679 = new example_mul_mul_1ocq<1,1,14,7,21>("example_mul_mul_1ocq_U679");
    example_mul_mul_1ocq_U679->din0(mul_ln1118_58_fu_1040_p0);
    example_mul_mul_1ocq_U679->din1(mul_ln1118_58_fu_1040_p1);
    example_mul_mul_1ocq_U679->dout(mul_ln1118_58_fu_1040_p2);
    example_mul_mul_1vdy_U680 = new example_mul_mul_1vdy<1,1,14,11,21>("example_mul_mul_1vdy_U680");
    example_mul_mul_1vdy_U680->din0(mul_ln1118_59_fu_1047_p0);
    example_mul_mul_1vdy_U680->din1(mul_ln1118_59_fu_1047_p1);
    example_mul_mul_1vdy_U680->dout(mul_ln1118_59_fu_1047_p2);
    example_mul_mul_1tde_U681 = new example_mul_mul_1tde<1,1,14,6,20>("example_mul_mul_1tde_U681");
    example_mul_mul_1tde_U681->din0(mul_ln1118_60_fu_1054_p0);
    example_mul_mul_1tde_U681->din1(mul_ln1118_60_fu_1054_p1);
    example_mul_mul_1tde_U681->dout(mul_ln1118_60_fu_1054_p2);
    example_mul_mul_1pcA_U682 = new example_mul_mul_1pcA<1,1,14,10,21>("example_mul_mul_1pcA_U682");
    example_mul_mul_1pcA_U682->din0(mul_ln1118_61_fu_1061_p0);
    example_mul_mul_1pcA_U682->din1(mul_ln1118_61_fu_1061_p1);
    example_mul_mul_1pcA_U682->dout(mul_ln1118_61_fu_1061_p2);
    example_mul_mul_1tde_U683 = new example_mul_mul_1tde<1,1,14,6,20>("example_mul_mul_1tde_U683");
    example_mul_mul_1tde_U683->din0(data_7_V_read);
    example_mul_mul_1tde_U683->din1(mul_ln1118_62_fu_1068_p1);
    example_mul_mul_1tde_U683->dout(mul_ln1118_62_fu_1068_p2);
    example_mul_mul_1wdI_U684 = new example_mul_mul_1wdI<1,1,14,8,21>("example_mul_mul_1wdI_U684");
    example_mul_mul_1wdI_U684->din0(mul_ln1118_63_fu_1075_p0);
    example_mul_mul_1wdI_U684->din1(mul_ln1118_63_fu_1075_p1);
    example_mul_mul_1wdI_U684->dout(mul_ln1118_63_fu_1075_p2);
    example_mul_mul_1sc4_U685 = new example_mul_mul_1sc4<1,1,14,8,21>("example_mul_mul_1sc4_U685");
    example_mul_mul_1sc4_U685->din0(mul_ln1118_65_fu_1082_p0);
    example_mul_mul_1sc4_U685->din1(mul_ln1118_65_fu_1082_p1);
    example_mul_mul_1sc4_U685->dout(mul_ln1118_65_fu_1082_p2);
    example_mul_mul_1sc4_U686 = new example_mul_mul_1sc4<1,1,14,8,21>("example_mul_mul_1sc4_U686");
    example_mul_mul_1sc4_U686->din0(mul_ln1118_66_fu_1089_p0);
    example_mul_mul_1sc4_U686->din1(mul_ln1118_66_fu_1089_p1);
    example_mul_mul_1sc4_U686->dout(mul_ln1118_66_fu_1089_p2);
    example_mul_mul_1rcU_U687 = new example_mul_mul_1rcU<1,1,14,6,20>("example_mul_mul_1rcU_U687");
    example_mul_mul_1rcU_U687->din0(mul_ln1118_67_fu_1096_p0);
    example_mul_mul_1rcU_U687->din1(mul_ln1118_67_fu_1096_p1);
    example_mul_mul_1rcU_U687->dout(mul_ln1118_67_fu_1096_p2);
    example_mul_mul_1rcU_U688 = new example_mul_mul_1rcU<1,1,14,6,20>("example_mul_mul_1rcU_U688");
    example_mul_mul_1rcU_U688->din0(mul_ln1118_56_fu_1103_p0);
    example_mul_mul_1rcU_U688->din1(mul_ln1118_56_fu_1103_p1);
    example_mul_mul_1rcU_U688->dout(mul_ln1118_56_fu_1103_p2);
    example_mul_mul_1rcU_U689 = new example_mul_mul_1rcU<1,1,14,6,20>("example_mul_mul_1rcU_U689");
    example_mul_mul_1rcU_U689->din0(data_6_V_read_4_reg_1123);
    example_mul_mul_1rcU_U689->din1(mul_ln1118_64_fu_1110_p1);
    example_mul_mul_1rcU_U689->dout(mul_ln1118_64_fu_1110_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln1118_13_fu_582_p2);
    sensitive << ( sext_ln1118_168_fu_566_p1 );
    sensitive << ( sext_ln1118_169_fu_578_p1 );

    SC_METHOD(thread_add_ln1118_fu_331_p2);
    sensitive << ( sext_ln1118_152_fu_206_p1 );
    sensitive << ( sext_ln1118_159_fu_327_p1 );

    SC_METHOD(thread_add_ln703_188_fu_273_p2);
    sensitive << ( sext_ln708_104_fu_232_p1 );
    sensitive << ( trunc_ln708_65_fu_210_p4 );

    SC_METHOD(thread_add_ln703_189_fu_279_p2);
    sensitive << ( add_ln703_fu_267_p2 );
    sensitive << ( add_ln703_188_fu_273_p2 );

    SC_METHOD(thread_add_ln703_190_fu_694_p2);
    sensitive << ( sext_ln708_106_fu_687_p1 );
    sensitive << ( sext_ln708_105_fu_671_p1 );

    SC_METHOD(thread_add_ln703_191_fu_285_p2);
    sensitive << ( sext_ln703_34_fu_263_p1 );

    SC_METHOD(thread_add_ln703_192_fu_295_p2);
    sensitive << ( trunc_ln708_69_fu_240_p4 );
    sensitive << ( sext_ln703_35_fu_291_p1 );

    SC_METHOD(thread_add_ln703_193_fu_700_p2);
    sensitive << ( add_ln703_192_reg_1148 );
    sensitive << ( add_ln703_190_fu_694_p2 );

    SC_METHOD(thread_add_ln703_195_fu_386_p2);
    sensitive << ( trunc_ln708_72_fu_310_p4 );
    sensitive << ( trunc_ln708_71_fu_301_p4 );

    SC_METHOD(thread_add_ln703_196_fu_392_p2);
    sensitive << ( sext_ln708_111_fu_360_p1 );
    sensitive << ( sext_ln708_110_fu_347_p1 );

    SC_METHOD(thread_add_ln703_197_fu_398_p2);
    sensitive << ( add_ln703_195_fu_386_p2 );
    sensitive << ( add_ln703_196_fu_392_p2 );

    SC_METHOD(thread_add_ln703_198_fu_761_p2);
    sensitive << ( sext_ln708_113_fu_757_p1 );
    sensitive << ( sext_ln708_112_fu_726_p1 );

    SC_METHOD(thread_add_ln703_199_fu_404_p2);
    sensitive << ( sext_ln708_114_fu_382_p1 );

    SC_METHOD(thread_add_ln703_200_fu_410_p2);
    sensitive << ( trunc_ln708_77_fu_364_p4 );
    sensitive << ( add_ln703_199_fu_404_p2 );

    SC_METHOD(thread_add_ln703_201_fu_767_p2);
    sensitive << ( add_ln703_200_reg_1158 );
    sensitive << ( add_ln703_198_fu_761_p2 );

    SC_METHOD(thread_add_ln703_203_fu_531_p2);
    sensitive << ( sext_ln708_115_fu_459_p1 );
    sensitive << ( trunc_ln708_79_fu_416_p4 );

    SC_METHOD(thread_add_ln703_204_fu_537_p2);
    sensitive << ( sext_ln708_117_fu_527_p1 );
    sensitive << ( sext_ln708_116_fu_513_p1 );

    SC_METHOD(thread_add_ln703_205_fu_543_p2);
    sensitive << ( add_ln703_203_fu_531_p2 );
    sensitive << ( add_ln703_204_fu_537_p2 );

    SC_METHOD(thread_add_ln703_206_fu_828_p2);
    sensitive << ( sext_ln708_119_fu_824_p1 );
    sensitive << ( sext_ln708_118_fu_789_p1 );

    SC_METHOD(thread_add_ln703_207_fu_834_p2);
    sensitive << ( sext_ln1118_163_fu_777_p1 );

    SC_METHOD(thread_add_ln703_208_fu_844_p2);
    sensitive << ( add_ln703_206_fu_828_p2 );
    sensitive << ( sext_ln703_fu_840_p1 );

    SC_METHOD(thread_add_ln703_210_fu_620_p2);
    sensitive << ( trunc_ln708_88_fu_588_p4 );
    sensitive << ( trunc_ln708_87_fu_549_p4 );

    SC_METHOD(thread_add_ln703_211_fu_626_p2);
    sensitive << ( sext_ln708_120_fu_616_p1 );
    sensitive << ( trunc_ln708_89_fu_598_p4 );

    SC_METHOD(thread_add_ln703_212_fu_632_p2);
    sensitive << ( add_ln703_210_fu_620_p2 );
    sensitive << ( add_ln703_211_fu_626_p2 );

    SC_METHOD(thread_add_ln703_213_fu_948_p2);
    sensitive << ( sext_ln708_106_fu_687_p1 );
    sensitive << ( sext_ln708_121_fu_871_p1 );

    SC_METHOD(thread_add_ln703_214_fu_954_p2);
    sensitive << ( sext_ln703_36_fu_944_p1 );

    SC_METHOD(thread_add_ln703_215_fu_964_p2);
    sensitive << ( sext_ln708_122_fu_913_p1 );
    sensitive << ( sext_ln703_37_fu_960_p1 );

    SC_METHOD(thread_add_ln703_216_fu_970_p2);
    sensitive << ( add_ln703_213_fu_948_p2 );
    sensitive << ( add_ln703_215_fu_964_p2 );

    SC_METHOD(thread_add_ln703_273_fu_705_p2);
    sensitive << ( add_ln703_189_reg_1143 );
    sensitive << ( add_ln703_193_fu_700_p2 );

    SC_METHOD(thread_add_ln703_274_fu_772_p2);
    sensitive << ( add_ln703_197_reg_1153 );
    sensitive << ( add_ln703_201_fu_767_p2 );

    SC_METHOD(thread_add_ln703_275_fu_850_p2);
    sensitive << ( add_ln703_205_reg_1168 );
    sensitive << ( add_ln703_208_fu_844_p2 );

    SC_METHOD(thread_add_ln703_276_fu_976_p2);
    sensitive << ( add_ln703_212_reg_1173 );
    sensitive << ( add_ln703_216_fu_970_p2 );

    SC_METHOD(thread_add_ln703_fu_267_p2);
    sensitive << ( trunc_ln708_64_fu_193_p4 );
    sensitive << ( sext_ln708_fu_181_p1 );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_return_0);
    sensitive << ( add_ln703_273_fu_705_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_0_int_reg );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( add_ln703_274_fu_772_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_1_int_reg );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( add_ln703_275_fu_850_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_2_int_reg );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( add_ln703_276_fu_976_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_3_int_reg );

    SC_METHOD(thread_mul_ln1118_52_fu_1012_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1118_149_fu_185_p1 );

    SC_METHOD(thread_mul_ln1118_52_fu_1012_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_53_fu_1019_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1118_151_fu_202_p1 );

    SC_METHOD(thread_mul_ln1118_53_fu_1019_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_54_fu_1026_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1118_153_fu_219_p1 );

    SC_METHOD(thread_mul_ln1118_54_fu_1026_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_56_fu_1103_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1118_156_fu_675_p1 );

    SC_METHOD(thread_mul_ln1118_56_fu_1103_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_57_fu_1033_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1118_157_fu_236_p1 );

    SC_METHOD(thread_mul_ln1118_57_fu_1033_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_58_fu_1040_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1118_fu_164_p1 );

    SC_METHOD(thread_mul_ln1118_58_fu_1040_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_59_fu_1047_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1118_149_fu_185_p1 );

    SC_METHOD(thread_mul_ln1118_59_fu_1047_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_60_fu_1054_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1118_153_fu_219_p1 );

    SC_METHOD(thread_mul_ln1118_60_fu_1054_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_61_fu_1061_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1118_157_fu_236_p1 );

    SC_METHOD(thread_mul_ln1118_61_fu_1061_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_62_fu_1068_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_63_fu_1075_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1118_fu_164_p1 );

    SC_METHOD(thread_mul_ln1118_63_fu_1075_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_64_fu_1110_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_65_fu_1082_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1118_fu_164_p1 );

    SC_METHOD(thread_mul_ln1118_65_fu_1082_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_66_fu_1089_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1118_151_fu_202_p1 );

    SC_METHOD(thread_mul_ln1118_66_fu_1089_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_67_fu_1096_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1118_153_fu_219_p1 );

    SC_METHOD(thread_mul_ln1118_67_fu_1096_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_68_fu_855_p0);
    sensitive << ( data_4_V_read_7_reg_1136 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_68_fu_855_p2);
    sensitive << ( mul_ln1118_68_fu_855_p0 );

    SC_METHOD(thread_mul_ln1118_fu_1005_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_sext_ln1118_149_fu_185_p0);
    sensitive << ( data_1_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_sext_ln1118_149_fu_185_p1);
    sensitive << ( sext_ln1118_149_fu_185_p0 );

    SC_METHOD(thread_sext_ln1118_150_fu_189_p0);
    sensitive << ( data_1_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_sext_ln1118_150_fu_189_p1);
    sensitive << ( sext_ln1118_150_fu_189_p0 );

    SC_METHOD(thread_sext_ln1118_151_fu_202_p0);
    sensitive << ( data_2_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_sext_ln1118_151_fu_202_p1);
    sensitive << ( sext_ln1118_151_fu_202_p0 );

    SC_METHOD(thread_sext_ln1118_152_fu_206_p0);
    sensitive << ( data_2_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_sext_ln1118_152_fu_206_p1);
    sensitive << ( sext_ln1118_152_fu_206_p0 );

    SC_METHOD(thread_sext_ln1118_153_fu_219_p0);
    sensitive << ( data_3_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_sext_ln1118_153_fu_219_p1);
    sensitive << ( sext_ln1118_153_fu_219_p0 );

    SC_METHOD(thread_sext_ln1118_155_fu_641_p1);
    sensitive << ( data_4_V_read_7_reg_1136 );

    SC_METHOD(thread_sext_ln1118_156_fu_675_p1);
    sensitive << ( data_5_V_read_6_reg_1130 );

    SC_METHOD(thread_sext_ln1118_157_fu_236_p0);
    sensitive << ( data_6_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_sext_ln1118_157_fu_236_p1);
    sensitive << ( sext_ln1118_157_fu_236_p0 );

    SC_METHOD(thread_sext_ln1118_159_fu_327_p1);
    sensitive << ( shl_ln_fu_319_p3 );

    SC_METHOD(thread_sext_ln1118_161_fu_737_p1);
    sensitive << ( shl_ln1118_81_fu_730_p3 );

    SC_METHOD(thread_sext_ln1118_162_fu_433_p1);
    sensitive << ( shl_ln1118_82_fu_425_p3 );

    SC_METHOD(thread_sext_ln1118_163_fu_777_p1);
    sensitive << ( trunc_ln708_136_reg_1163 );

    SC_METHOD(thread_sext_ln1118_164_fu_481_p1);
    sensitive << ( shl_ln1118_83_fu_473_p3 );

    SC_METHOD(thread_sext_ln1118_165_fu_493_p1);
    sensitive << ( shl_ln1118_84_fu_485_p3 );

    SC_METHOD(thread_sext_ln1118_166_fu_800_p1);
    sensitive << ( shl_ln1118_85_fu_793_p3 );

    SC_METHOD(thread_sext_ln1118_167_fu_804_p1);
    sensitive << ( shl_ln1118_85_fu_793_p3 );

    SC_METHOD(thread_sext_ln1118_168_fu_566_p1);
    sensitive << ( shl_ln1118_86_fu_558_p3 );

    SC_METHOD(thread_sext_ln1118_169_fu_578_p1);
    sensitive << ( shl_ln1118_87_fu_570_p3 );

    SC_METHOD(thread_sext_ln1118_170_fu_882_p1);
    sensitive << ( shl_ln1118_88_fu_875_p3 );

    SC_METHOD(thread_sext_ln1118_171_fu_893_p1);
    sensitive << ( shl_ln1118_89_fu_886_p3 );

    SC_METHOD(thread_sext_ln1118_172_fu_924_p1);
    sensitive << ( shl_ln1118_90_fu_917_p3 );

    SC_METHOD(thread_sext_ln1118_216_fu_651_p1);
    sensitive << ( tmp_fu_644_p3 );

    SC_METHOD(thread_sext_ln1118_fu_164_p0);
    sensitive << ( data_0_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_sext_ln1118_fu_164_p1);
    sensitive << ( sext_ln1118_fu_164_p0 );

    SC_METHOD(thread_sext_ln703_34_fu_263_p1);
    sensitive << ( tmp_44_fu_253_p4 );

    SC_METHOD(thread_sext_ln703_35_fu_291_p1);
    sensitive << ( add_ln703_191_fu_285_p2 );

    SC_METHOD(thread_sext_ln703_36_fu_944_p1);
    sensitive << ( tmp_45_fu_934_p4 );

    SC_METHOD(thread_sext_ln703_37_fu_960_p1);
    sensitive << ( add_ln703_214_fu_954_p2 );

    SC_METHOD(thread_sext_ln703_fu_840_p1);
    sensitive << ( add_ln703_207_fu_834_p2 );

    SC_METHOD(thread_sext_ln708_104_fu_232_p1);
    sensitive << ( trunc_ln708_126_fu_223_p4 );

    SC_METHOD(thread_sext_ln708_105_fu_671_p1);
    sensitive << ( trunc_ln708_127_fu_661_p4 );

    SC_METHOD(thread_sext_ln708_106_fu_687_p1);
    sensitive << ( trunc_ln708_128_fu_678_p4 );

    SC_METHOD(thread_sext_ln708_110_fu_347_p1);
    sensitive << ( trunc_ln708_130_fu_337_p4 );

    SC_METHOD(thread_sext_ln708_111_fu_360_p1);
    sensitive << ( trunc_ln708_131_fu_351_p4 );

    SC_METHOD(thread_sext_ln708_112_fu_726_p1);
    sensitive << ( trunc_ln708_132_fu_716_p4 );

    SC_METHOD(thread_sext_ln708_113_fu_757_p1);
    sensitive << ( trunc_ln708_133_fu_747_p4 );

    SC_METHOD(thread_sext_ln708_114_fu_382_p1);
    sensitive << ( trunc_ln708_134_fu_373_p4 );

    SC_METHOD(thread_sext_ln708_115_fu_459_p1);
    sensitive << ( trunc_ln708_135_fu_449_p4 );

    SC_METHOD(thread_sext_ln708_116_fu_513_p1);
    sensitive << ( trunc_ln708_137_fu_503_p4 );

    SC_METHOD(thread_sext_ln708_117_fu_527_p1);
    sensitive << ( trunc_ln708_138_fu_517_p4 );

    SC_METHOD(thread_sext_ln708_118_fu_789_p1);
    sensitive << ( trunc_ln708_139_fu_780_p4 );

    SC_METHOD(thread_sext_ln708_119_fu_824_p1);
    sensitive << ( trunc_ln708_140_fu_814_p4 );

    SC_METHOD(thread_sext_ln708_120_fu_616_p1);
    sensitive << ( trunc_ln708_141_fu_607_p4 );

    SC_METHOD(thread_sext_ln708_121_fu_871_p1);
    sensitive << ( trunc_ln708_142_fu_861_p4 );

    SC_METHOD(thread_sext_ln708_122_fu_913_p1);
    sensitive << ( trunc_ln708_143_fu_903_p4 );

    SC_METHOD(thread_sext_ln708_fu_181_p1);
    sensitive << ( trunc_ln_fu_172_p4 );

    SC_METHOD(thread_shl_ln1118_81_fu_730_p3);
    sensitive << ( data_5_V_read_6_reg_1130 );

    SC_METHOD(thread_shl_ln1118_82_fu_425_p1);
    sensitive << ( data_1_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_shl_ln1118_82_fu_425_p3);
    sensitive << ( shl_ln1118_82_fu_425_p1 );

    SC_METHOD(thread_shl_ln1118_83_fu_473_p1);
    sensitive << ( data_3_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_shl_ln1118_83_fu_473_p3);
    sensitive << ( shl_ln1118_83_fu_473_p1 );

    SC_METHOD(thread_shl_ln1118_84_fu_485_p1);
    sensitive << ( data_3_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_shl_ln1118_84_fu_485_p3);
    sensitive << ( shl_ln1118_84_fu_485_p1 );

    SC_METHOD(thread_shl_ln1118_85_fu_793_p3);
    sensitive << ( data_7_V_read_4_reg_1117 );

    SC_METHOD(thread_shl_ln1118_86_fu_558_p1);
    sensitive << ( data_1_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_shl_ln1118_86_fu_558_p3);
    sensitive << ( shl_ln1118_86_fu_558_p1 );

    SC_METHOD(thread_shl_ln1118_87_fu_570_p1);
    sensitive << ( data_1_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_shl_ln1118_87_fu_570_p3);
    sensitive << ( shl_ln1118_87_fu_570_p1 );

    SC_METHOD(thread_shl_ln1118_88_fu_875_p3);
    sensitive << ( data_6_V_read_4_reg_1123 );

    SC_METHOD(thread_shl_ln1118_89_fu_886_p3);
    sensitive << ( data_6_V_read_4_reg_1123 );

    SC_METHOD(thread_shl_ln1118_90_fu_917_p3);
    sensitive << ( data_7_V_read_4_reg_1117 );

    SC_METHOD(thread_shl_ln_fu_319_p1);
    sensitive << ( data_2_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_shl_ln_fu_319_p3);
    sensitive << ( shl_ln_fu_319_p1 );

    SC_METHOD(thread_sub_ln1118_69_fu_741_p2);
    sensitive << ( sext_ln1118_161_fu_737_p1 );
    sensitive << ( sext_ln1118_156_fu_675_p1 );

    SC_METHOD(thread_sub_ln1118_70_fu_437_p2);
    sensitive << ( sext_ln1118_162_fu_433_p1 );

    SC_METHOD(thread_sub_ln1118_71_fu_443_p2);
    sensitive << ( sub_ln1118_70_fu_437_p2 );
    sensitive << ( sext_ln1118_150_fu_189_p1 );

    SC_METHOD(thread_sub_ln1118_72_fu_497_p2);
    sensitive << ( sext_ln1118_164_fu_481_p1 );
    sensitive << ( sext_ln1118_165_fu_493_p1 );

    SC_METHOD(thread_sub_ln1118_73_fu_808_p2);
    sensitive << ( sext_ln1118_167_fu_804_p1 );

    SC_METHOD(thread_sub_ln1118_74_fu_897_p2);
    sensitive << ( sext_ln1118_170_fu_882_p1 );
    sensitive << ( sext_ln1118_171_fu_893_p1 );

    SC_METHOD(thread_sub_ln1118_75_fu_928_p2);
    sensitive << ( sext_ln1118_166_fu_800_p1 );
    sensitive << ( sext_ln1118_172_fu_924_p1 );

    SC_METHOD(thread_sub_ln1118_99_fu_655_p2);
    sensitive << ( sext_ln1118_155_fu_641_p1 );
    sensitive << ( sext_ln1118_216_fu_651_p1 );

    SC_METHOD(thread_sub_ln1118_fu_710_p2);
    sensitive << ( sext_ln1118_155_fu_641_p1 );
    sensitive << ( sext_ln1118_216_fu_651_p1 );

    SC_METHOD(thread_tmp_44_fu_253_p1);
    sensitive << ( data_7_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_tmp_44_fu_253_p4);
    sensitive << ( tmp_44_fu_253_p1 );

    SC_METHOD(thread_tmp_45_fu_934_p4);
    sensitive << ( sub_ln1118_75_fu_928_p2 );

    SC_METHOD(thread_tmp_fu_644_p3);
    sensitive << ( data_4_V_read_7_reg_1136 );

    SC_METHOD(thread_trunc_ln708_126_fu_223_p4);
    sensitive << ( mul_ln1118_54_fu_1026_p2 );

    SC_METHOD(thread_trunc_ln708_127_fu_661_p4);
    sensitive << ( sub_ln1118_99_fu_655_p2 );

    SC_METHOD(thread_trunc_ln708_128_fu_678_p4);
    sensitive << ( mul_ln1118_56_fu_1103_p2 );

    SC_METHOD(thread_trunc_ln708_130_fu_337_p4);
    sensitive << ( add_ln1118_fu_331_p2 );

    SC_METHOD(thread_trunc_ln708_131_fu_351_p4);
    sensitive << ( mul_ln1118_60_fu_1054_p2 );

    SC_METHOD(thread_trunc_ln708_132_fu_716_p4);
    sensitive << ( sub_ln1118_fu_710_p2 );

    SC_METHOD(thread_trunc_ln708_133_fu_747_p4);
    sensitive << ( sub_ln1118_69_fu_741_p2 );

    SC_METHOD(thread_trunc_ln708_134_fu_373_p4);
    sensitive << ( mul_ln1118_62_fu_1068_p2 );

    SC_METHOD(thread_trunc_ln708_135_fu_449_p4);
    sensitive << ( sub_ln1118_71_fu_443_p2 );

    SC_METHOD(thread_trunc_ln708_136_fu_463_p1);
    sensitive << ( data_2_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_trunc_ln708_137_fu_503_p4);
    sensitive << ( sub_ln1118_72_fu_497_p2 );

    SC_METHOD(thread_trunc_ln708_138_fu_517_p1);
    sensitive << ( data_5_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_trunc_ln708_138_fu_517_p4);
    sensitive << ( trunc_ln708_138_fu_517_p1 );

    SC_METHOD(thread_trunc_ln708_139_fu_780_p4);
    sensitive << ( mul_ln1118_64_fu_1110_p2 );

    SC_METHOD(thread_trunc_ln708_140_fu_814_p4);
    sensitive << ( sub_ln1118_73_fu_808_p2 );

    SC_METHOD(thread_trunc_ln708_141_fu_607_p4);
    sensitive << ( mul_ln1118_67_fu_1096_p2 );

    SC_METHOD(thread_trunc_ln708_142_fu_861_p4);
    sensitive << ( mul_ln1118_68_fu_855_p2 );

    SC_METHOD(thread_trunc_ln708_143_fu_903_p4);
    sensitive << ( sub_ln1118_74_fu_897_p2 );

    SC_METHOD(thread_trunc_ln708_64_fu_193_p4);
    sensitive << ( mul_ln1118_52_fu_1012_p2 );

    SC_METHOD(thread_trunc_ln708_65_fu_210_p4);
    sensitive << ( mul_ln1118_53_fu_1019_p2 );

    SC_METHOD(thread_trunc_ln708_69_fu_240_p4);
    sensitive << ( mul_ln1118_57_fu_1033_p2 );

    SC_METHOD(thread_trunc_ln708_71_fu_301_p4);
    sensitive << ( mul_ln1118_58_fu_1040_p2 );

    SC_METHOD(thread_trunc_ln708_72_fu_310_p4);
    sensitive << ( mul_ln1118_59_fu_1047_p2 );

    SC_METHOD(thread_trunc_ln708_77_fu_364_p4);
    sensitive << ( mul_ln1118_61_fu_1061_p2 );

    SC_METHOD(thread_trunc_ln708_79_fu_416_p4);
    sensitive << ( mul_ln1118_63_fu_1075_p2 );

    SC_METHOD(thread_trunc_ln708_87_fu_549_p4);
    sensitive << ( mul_ln1118_65_fu_1082_p2 );

    SC_METHOD(thread_trunc_ln708_88_fu_588_p4);
    sensitive << ( add_ln1118_13_fu_582_p2 );

    SC_METHOD(thread_trunc_ln708_89_fu_598_p4);
    sensitive << ( mul_ln1118_66_fu_1089_p2 );

    SC_METHOD(thread_trunc_ln_fu_172_p4);
    sensitive << ( mul_ln1118_fu_1005_p2 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dense_resource_0_0_1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, data_0_V_read, "(port)data_0_V_read");
    sc_trace(mVcdFile, data_1_V_read, "(port)data_1_V_read");
    sc_trace(mVcdFile, data_2_V_read, "(port)data_2_V_read");
    sc_trace(mVcdFile, data_3_V_read, "(port)data_3_V_read");
    sc_trace(mVcdFile, data_4_V_read, "(port)data_4_V_read");
    sc_trace(mVcdFile, data_5_V_read, "(port)data_5_V_read");
    sc_trace(mVcdFile, data_6_V_read, "(port)data_6_V_read");
    sc_trace(mVcdFile, data_7_V_read, "(port)data_7_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_ce, "(port)ap_ce");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, data_7_V_read_4_reg_1117, "data_7_V_read_4_reg_1117");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, data_6_V_read_4_reg_1123, "data_6_V_read_4_reg_1123");
    sc_trace(mVcdFile, data_5_V_read_6_reg_1130, "data_5_V_read_6_reg_1130");
    sc_trace(mVcdFile, data_4_V_read_7_reg_1136, "data_4_V_read_7_reg_1136");
    sc_trace(mVcdFile, add_ln703_189_fu_279_p2, "add_ln703_189_fu_279_p2");
    sc_trace(mVcdFile, add_ln703_189_reg_1143, "add_ln703_189_reg_1143");
    sc_trace(mVcdFile, add_ln703_192_fu_295_p2, "add_ln703_192_fu_295_p2");
    sc_trace(mVcdFile, add_ln703_192_reg_1148, "add_ln703_192_reg_1148");
    sc_trace(mVcdFile, add_ln703_197_fu_398_p2, "add_ln703_197_fu_398_p2");
    sc_trace(mVcdFile, add_ln703_197_reg_1153, "add_ln703_197_reg_1153");
    sc_trace(mVcdFile, add_ln703_200_fu_410_p2, "add_ln703_200_fu_410_p2");
    sc_trace(mVcdFile, add_ln703_200_reg_1158, "add_ln703_200_reg_1158");
    sc_trace(mVcdFile, trunc_ln708_136_reg_1163, "trunc_ln708_136_reg_1163");
    sc_trace(mVcdFile, add_ln703_205_fu_543_p2, "add_ln703_205_fu_543_p2");
    sc_trace(mVcdFile, add_ln703_205_reg_1168, "add_ln703_205_reg_1168");
    sc_trace(mVcdFile, add_ln703_212_fu_632_p2, "add_ln703_212_fu_632_p2");
    sc_trace(mVcdFile, add_ln703_212_reg_1173, "add_ln703_212_reg_1173");
    sc_trace(mVcdFile, sext_ln1118_fu_164_p0, "sext_ln1118_fu_164_p0");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, mul_ln1118_fu_1005_p2, "mul_ln1118_fu_1005_p2");
    sc_trace(mVcdFile, trunc_ln_fu_172_p4, "trunc_ln_fu_172_p4");
    sc_trace(mVcdFile, sext_ln1118_149_fu_185_p0, "sext_ln1118_149_fu_185_p0");
    sc_trace(mVcdFile, sext_ln1118_150_fu_189_p0, "sext_ln1118_150_fu_189_p0");
    sc_trace(mVcdFile, mul_ln1118_52_fu_1012_p2, "mul_ln1118_52_fu_1012_p2");
    sc_trace(mVcdFile, sext_ln1118_151_fu_202_p0, "sext_ln1118_151_fu_202_p0");
    sc_trace(mVcdFile, sext_ln1118_152_fu_206_p0, "sext_ln1118_152_fu_206_p0");
    sc_trace(mVcdFile, mul_ln1118_53_fu_1019_p2, "mul_ln1118_53_fu_1019_p2");
    sc_trace(mVcdFile, sext_ln1118_153_fu_219_p0, "sext_ln1118_153_fu_219_p0");
    sc_trace(mVcdFile, mul_ln1118_54_fu_1026_p2, "mul_ln1118_54_fu_1026_p2");
    sc_trace(mVcdFile, trunc_ln708_126_fu_223_p4, "trunc_ln708_126_fu_223_p4");
    sc_trace(mVcdFile, sext_ln1118_157_fu_236_p0, "sext_ln1118_157_fu_236_p0");
    sc_trace(mVcdFile, mul_ln1118_57_fu_1033_p2, "mul_ln1118_57_fu_1033_p2");
    sc_trace(mVcdFile, tmp_44_fu_253_p1, "tmp_44_fu_253_p1");
    sc_trace(mVcdFile, tmp_44_fu_253_p4, "tmp_44_fu_253_p4");
    sc_trace(mVcdFile, trunc_ln708_64_fu_193_p4, "trunc_ln708_64_fu_193_p4");
    sc_trace(mVcdFile, sext_ln708_fu_181_p1, "sext_ln708_fu_181_p1");
    sc_trace(mVcdFile, sext_ln708_104_fu_232_p1, "sext_ln708_104_fu_232_p1");
    sc_trace(mVcdFile, trunc_ln708_65_fu_210_p4, "trunc_ln708_65_fu_210_p4");
    sc_trace(mVcdFile, add_ln703_fu_267_p2, "add_ln703_fu_267_p2");
    sc_trace(mVcdFile, add_ln703_188_fu_273_p2, "add_ln703_188_fu_273_p2");
    sc_trace(mVcdFile, sext_ln703_34_fu_263_p1, "sext_ln703_34_fu_263_p1");
    sc_trace(mVcdFile, add_ln703_191_fu_285_p2, "add_ln703_191_fu_285_p2");
    sc_trace(mVcdFile, trunc_ln708_69_fu_240_p4, "trunc_ln708_69_fu_240_p4");
    sc_trace(mVcdFile, sext_ln703_35_fu_291_p1, "sext_ln703_35_fu_291_p1");
    sc_trace(mVcdFile, mul_ln1118_58_fu_1040_p2, "mul_ln1118_58_fu_1040_p2");
    sc_trace(mVcdFile, mul_ln1118_59_fu_1047_p2, "mul_ln1118_59_fu_1047_p2");
    sc_trace(mVcdFile, shl_ln_fu_319_p1, "shl_ln_fu_319_p1");
    sc_trace(mVcdFile, shl_ln_fu_319_p3, "shl_ln_fu_319_p3");
    sc_trace(mVcdFile, sext_ln1118_152_fu_206_p1, "sext_ln1118_152_fu_206_p1");
    sc_trace(mVcdFile, sext_ln1118_159_fu_327_p1, "sext_ln1118_159_fu_327_p1");
    sc_trace(mVcdFile, add_ln1118_fu_331_p2, "add_ln1118_fu_331_p2");
    sc_trace(mVcdFile, trunc_ln708_130_fu_337_p4, "trunc_ln708_130_fu_337_p4");
    sc_trace(mVcdFile, mul_ln1118_60_fu_1054_p2, "mul_ln1118_60_fu_1054_p2");
    sc_trace(mVcdFile, trunc_ln708_131_fu_351_p4, "trunc_ln708_131_fu_351_p4");
    sc_trace(mVcdFile, mul_ln1118_61_fu_1061_p2, "mul_ln1118_61_fu_1061_p2");
    sc_trace(mVcdFile, mul_ln1118_62_fu_1068_p2, "mul_ln1118_62_fu_1068_p2");
    sc_trace(mVcdFile, trunc_ln708_134_fu_373_p4, "trunc_ln708_134_fu_373_p4");
    sc_trace(mVcdFile, trunc_ln708_72_fu_310_p4, "trunc_ln708_72_fu_310_p4");
    sc_trace(mVcdFile, trunc_ln708_71_fu_301_p4, "trunc_ln708_71_fu_301_p4");
    sc_trace(mVcdFile, sext_ln708_111_fu_360_p1, "sext_ln708_111_fu_360_p1");
    sc_trace(mVcdFile, sext_ln708_110_fu_347_p1, "sext_ln708_110_fu_347_p1");
    sc_trace(mVcdFile, add_ln703_195_fu_386_p2, "add_ln703_195_fu_386_p2");
    sc_trace(mVcdFile, add_ln703_196_fu_392_p2, "add_ln703_196_fu_392_p2");
    sc_trace(mVcdFile, sext_ln708_114_fu_382_p1, "sext_ln708_114_fu_382_p1");
    sc_trace(mVcdFile, trunc_ln708_77_fu_364_p4, "trunc_ln708_77_fu_364_p4");
    sc_trace(mVcdFile, add_ln703_199_fu_404_p2, "add_ln703_199_fu_404_p2");
    sc_trace(mVcdFile, mul_ln1118_63_fu_1075_p2, "mul_ln1118_63_fu_1075_p2");
    sc_trace(mVcdFile, shl_ln1118_82_fu_425_p1, "shl_ln1118_82_fu_425_p1");
    sc_trace(mVcdFile, shl_ln1118_82_fu_425_p3, "shl_ln1118_82_fu_425_p3");
    sc_trace(mVcdFile, sext_ln1118_162_fu_433_p1, "sext_ln1118_162_fu_433_p1");
    sc_trace(mVcdFile, sub_ln1118_70_fu_437_p2, "sub_ln1118_70_fu_437_p2");
    sc_trace(mVcdFile, sext_ln1118_150_fu_189_p1, "sext_ln1118_150_fu_189_p1");
    sc_trace(mVcdFile, sub_ln1118_71_fu_443_p2, "sub_ln1118_71_fu_443_p2");
    sc_trace(mVcdFile, trunc_ln708_135_fu_449_p4, "trunc_ln708_135_fu_449_p4");
    sc_trace(mVcdFile, trunc_ln708_136_fu_463_p1, "trunc_ln708_136_fu_463_p1");
    sc_trace(mVcdFile, shl_ln1118_83_fu_473_p1, "shl_ln1118_83_fu_473_p1");
    sc_trace(mVcdFile, shl_ln1118_83_fu_473_p3, "shl_ln1118_83_fu_473_p3");
    sc_trace(mVcdFile, shl_ln1118_84_fu_485_p1, "shl_ln1118_84_fu_485_p1");
    sc_trace(mVcdFile, shl_ln1118_84_fu_485_p3, "shl_ln1118_84_fu_485_p3");
    sc_trace(mVcdFile, sext_ln1118_164_fu_481_p1, "sext_ln1118_164_fu_481_p1");
    sc_trace(mVcdFile, sext_ln1118_165_fu_493_p1, "sext_ln1118_165_fu_493_p1");
    sc_trace(mVcdFile, sub_ln1118_72_fu_497_p2, "sub_ln1118_72_fu_497_p2");
    sc_trace(mVcdFile, trunc_ln708_137_fu_503_p4, "trunc_ln708_137_fu_503_p4");
    sc_trace(mVcdFile, trunc_ln708_138_fu_517_p1, "trunc_ln708_138_fu_517_p1");
    sc_trace(mVcdFile, trunc_ln708_138_fu_517_p4, "trunc_ln708_138_fu_517_p4");
    sc_trace(mVcdFile, sext_ln708_115_fu_459_p1, "sext_ln708_115_fu_459_p1");
    sc_trace(mVcdFile, trunc_ln708_79_fu_416_p4, "trunc_ln708_79_fu_416_p4");
    sc_trace(mVcdFile, sext_ln708_117_fu_527_p1, "sext_ln708_117_fu_527_p1");
    sc_trace(mVcdFile, sext_ln708_116_fu_513_p1, "sext_ln708_116_fu_513_p1");
    sc_trace(mVcdFile, add_ln703_203_fu_531_p2, "add_ln703_203_fu_531_p2");
    sc_trace(mVcdFile, add_ln703_204_fu_537_p2, "add_ln703_204_fu_537_p2");
    sc_trace(mVcdFile, mul_ln1118_65_fu_1082_p2, "mul_ln1118_65_fu_1082_p2");
    sc_trace(mVcdFile, shl_ln1118_86_fu_558_p1, "shl_ln1118_86_fu_558_p1");
    sc_trace(mVcdFile, shl_ln1118_86_fu_558_p3, "shl_ln1118_86_fu_558_p3");
    sc_trace(mVcdFile, shl_ln1118_87_fu_570_p1, "shl_ln1118_87_fu_570_p1");
    sc_trace(mVcdFile, shl_ln1118_87_fu_570_p3, "shl_ln1118_87_fu_570_p3");
    sc_trace(mVcdFile, sext_ln1118_168_fu_566_p1, "sext_ln1118_168_fu_566_p1");
    sc_trace(mVcdFile, sext_ln1118_169_fu_578_p1, "sext_ln1118_169_fu_578_p1");
    sc_trace(mVcdFile, add_ln1118_13_fu_582_p2, "add_ln1118_13_fu_582_p2");
    sc_trace(mVcdFile, mul_ln1118_66_fu_1089_p2, "mul_ln1118_66_fu_1089_p2");
    sc_trace(mVcdFile, mul_ln1118_67_fu_1096_p2, "mul_ln1118_67_fu_1096_p2");
    sc_trace(mVcdFile, trunc_ln708_141_fu_607_p4, "trunc_ln708_141_fu_607_p4");
    sc_trace(mVcdFile, trunc_ln708_88_fu_588_p4, "trunc_ln708_88_fu_588_p4");
    sc_trace(mVcdFile, trunc_ln708_87_fu_549_p4, "trunc_ln708_87_fu_549_p4");
    sc_trace(mVcdFile, sext_ln708_120_fu_616_p1, "sext_ln708_120_fu_616_p1");
    sc_trace(mVcdFile, trunc_ln708_89_fu_598_p4, "trunc_ln708_89_fu_598_p4");
    sc_trace(mVcdFile, add_ln703_210_fu_620_p2, "add_ln703_210_fu_620_p2");
    sc_trace(mVcdFile, add_ln703_211_fu_626_p2, "add_ln703_211_fu_626_p2");
    sc_trace(mVcdFile, tmp_fu_644_p3, "tmp_fu_644_p3");
    sc_trace(mVcdFile, sext_ln1118_155_fu_641_p1, "sext_ln1118_155_fu_641_p1");
    sc_trace(mVcdFile, sext_ln1118_216_fu_651_p1, "sext_ln1118_216_fu_651_p1");
    sc_trace(mVcdFile, sub_ln1118_99_fu_655_p2, "sub_ln1118_99_fu_655_p2");
    sc_trace(mVcdFile, trunc_ln708_127_fu_661_p4, "trunc_ln708_127_fu_661_p4");
    sc_trace(mVcdFile, mul_ln1118_56_fu_1103_p2, "mul_ln1118_56_fu_1103_p2");
    sc_trace(mVcdFile, trunc_ln708_128_fu_678_p4, "trunc_ln708_128_fu_678_p4");
    sc_trace(mVcdFile, sext_ln708_106_fu_687_p1, "sext_ln708_106_fu_687_p1");
    sc_trace(mVcdFile, sext_ln708_105_fu_671_p1, "sext_ln708_105_fu_671_p1");
    sc_trace(mVcdFile, add_ln703_190_fu_694_p2, "add_ln703_190_fu_694_p2");
    sc_trace(mVcdFile, add_ln703_193_fu_700_p2, "add_ln703_193_fu_700_p2");
    sc_trace(mVcdFile, sub_ln1118_fu_710_p2, "sub_ln1118_fu_710_p2");
    sc_trace(mVcdFile, trunc_ln708_132_fu_716_p4, "trunc_ln708_132_fu_716_p4");
    sc_trace(mVcdFile, shl_ln1118_81_fu_730_p3, "shl_ln1118_81_fu_730_p3");
    sc_trace(mVcdFile, sext_ln1118_161_fu_737_p1, "sext_ln1118_161_fu_737_p1");
    sc_trace(mVcdFile, sext_ln1118_156_fu_675_p1, "sext_ln1118_156_fu_675_p1");
    sc_trace(mVcdFile, sub_ln1118_69_fu_741_p2, "sub_ln1118_69_fu_741_p2");
    sc_trace(mVcdFile, trunc_ln708_133_fu_747_p4, "trunc_ln708_133_fu_747_p4");
    sc_trace(mVcdFile, sext_ln708_113_fu_757_p1, "sext_ln708_113_fu_757_p1");
    sc_trace(mVcdFile, sext_ln708_112_fu_726_p1, "sext_ln708_112_fu_726_p1");
    sc_trace(mVcdFile, add_ln703_198_fu_761_p2, "add_ln703_198_fu_761_p2");
    sc_trace(mVcdFile, add_ln703_201_fu_767_p2, "add_ln703_201_fu_767_p2");
    sc_trace(mVcdFile, mul_ln1118_64_fu_1110_p2, "mul_ln1118_64_fu_1110_p2");
    sc_trace(mVcdFile, trunc_ln708_139_fu_780_p4, "trunc_ln708_139_fu_780_p4");
    sc_trace(mVcdFile, shl_ln1118_85_fu_793_p3, "shl_ln1118_85_fu_793_p3");
    sc_trace(mVcdFile, sext_ln1118_167_fu_804_p1, "sext_ln1118_167_fu_804_p1");
    sc_trace(mVcdFile, sub_ln1118_73_fu_808_p2, "sub_ln1118_73_fu_808_p2");
    sc_trace(mVcdFile, trunc_ln708_140_fu_814_p4, "trunc_ln708_140_fu_814_p4");
    sc_trace(mVcdFile, sext_ln708_119_fu_824_p1, "sext_ln708_119_fu_824_p1");
    sc_trace(mVcdFile, sext_ln708_118_fu_789_p1, "sext_ln708_118_fu_789_p1");
    sc_trace(mVcdFile, sext_ln1118_163_fu_777_p1, "sext_ln1118_163_fu_777_p1");
    sc_trace(mVcdFile, add_ln703_207_fu_834_p2, "add_ln703_207_fu_834_p2");
    sc_trace(mVcdFile, add_ln703_206_fu_828_p2, "add_ln703_206_fu_828_p2");
    sc_trace(mVcdFile, sext_ln703_fu_840_p1, "sext_ln703_fu_840_p1");
    sc_trace(mVcdFile, add_ln703_208_fu_844_p2, "add_ln703_208_fu_844_p2");
    sc_trace(mVcdFile, mul_ln1118_68_fu_855_p0, "mul_ln1118_68_fu_855_p0");
    sc_trace(mVcdFile, mul_ln1118_68_fu_855_p2, "mul_ln1118_68_fu_855_p2");
    sc_trace(mVcdFile, trunc_ln708_142_fu_861_p4, "trunc_ln708_142_fu_861_p4");
    sc_trace(mVcdFile, shl_ln1118_88_fu_875_p3, "shl_ln1118_88_fu_875_p3");
    sc_trace(mVcdFile, shl_ln1118_89_fu_886_p3, "shl_ln1118_89_fu_886_p3");
    sc_trace(mVcdFile, sext_ln1118_170_fu_882_p1, "sext_ln1118_170_fu_882_p1");
    sc_trace(mVcdFile, sext_ln1118_171_fu_893_p1, "sext_ln1118_171_fu_893_p1");
    sc_trace(mVcdFile, sub_ln1118_74_fu_897_p2, "sub_ln1118_74_fu_897_p2");
    sc_trace(mVcdFile, trunc_ln708_143_fu_903_p4, "trunc_ln708_143_fu_903_p4");
    sc_trace(mVcdFile, shl_ln1118_90_fu_917_p3, "shl_ln1118_90_fu_917_p3");
    sc_trace(mVcdFile, sext_ln1118_166_fu_800_p1, "sext_ln1118_166_fu_800_p1");
    sc_trace(mVcdFile, sext_ln1118_172_fu_924_p1, "sext_ln1118_172_fu_924_p1");
    sc_trace(mVcdFile, sub_ln1118_75_fu_928_p2, "sub_ln1118_75_fu_928_p2");
    sc_trace(mVcdFile, tmp_45_fu_934_p4, "tmp_45_fu_934_p4");
    sc_trace(mVcdFile, sext_ln708_121_fu_871_p1, "sext_ln708_121_fu_871_p1");
    sc_trace(mVcdFile, sext_ln703_36_fu_944_p1, "sext_ln703_36_fu_944_p1");
    sc_trace(mVcdFile, add_ln703_214_fu_954_p2, "add_ln703_214_fu_954_p2");
    sc_trace(mVcdFile, sext_ln708_122_fu_913_p1, "sext_ln708_122_fu_913_p1");
    sc_trace(mVcdFile, sext_ln703_37_fu_960_p1, "sext_ln703_37_fu_960_p1");
    sc_trace(mVcdFile, add_ln703_213_fu_948_p2, "add_ln703_213_fu_948_p2");
    sc_trace(mVcdFile, add_ln703_215_fu_964_p2, "add_ln703_215_fu_964_p2");
    sc_trace(mVcdFile, add_ln703_216_fu_970_p2, "add_ln703_216_fu_970_p2");
    sc_trace(mVcdFile, add_ln703_273_fu_705_p2, "add_ln703_273_fu_705_p2");
    sc_trace(mVcdFile, add_ln703_274_fu_772_p2, "add_ln703_274_fu_772_p2");
    sc_trace(mVcdFile, add_ln703_275_fu_850_p2, "add_ln703_275_fu_850_p2");
    sc_trace(mVcdFile, add_ln703_276_fu_976_p2, "add_ln703_276_fu_976_p2");
    sc_trace(mVcdFile, mul_ln1118_fu_1005_p1, "mul_ln1118_fu_1005_p1");
    sc_trace(mVcdFile, mul_ln1118_52_fu_1012_p0, "mul_ln1118_52_fu_1012_p0");
    sc_trace(mVcdFile, sext_ln1118_149_fu_185_p1, "sext_ln1118_149_fu_185_p1");
    sc_trace(mVcdFile, mul_ln1118_52_fu_1012_p1, "mul_ln1118_52_fu_1012_p1");
    sc_trace(mVcdFile, mul_ln1118_53_fu_1019_p0, "mul_ln1118_53_fu_1019_p0");
    sc_trace(mVcdFile, sext_ln1118_151_fu_202_p1, "sext_ln1118_151_fu_202_p1");
    sc_trace(mVcdFile, mul_ln1118_53_fu_1019_p1, "mul_ln1118_53_fu_1019_p1");
    sc_trace(mVcdFile, mul_ln1118_54_fu_1026_p0, "mul_ln1118_54_fu_1026_p0");
    sc_trace(mVcdFile, sext_ln1118_153_fu_219_p1, "sext_ln1118_153_fu_219_p1");
    sc_trace(mVcdFile, mul_ln1118_54_fu_1026_p1, "mul_ln1118_54_fu_1026_p1");
    sc_trace(mVcdFile, mul_ln1118_57_fu_1033_p0, "mul_ln1118_57_fu_1033_p0");
    sc_trace(mVcdFile, sext_ln1118_157_fu_236_p1, "sext_ln1118_157_fu_236_p1");
    sc_trace(mVcdFile, mul_ln1118_57_fu_1033_p1, "mul_ln1118_57_fu_1033_p1");
    sc_trace(mVcdFile, mul_ln1118_58_fu_1040_p0, "mul_ln1118_58_fu_1040_p0");
    sc_trace(mVcdFile, sext_ln1118_fu_164_p1, "sext_ln1118_fu_164_p1");
    sc_trace(mVcdFile, mul_ln1118_58_fu_1040_p1, "mul_ln1118_58_fu_1040_p1");
    sc_trace(mVcdFile, mul_ln1118_59_fu_1047_p0, "mul_ln1118_59_fu_1047_p0");
    sc_trace(mVcdFile, mul_ln1118_59_fu_1047_p1, "mul_ln1118_59_fu_1047_p1");
    sc_trace(mVcdFile, mul_ln1118_60_fu_1054_p0, "mul_ln1118_60_fu_1054_p0");
    sc_trace(mVcdFile, mul_ln1118_60_fu_1054_p1, "mul_ln1118_60_fu_1054_p1");
    sc_trace(mVcdFile, mul_ln1118_61_fu_1061_p0, "mul_ln1118_61_fu_1061_p0");
    sc_trace(mVcdFile, mul_ln1118_61_fu_1061_p1, "mul_ln1118_61_fu_1061_p1");
    sc_trace(mVcdFile, mul_ln1118_62_fu_1068_p1, "mul_ln1118_62_fu_1068_p1");
    sc_trace(mVcdFile, mul_ln1118_63_fu_1075_p0, "mul_ln1118_63_fu_1075_p0");
    sc_trace(mVcdFile, mul_ln1118_63_fu_1075_p1, "mul_ln1118_63_fu_1075_p1");
    sc_trace(mVcdFile, mul_ln1118_65_fu_1082_p0, "mul_ln1118_65_fu_1082_p0");
    sc_trace(mVcdFile, mul_ln1118_65_fu_1082_p1, "mul_ln1118_65_fu_1082_p1");
    sc_trace(mVcdFile, mul_ln1118_66_fu_1089_p0, "mul_ln1118_66_fu_1089_p0");
    sc_trace(mVcdFile, mul_ln1118_66_fu_1089_p1, "mul_ln1118_66_fu_1089_p1");
    sc_trace(mVcdFile, mul_ln1118_67_fu_1096_p0, "mul_ln1118_67_fu_1096_p0");
    sc_trace(mVcdFile, mul_ln1118_67_fu_1096_p1, "mul_ln1118_67_fu_1096_p1");
    sc_trace(mVcdFile, mul_ln1118_56_fu_1103_p0, "mul_ln1118_56_fu_1103_p0");
    sc_trace(mVcdFile, mul_ln1118_56_fu_1103_p1, "mul_ln1118_56_fu_1103_p1");
    sc_trace(mVcdFile, mul_ln1118_64_fu_1110_p1, "mul_ln1118_64_fu_1110_p1");
    sc_trace(mVcdFile, ap_ce_reg, "ap_ce_reg");
    sc_trace(mVcdFile, ap_return_0_int_reg, "ap_return_0_int_reg");
    sc_trace(mVcdFile, ap_return_1_int_reg, "ap_return_1_int_reg");
    sc_trace(mVcdFile, ap_return_2_int_reg, "ap_return_2_int_reg");
    sc_trace(mVcdFile, ap_return_3_int_reg, "ap_return_3_int_reg");
#endif

    }
}

dense_resource_0_0_1::~dense_resource_0_0_1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete example_mul_mul_1tde_U674;
    delete example_mul_mul_1mb6_U675;
    delete example_mul_mul_1ncg_U676;
    delete example_mul_mul_1tde_U677;
    delete example_mul_mul_1mb6_U678;
    delete example_mul_mul_1ocq_U679;
    delete example_mul_mul_1vdy_U680;
    delete example_mul_mul_1tde_U681;
    delete example_mul_mul_1pcA_U682;
    delete example_mul_mul_1tde_U683;
    delete example_mul_mul_1wdI_U684;
    delete example_mul_mul_1sc4_U685;
    delete example_mul_mul_1sc4_U686;
    delete example_mul_mul_1rcU_U687;
    delete example_mul_mul_1rcU_U688;
    delete example_mul_mul_1rcU_U689;
}

void dense_resource_0_0_1::thread_ap_clk_no_reset_() {
    ap_ce_reg = ap_ce.read();
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1))) {
        add_ln703_189_reg_1143 = add_ln703_189_fu_279_p2.read();
        add_ln703_192_reg_1148 = add_ln703_192_fu_295_p2.read();
        add_ln703_197_reg_1153 = add_ln703_197_fu_398_p2.read();
        add_ln703_200_reg_1158 = add_ln703_200_fu_410_p2.read();
        add_ln703_205_reg_1168 = add_ln703_205_fu_543_p2.read();
        add_ln703_212_reg_1173 = add_ln703_212_fu_632_p2.read();
        data_4_V_read_7_reg_1136 = data_4_V_read.read();
        data_5_V_read_6_reg_1130 = data_5_V_read.read();
        data_6_V_read_4_reg_1123 = data_6_V_read.read();
        data_7_V_read_4_reg_1117 = data_7_V_read.read();
        trunc_ln708_136_reg_1163 = trunc_ln708_136_fu_463_p1.read().range(13, 7);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_0_int_reg = add_ln703_273_fu_705_p2.read();
        ap_return_1_int_reg = add_ln703_274_fu_772_p2.read();
        ap_return_2_int_reg = add_ln703_275_fu_850_p2.read();
        ap_return_3_int_reg = add_ln703_276_fu_976_p2.read();
    }
}

void dense_resource_0_0_1::thread_add_ln1118_13_fu_582_p2() {
    add_ln1118_13_fu_582_p2 = (!sext_ln1118_168_fu_566_p1.read().is_01() || !sext_ln1118_169_fu_578_p1.read().is_01())? sc_lv<21>(): (sc_bigint<21>(sext_ln1118_168_fu_566_p1.read()) + sc_bigint<21>(sext_ln1118_169_fu_578_p1.read()));
}

void dense_resource_0_0_1::thread_add_ln1118_fu_331_p2() {
    add_ln1118_fu_331_p2 = (!sext_ln1118_152_fu_206_p1.read().is_01() || !sext_ln1118_159_fu_327_p1.read().is_01())? sc_lv<17>(): (sc_bigint<17>(sext_ln1118_152_fu_206_p1.read()) + sc_bigint<17>(sext_ln1118_159_fu_327_p1.read()));
}

void dense_resource_0_0_1::thread_add_ln703_188_fu_273_p2() {
    add_ln703_188_fu_273_p2 = (!sext_ln708_104_fu_232_p1.read().is_01() || !trunc_ln708_65_fu_210_p4.read().is_01())? sc_lv<14>(): (sc_bigint<14>(sext_ln708_104_fu_232_p1.read()) + sc_biguint<14>(trunc_ln708_65_fu_210_p4.read()));
}

void dense_resource_0_0_1::thread_add_ln703_189_fu_279_p2() {
    add_ln703_189_fu_279_p2 = (!add_ln703_fu_267_p2.read().is_01() || !add_ln703_188_fu_273_p2.read().is_01())? sc_lv<14>(): (sc_biguint<14>(add_ln703_fu_267_p2.read()) + sc_biguint<14>(add_ln703_188_fu_273_p2.read()));
}

void dense_resource_0_0_1::thread_add_ln703_190_fu_694_p2() {
    add_ln703_190_fu_694_p2 = (!sext_ln708_106_fu_687_p1.read().is_01() || !sext_ln708_105_fu_671_p1.read().is_01())? sc_lv<14>(): (sc_bigint<14>(sext_ln708_106_fu_687_p1.read()) + sc_bigint<14>(sext_ln708_105_fu_671_p1.read()));
}

void dense_resource_0_0_1::thread_add_ln703_191_fu_285_p2() {
    add_ln703_191_fu_285_p2 = (!sext_ln703_34_fu_263_p1.read().is_01() || !ap_const_lv13_1FDF.is_01())? sc_lv<13>(): (sc_bigint<13>(sext_ln703_34_fu_263_p1.read()) + sc_bigint<13>(ap_const_lv13_1FDF));
}

void dense_resource_0_0_1::thread_add_ln703_192_fu_295_p2() {
    add_ln703_192_fu_295_p2 = (!trunc_ln708_69_fu_240_p4.read().is_01() || !sext_ln703_35_fu_291_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(trunc_ln708_69_fu_240_p4.read()) + sc_bigint<14>(sext_ln703_35_fu_291_p1.read()));
}

void dense_resource_0_0_1::thread_add_ln703_193_fu_700_p2() {
    add_ln703_193_fu_700_p2 = (!add_ln703_190_fu_694_p2.read().is_01() || !add_ln703_192_reg_1148.read().is_01())? sc_lv<14>(): (sc_biguint<14>(add_ln703_190_fu_694_p2.read()) + sc_biguint<14>(add_ln703_192_reg_1148.read()));
}

void dense_resource_0_0_1::thread_add_ln703_195_fu_386_p2() {
    add_ln703_195_fu_386_p2 = (!trunc_ln708_72_fu_310_p4.read().is_01() || !trunc_ln708_71_fu_301_p4.read().is_01())? sc_lv<14>(): (sc_biguint<14>(trunc_ln708_72_fu_310_p4.read()) + sc_biguint<14>(trunc_ln708_71_fu_301_p4.read()));
}

void dense_resource_0_0_1::thread_add_ln703_196_fu_392_p2() {
    add_ln703_196_fu_392_p2 = (!sext_ln708_111_fu_360_p1.read().is_01() || !sext_ln708_110_fu_347_p1.read().is_01())? sc_lv<14>(): (sc_bigint<14>(sext_ln708_111_fu_360_p1.read()) + sc_bigint<14>(sext_ln708_110_fu_347_p1.read()));
}

void dense_resource_0_0_1::thread_add_ln703_197_fu_398_p2() {
    add_ln703_197_fu_398_p2 = (!add_ln703_195_fu_386_p2.read().is_01() || !add_ln703_196_fu_392_p2.read().is_01())? sc_lv<14>(): (sc_biguint<14>(add_ln703_195_fu_386_p2.read()) + sc_biguint<14>(add_ln703_196_fu_392_p2.read()));
}

void dense_resource_0_0_1::thread_add_ln703_198_fu_761_p2() {
    add_ln703_198_fu_761_p2 = (!sext_ln708_113_fu_757_p1.read().is_01() || !sext_ln708_112_fu_726_p1.read().is_01())? sc_lv<14>(): (sc_bigint<14>(sext_ln708_113_fu_757_p1.read()) + sc_bigint<14>(sext_ln708_112_fu_726_p1.read()));
}

void dense_resource_0_0_1::thread_add_ln703_199_fu_404_p2() {
    add_ln703_199_fu_404_p2 = (!sext_ln708_114_fu_382_p1.read().is_01() || !ap_const_lv14_3FDE.is_01())? sc_lv<14>(): (sc_bigint<14>(sext_ln708_114_fu_382_p1.read()) + sc_bigint<14>(ap_const_lv14_3FDE));
}

void dense_resource_0_0_1::thread_add_ln703_200_fu_410_p2() {
    add_ln703_200_fu_410_p2 = (!trunc_ln708_77_fu_364_p4.read().is_01() || !add_ln703_199_fu_404_p2.read().is_01())? sc_lv<14>(): (sc_biguint<14>(trunc_ln708_77_fu_364_p4.read()) + sc_biguint<14>(add_ln703_199_fu_404_p2.read()));
}

void dense_resource_0_0_1::thread_add_ln703_201_fu_767_p2() {
    add_ln703_201_fu_767_p2 = (!add_ln703_198_fu_761_p2.read().is_01() || !add_ln703_200_reg_1158.read().is_01())? sc_lv<14>(): (sc_biguint<14>(add_ln703_198_fu_761_p2.read()) + sc_biguint<14>(add_ln703_200_reg_1158.read()));
}

void dense_resource_0_0_1::thread_add_ln703_203_fu_531_p2() {
    add_ln703_203_fu_531_p2 = (!sext_ln708_115_fu_459_p1.read().is_01() || !trunc_ln708_79_fu_416_p4.read().is_01())? sc_lv<14>(): (sc_bigint<14>(sext_ln708_115_fu_459_p1.read()) + sc_biguint<14>(trunc_ln708_79_fu_416_p4.read()));
}

void dense_resource_0_0_1::thread_add_ln703_204_fu_537_p2() {
    add_ln703_204_fu_537_p2 = (!sext_ln708_117_fu_527_p1.read().is_01() || !sext_ln708_116_fu_513_p1.read().is_01())? sc_lv<14>(): (sc_bigint<14>(sext_ln708_117_fu_527_p1.read()) + sc_bigint<14>(sext_ln708_116_fu_513_p1.read()));
}

void dense_resource_0_0_1::thread_add_ln703_205_fu_543_p2() {
    add_ln703_205_fu_543_p2 = (!add_ln703_203_fu_531_p2.read().is_01() || !add_ln703_204_fu_537_p2.read().is_01())? sc_lv<14>(): (sc_biguint<14>(add_ln703_203_fu_531_p2.read()) + sc_biguint<14>(add_ln703_204_fu_537_p2.read()));
}

void dense_resource_0_0_1::thread_add_ln703_206_fu_828_p2() {
    add_ln703_206_fu_828_p2 = (!sext_ln708_119_fu_824_p1.read().is_01() || !sext_ln708_118_fu_789_p1.read().is_01())? sc_lv<14>(): (sc_bigint<14>(sext_ln708_119_fu_824_p1.read()) + sc_bigint<14>(sext_ln708_118_fu_789_p1.read()));
}

void dense_resource_0_0_1::thread_add_ln703_207_fu_834_p2() {
    add_ln703_207_fu_834_p2 = (!sext_ln1118_163_fu_777_p1.read().is_01() || !ap_const_lv8_33.is_01())? sc_lv<8>(): (sc_bigint<8>(sext_ln1118_163_fu_777_p1.read()) + sc_biguint<8>(ap_const_lv8_33));
}

void dense_resource_0_0_1::thread_add_ln703_208_fu_844_p2() {
    add_ln703_208_fu_844_p2 = (!add_ln703_206_fu_828_p2.read().is_01() || !sext_ln703_fu_840_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(add_ln703_206_fu_828_p2.read()) + sc_bigint<14>(sext_ln703_fu_840_p1.read()));
}

void dense_resource_0_0_1::thread_add_ln703_210_fu_620_p2() {
    add_ln703_210_fu_620_p2 = (!trunc_ln708_88_fu_588_p4.read().is_01() || !trunc_ln708_87_fu_549_p4.read().is_01())? sc_lv<14>(): (sc_biguint<14>(trunc_ln708_88_fu_588_p4.read()) + sc_biguint<14>(trunc_ln708_87_fu_549_p4.read()));
}

void dense_resource_0_0_1::thread_add_ln703_211_fu_626_p2() {
    add_ln703_211_fu_626_p2 = (!sext_ln708_120_fu_616_p1.read().is_01() || !trunc_ln708_89_fu_598_p4.read().is_01())? sc_lv<14>(): (sc_bigint<14>(sext_ln708_120_fu_616_p1.read()) + sc_biguint<14>(trunc_ln708_89_fu_598_p4.read()));
}

void dense_resource_0_0_1::thread_add_ln703_212_fu_632_p2() {
    add_ln703_212_fu_632_p2 = (!add_ln703_210_fu_620_p2.read().is_01() || !add_ln703_211_fu_626_p2.read().is_01())? sc_lv<14>(): (sc_biguint<14>(add_ln703_210_fu_620_p2.read()) + sc_biguint<14>(add_ln703_211_fu_626_p2.read()));
}

void dense_resource_0_0_1::thread_add_ln703_213_fu_948_p2() {
    add_ln703_213_fu_948_p2 = (!sext_ln708_106_fu_687_p1.read().is_01() || !sext_ln708_121_fu_871_p1.read().is_01())? sc_lv<14>(): (sc_bigint<14>(sext_ln708_106_fu_687_p1.read()) + sc_bigint<14>(sext_ln708_121_fu_871_p1.read()));
}

void dense_resource_0_0_1::thread_add_ln703_214_fu_954_p2() {
    add_ln703_214_fu_954_p2 = (!sext_ln703_36_fu_944_p1.read().is_01() || !ap_const_lv13_1FDB.is_01())? sc_lv<13>(): (sc_bigint<13>(sext_ln703_36_fu_944_p1.read()) + sc_bigint<13>(ap_const_lv13_1FDB));
}

void dense_resource_0_0_1::thread_add_ln703_215_fu_964_p2() {
    add_ln703_215_fu_964_p2 = (!sext_ln708_122_fu_913_p1.read().is_01() || !sext_ln703_37_fu_960_p1.read().is_01())? sc_lv<14>(): (sc_bigint<14>(sext_ln708_122_fu_913_p1.read()) + sc_bigint<14>(sext_ln703_37_fu_960_p1.read()));
}

void dense_resource_0_0_1::thread_add_ln703_216_fu_970_p2() {
    add_ln703_216_fu_970_p2 = (!add_ln703_213_fu_948_p2.read().is_01() || !add_ln703_215_fu_964_p2.read().is_01())? sc_lv<14>(): (sc_biguint<14>(add_ln703_213_fu_948_p2.read()) + sc_biguint<14>(add_ln703_215_fu_964_p2.read()));
}

void dense_resource_0_0_1::thread_add_ln703_273_fu_705_p2() {
    add_ln703_273_fu_705_p2 = (!add_ln703_189_reg_1143.read().is_01() || !add_ln703_193_fu_700_p2.read().is_01())? sc_lv<14>(): (sc_biguint<14>(add_ln703_189_reg_1143.read()) + sc_biguint<14>(add_ln703_193_fu_700_p2.read()));
}

void dense_resource_0_0_1::thread_add_ln703_274_fu_772_p2() {
    add_ln703_274_fu_772_p2 = (!add_ln703_197_reg_1153.read().is_01() || !add_ln703_201_fu_767_p2.read().is_01())? sc_lv<14>(): (sc_biguint<14>(add_ln703_197_reg_1153.read()) + sc_biguint<14>(add_ln703_201_fu_767_p2.read()));
}

void dense_resource_0_0_1::thread_add_ln703_275_fu_850_p2() {
    add_ln703_275_fu_850_p2 = (!add_ln703_205_reg_1168.read().is_01() || !add_ln703_208_fu_844_p2.read().is_01())? sc_lv<14>(): (sc_biguint<14>(add_ln703_205_reg_1168.read()) + sc_biguint<14>(add_ln703_208_fu_844_p2.read()));
}

void dense_resource_0_0_1::thread_add_ln703_276_fu_976_p2() {
    add_ln703_276_fu_976_p2 = (!add_ln703_212_reg_1173.read().is_01() || !add_ln703_216_fu_970_p2.read().is_01())? sc_lv<14>(): (sc_biguint<14>(add_ln703_212_reg_1173.read()) + sc_biguint<14>(add_ln703_216_fu_970_p2.read()));
}

void dense_resource_0_0_1::thread_add_ln703_fu_267_p2() {
    add_ln703_fu_267_p2 = (!trunc_ln708_64_fu_193_p4.read().is_01() || !sext_ln708_fu_181_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(trunc_ln708_64_fu_193_p4.read()) + sc_bigint<14>(sext_ln708_fu_181_p1.read()));
}

void dense_resource_0_0_1::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_resource_0_0_1::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_resource_0_0_1::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_resource_0_0_1::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_resource_0_0_1::thread_ap_return_0() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_0 = ap_return_0_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_0 = add_ln703_273_fu_705_p2.read();
    }
}

void dense_resource_0_0_1::thread_ap_return_1() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_1 = ap_return_1_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_1 = add_ln703_274_fu_772_p2.read();
    }
}

void dense_resource_0_0_1::thread_ap_return_2() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_2 = ap_return_2_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_2 = add_ln703_275_fu_850_p2.read();
    }
}

void dense_resource_0_0_1::thread_ap_return_3() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return_3 = ap_return_3_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_3 = add_ln703_276_fu_976_p2.read();
    }
}

void dense_resource_0_0_1::thread_mul_ln1118_52_fu_1012_p0() {
    mul_ln1118_52_fu_1012_p0 =  (sc_lv<14>) (sext_ln1118_149_fu_185_p1.read());
}

void dense_resource_0_0_1::thread_mul_ln1118_52_fu_1012_p1() {
    mul_ln1118_52_fu_1012_p1 =  (sc_lv<10>) (ap_const_lv21_1FFE05);
}

void dense_resource_0_0_1::thread_mul_ln1118_53_fu_1019_p0() {
    mul_ln1118_53_fu_1019_p0 =  (sc_lv<14>) (sext_ln1118_151_fu_202_p1.read());
}

void dense_resource_0_0_1::thread_mul_ln1118_53_fu_1019_p1() {
    mul_ln1118_53_fu_1019_p1 =  (sc_lv<7>) (ap_const_lv21_2A);
}

void dense_resource_0_0_1::thread_mul_ln1118_54_fu_1026_p0() {
    mul_ln1118_54_fu_1026_p0 =  (sc_lv<14>) (sext_ln1118_153_fu_219_p1.read());
}

void dense_resource_0_0_1::thread_mul_ln1118_54_fu_1026_p1() {
    mul_ln1118_54_fu_1026_p1 =  (sc_lv<6>) (ap_const_lv20_13);
}

void dense_resource_0_0_1::thread_mul_ln1118_56_fu_1103_p0() {
    mul_ln1118_56_fu_1103_p0 =  (sc_lv<14>) (sext_ln1118_156_fu_675_p1.read());
}

void dense_resource_0_0_1::thread_mul_ln1118_56_fu_1103_p1() {
    mul_ln1118_56_fu_1103_p1 =  (sc_lv<6>) (ap_const_lv20_FFFEB);
}

void dense_resource_0_0_1::thread_mul_ln1118_57_fu_1033_p0() {
    mul_ln1118_57_fu_1033_p0 =  (sc_lv<14>) (sext_ln1118_157_fu_236_p1.read());
}

void dense_resource_0_0_1::thread_mul_ln1118_57_fu_1033_p1() {
    mul_ln1118_57_fu_1033_p1 =  (sc_lv<10>) (ap_const_lv21_1FFEE4);
}

void dense_resource_0_0_1::thread_mul_ln1118_58_fu_1040_p0() {
    mul_ln1118_58_fu_1040_p0 =  (sc_lv<14>) (sext_ln1118_fu_164_p1.read());
}

void dense_resource_0_0_1::thread_mul_ln1118_58_fu_1040_p1() {
    mul_ln1118_58_fu_1040_p1 =  (sc_lv<7>) (ap_const_lv21_1FFFD3);
}

void dense_resource_0_0_1::thread_mul_ln1118_59_fu_1047_p0() {
    mul_ln1118_59_fu_1047_p0 =  (sc_lv<14>) (sext_ln1118_149_fu_185_p1.read());
}

void dense_resource_0_0_1::thread_mul_ln1118_59_fu_1047_p1() {
    mul_ln1118_59_fu_1047_p1 =  (sc_lv<11>) (ap_const_lv21_2B7);
}

void dense_resource_0_0_1::thread_mul_ln1118_60_fu_1054_p0() {
    mul_ln1118_60_fu_1054_p0 =  (sc_lv<14>) (sext_ln1118_153_fu_219_p1.read());
}

void dense_resource_0_0_1::thread_mul_ln1118_60_fu_1054_p1() {
    mul_ln1118_60_fu_1054_p1 =  (sc_lv<6>) (ap_const_lv20_16);
}

void dense_resource_0_0_1::thread_mul_ln1118_61_fu_1061_p0() {
    mul_ln1118_61_fu_1061_p0 =  (sc_lv<14>) (sext_ln1118_157_fu_236_p1.read());
}

void dense_resource_0_0_1::thread_mul_ln1118_61_fu_1061_p1() {
    mul_ln1118_61_fu_1061_p1 =  (sc_lv<10>) (ap_const_lv21_158);
}

void dense_resource_0_0_1::thread_mul_ln1118_62_fu_1068_p1() {
    mul_ln1118_62_fu_1068_p1 =  (sc_lv<6>) (ap_const_lv20_13);
}

void dense_resource_0_0_1::thread_mul_ln1118_63_fu_1075_p0() {
    mul_ln1118_63_fu_1075_p0 =  (sc_lv<14>) (sext_ln1118_fu_164_p1.read());
}

void dense_resource_0_0_1::thread_mul_ln1118_63_fu_1075_p1() {
    mul_ln1118_63_fu_1075_p1 =  (sc_lv<8>) (ap_const_lv21_57);
}

void dense_resource_0_0_1::thread_mul_ln1118_64_fu_1110_p1() {
    mul_ln1118_64_fu_1110_p1 =  (sc_lv<6>) (ap_const_lv20_FFFE3);
}

void dense_resource_0_0_1::thread_mul_ln1118_65_fu_1082_p0() {
    mul_ln1118_65_fu_1082_p0 =  (sc_lv<14>) (sext_ln1118_fu_164_p1.read());
}

void dense_resource_0_0_1::thread_mul_ln1118_65_fu_1082_p1() {
    mul_ln1118_65_fu_1082_p1 =  (sc_lv<8>) (ap_const_lv21_1FFF93);
}

void dense_resource_0_0_1::thread_mul_ln1118_66_fu_1089_p0() {
    mul_ln1118_66_fu_1089_p0 =  (sc_lv<14>) (sext_ln1118_151_fu_202_p1.read());
}

void dense_resource_0_0_1::thread_mul_ln1118_66_fu_1089_p1() {
    mul_ln1118_66_fu_1089_p1 =  (sc_lv<8>) (ap_const_lv21_1FFFB5);
}

void dense_resource_0_0_1::thread_mul_ln1118_67_fu_1096_p0() {
    mul_ln1118_67_fu_1096_p0 =  (sc_lv<14>) (sext_ln1118_153_fu_219_p1.read());
}

void dense_resource_0_0_1::thread_mul_ln1118_67_fu_1096_p1() {
    mul_ln1118_67_fu_1096_p1 =  (sc_lv<6>) (ap_const_lv20_FFFE7);
}

void dense_resource_0_0_1::thread_mul_ln1118_68_fu_855_p0() {
    mul_ln1118_68_fu_855_p0 = data_4_V_read_7_reg_1136.read();
}

void dense_resource_0_0_1::thread_mul_ln1118_68_fu_855_p2() {
    mul_ln1118_68_fu_855_p2 = (!mul_ln1118_68_fu_855_p0.read().is_01() || !ap_const_lv19_7FFF3.is_01())? sc_lv<19>(): sc_bigint<14>(mul_ln1118_68_fu_855_p0.read()) * sc_bigint<19>(ap_const_lv19_7FFF3);
}

void dense_resource_0_0_1::thread_mul_ln1118_fu_1005_p1() {
    mul_ln1118_fu_1005_p1 =  (sc_lv<6>) (ap_const_lv20_17);
}

void dense_resource_0_0_1::thread_sext_ln1118_149_fu_185_p0() {
    sext_ln1118_149_fu_185_p0 = data_1_V_read.read();
}

void dense_resource_0_0_1::thread_sext_ln1118_149_fu_185_p1() {
    sext_ln1118_149_fu_185_p1 = esl_sext<21,14>(sext_ln1118_149_fu_185_p0.read());
}

void dense_resource_0_0_1::thread_sext_ln1118_150_fu_189_p0() {
    sext_ln1118_150_fu_189_p0 = data_1_V_read.read();
}

void dense_resource_0_0_1::thread_sext_ln1118_150_fu_189_p1() {
    sext_ln1118_150_fu_189_p1 = esl_sext<17,14>(sext_ln1118_150_fu_189_p0.read());
}

void dense_resource_0_0_1::thread_sext_ln1118_151_fu_202_p0() {
    sext_ln1118_151_fu_202_p0 = data_2_V_read.read();
}

void dense_resource_0_0_1::thread_sext_ln1118_151_fu_202_p1() {
    sext_ln1118_151_fu_202_p1 = esl_sext<21,14>(sext_ln1118_151_fu_202_p0.read());
}

void dense_resource_0_0_1::thread_sext_ln1118_152_fu_206_p0() {
    sext_ln1118_152_fu_206_p0 = data_2_V_read.read();
}

void dense_resource_0_0_1::thread_sext_ln1118_152_fu_206_p1() {
    sext_ln1118_152_fu_206_p1 = esl_sext<17,14>(sext_ln1118_152_fu_206_p0.read());
}

void dense_resource_0_0_1::thread_sext_ln1118_153_fu_219_p0() {
    sext_ln1118_153_fu_219_p0 = data_3_V_read.read();
}

void dense_resource_0_0_1::thread_sext_ln1118_153_fu_219_p1() {
    sext_ln1118_153_fu_219_p1 = esl_sext<20,14>(sext_ln1118_153_fu_219_p0.read());
}

void dense_resource_0_0_1::thread_sext_ln1118_155_fu_641_p1() {
    sext_ln1118_155_fu_641_p1 = esl_sext<18,14>(data_4_V_read_7_reg_1136.read());
}

void dense_resource_0_0_1::thread_sext_ln1118_156_fu_675_p1() {
    sext_ln1118_156_fu_675_p1 = esl_sext<20,14>(data_5_V_read_6_reg_1130.read());
}

void dense_resource_0_0_1::thread_sext_ln1118_157_fu_236_p0() {
    sext_ln1118_157_fu_236_p0 = data_6_V_read.read();
}

void dense_resource_0_0_1::thread_sext_ln1118_157_fu_236_p1() {
    sext_ln1118_157_fu_236_p1 = esl_sext<21,14>(sext_ln1118_157_fu_236_p0.read());
}

void dense_resource_0_0_1::thread_sext_ln1118_159_fu_327_p1() {
    sext_ln1118_159_fu_327_p1 = esl_sext<17,16>(shl_ln_fu_319_p3.read());
}

void dense_resource_0_0_1::thread_sext_ln1118_161_fu_737_p1() {
    sext_ln1118_161_fu_737_p1 = esl_sext<20,19>(shl_ln1118_81_fu_730_p3.read());
}

void dense_resource_0_0_1::thread_sext_ln1118_162_fu_433_p1() {
    sext_ln1118_162_fu_433_p1 = esl_sext<17,16>(shl_ln1118_82_fu_425_p3.read());
}

void dense_resource_0_0_1::thread_sext_ln1118_163_fu_777_p1() {
    sext_ln1118_163_fu_777_p1 = esl_sext<8,7>(trunc_ln708_136_reg_1163.read());
}

void dense_resource_0_0_1::thread_sext_ln1118_164_fu_481_p1() {
    sext_ln1118_164_fu_481_p1 = esl_sext<20,19>(shl_ln1118_83_fu_473_p3.read());
}

void dense_resource_0_0_1::thread_sext_ln1118_165_fu_493_p1() {
    sext_ln1118_165_fu_493_p1 = esl_sext<20,17>(shl_ln1118_84_fu_485_p3.read());
}

void dense_resource_0_0_1::thread_sext_ln1118_166_fu_800_p1() {
    sext_ln1118_166_fu_800_p1 = esl_sext<19,16>(shl_ln1118_85_fu_793_p3.read());
}

void dense_resource_0_0_1::thread_sext_ln1118_167_fu_804_p1() {
    sext_ln1118_167_fu_804_p1 = esl_sext<17,16>(shl_ln1118_85_fu_793_p3.read());
}

void dense_resource_0_0_1::thread_sext_ln1118_168_fu_566_p1() {
    sext_ln1118_168_fu_566_p1 = esl_sext<21,20>(shl_ln1118_86_fu_558_p3.read());
}

void dense_resource_0_0_1::thread_sext_ln1118_169_fu_578_p1() {
    sext_ln1118_169_fu_578_p1 = esl_sext<21,17>(shl_ln1118_87_fu_570_p3.read());
}

void dense_resource_0_0_1::thread_sext_ln1118_170_fu_882_p1() {
    sext_ln1118_170_fu_882_p1 = esl_sext<20,19>(shl_ln1118_88_fu_875_p3.read());
}

void dense_resource_0_0_1::thread_sext_ln1118_171_fu_893_p1() {
    sext_ln1118_171_fu_893_p1 = esl_sext<20,16>(shl_ln1118_89_fu_886_p3.read());
}

void dense_resource_0_0_1::thread_sext_ln1118_172_fu_924_p1() {
    sext_ln1118_172_fu_924_p1 = esl_sext<19,18>(shl_ln1118_90_fu_917_p3.read());
}

void dense_resource_0_0_1::thread_sext_ln1118_216_fu_651_p1() {
    sext_ln1118_216_fu_651_p1 = esl_sext<18,17>(tmp_fu_644_p3.read());
}

void dense_resource_0_0_1::thread_sext_ln1118_fu_164_p0() {
    sext_ln1118_fu_164_p0 = data_0_V_read.read();
}

void dense_resource_0_0_1::thread_sext_ln1118_fu_164_p1() {
    sext_ln1118_fu_164_p1 = esl_sext<21,14>(sext_ln1118_fu_164_p0.read());
}

void dense_resource_0_0_1::thread_sext_ln703_34_fu_263_p1() {
    sext_ln703_34_fu_263_p1 = esl_sext<13,12>(tmp_44_fu_253_p4.read());
}

void dense_resource_0_0_1::thread_sext_ln703_35_fu_291_p1() {
    sext_ln703_35_fu_291_p1 = esl_sext<14,13>(add_ln703_191_fu_285_p2.read());
}

void dense_resource_0_0_1::thread_sext_ln703_36_fu_944_p1() {
    sext_ln703_36_fu_944_p1 = esl_sext<13,12>(tmp_45_fu_934_p4.read());
}

void dense_resource_0_0_1::thread_sext_ln703_37_fu_960_p1() {
    sext_ln703_37_fu_960_p1 = esl_sext<14,13>(add_ln703_214_fu_954_p2.read());
}

void dense_resource_0_0_1::thread_sext_ln703_fu_840_p1() {
    sext_ln703_fu_840_p1 = esl_sext<14,8>(add_ln703_207_fu_834_p2.read());
}

void dense_resource_0_0_1::thread_sext_ln708_104_fu_232_p1() {
    sext_ln708_104_fu_232_p1 = esl_sext<14,13>(trunc_ln708_126_fu_223_p4.read());
}

void dense_resource_0_0_1::thread_sext_ln708_105_fu_671_p1() {
    sext_ln708_105_fu_671_p1 = esl_sext<14,11>(trunc_ln708_127_fu_661_p4.read());
}

void dense_resource_0_0_1::thread_sext_ln708_106_fu_687_p1() {
    sext_ln708_106_fu_687_p1 = esl_sext<14,13>(trunc_ln708_128_fu_678_p4.read());
}

void dense_resource_0_0_1::thread_sext_ln708_110_fu_347_p1() {
    sext_ln708_110_fu_347_p1 = esl_sext<14,10>(trunc_ln708_130_fu_337_p4.read());
}

void dense_resource_0_0_1::thread_sext_ln708_111_fu_360_p1() {
    sext_ln708_111_fu_360_p1 = esl_sext<14,13>(trunc_ln708_131_fu_351_p4.read());
}

void dense_resource_0_0_1::thread_sext_ln708_112_fu_726_p1() {
    sext_ln708_112_fu_726_p1 = esl_sext<14,11>(trunc_ln708_132_fu_716_p4.read());
}

void dense_resource_0_0_1::thread_sext_ln708_113_fu_757_p1() {
    sext_ln708_113_fu_757_p1 = esl_sext<14,13>(trunc_ln708_133_fu_747_p4.read());
}

void dense_resource_0_0_1::thread_sext_ln708_114_fu_382_p1() {
    sext_ln708_114_fu_382_p1 = esl_sext<14,13>(trunc_ln708_134_fu_373_p4.read());
}

void dense_resource_0_0_1::thread_sext_ln708_115_fu_459_p1() {
    sext_ln708_115_fu_459_p1 = esl_sext<14,10>(trunc_ln708_135_fu_449_p4.read());
}

void dense_resource_0_0_1::thread_sext_ln708_116_fu_513_p1() {
    sext_ln708_116_fu_513_p1 = esl_sext<14,13>(trunc_ln708_137_fu_503_p4.read());
}

void dense_resource_0_0_1::thread_sext_ln708_117_fu_527_p1() {
    sext_ln708_117_fu_527_p1 = esl_sext<14,8>(trunc_ln708_138_fu_517_p4.read());
}

void dense_resource_0_0_1::thread_sext_ln708_118_fu_789_p1() {
    sext_ln708_118_fu_789_p1 = esl_sext<14,13>(trunc_ln708_139_fu_780_p4.read());
}

void dense_resource_0_0_1::thread_sext_ln708_119_fu_824_p1() {
    sext_ln708_119_fu_824_p1 = esl_sext<14,10>(trunc_ln708_140_fu_814_p4.read());
}

void dense_resource_0_0_1::thread_sext_ln708_120_fu_616_p1() {
    sext_ln708_120_fu_616_p1 = esl_sext<14,13>(trunc_ln708_141_fu_607_p4.read());
}

void dense_resource_0_0_1::thread_sext_ln708_121_fu_871_p1() {
    sext_ln708_121_fu_871_p1 = esl_sext<14,12>(trunc_ln708_142_fu_861_p4.read());
}

void dense_resource_0_0_1::thread_sext_ln708_122_fu_913_p1() {
    sext_ln708_122_fu_913_p1 = esl_sext<14,13>(trunc_ln708_143_fu_903_p4.read());
}

void dense_resource_0_0_1::thread_sext_ln708_fu_181_p1() {
    sext_ln708_fu_181_p1 = esl_sext<14,13>(trunc_ln_fu_172_p4.read());
}

void dense_resource_0_0_1::thread_shl_ln1118_81_fu_730_p3() {
    shl_ln1118_81_fu_730_p3 = esl_concat<14,5>(data_5_V_read_6_reg_1130.read(), ap_const_lv5_0);
}

void dense_resource_0_0_1::thread_shl_ln1118_82_fu_425_p1() {
    shl_ln1118_82_fu_425_p1 = data_1_V_read.read();
}

void dense_resource_0_0_1::thread_shl_ln1118_82_fu_425_p3() {
    shl_ln1118_82_fu_425_p3 = esl_concat<14,2>(shl_ln1118_82_fu_425_p1.read(), ap_const_lv2_0);
}

void dense_resource_0_0_1::thread_shl_ln1118_83_fu_473_p1() {
    shl_ln1118_83_fu_473_p1 = data_3_V_read.read();
}

void dense_resource_0_0_1::thread_shl_ln1118_83_fu_473_p3() {
    shl_ln1118_83_fu_473_p3 = esl_concat<14,5>(shl_ln1118_83_fu_473_p1.read(), ap_const_lv5_0);
}

void dense_resource_0_0_1::thread_shl_ln1118_84_fu_485_p1() {
    shl_ln1118_84_fu_485_p1 = data_3_V_read.read();
}

void dense_resource_0_0_1::thread_shl_ln1118_84_fu_485_p3() {
    shl_ln1118_84_fu_485_p3 = esl_concat<14,3>(shl_ln1118_84_fu_485_p1.read(), ap_const_lv3_0);
}

void dense_resource_0_0_1::thread_shl_ln1118_85_fu_793_p3() {
    shl_ln1118_85_fu_793_p3 = esl_concat<14,2>(data_7_V_read_4_reg_1117.read(), ap_const_lv2_0);
}

void dense_resource_0_0_1::thread_shl_ln1118_86_fu_558_p1() {
    shl_ln1118_86_fu_558_p1 = data_1_V_read.read();
}

void dense_resource_0_0_1::thread_shl_ln1118_86_fu_558_p3() {
    shl_ln1118_86_fu_558_p3 = esl_concat<14,6>(shl_ln1118_86_fu_558_p1.read(), ap_const_lv6_0);
}

void dense_resource_0_0_1::thread_shl_ln1118_87_fu_570_p1() {
    shl_ln1118_87_fu_570_p1 = data_1_V_read.read();
}

void dense_resource_0_0_1::thread_shl_ln1118_87_fu_570_p3() {
    shl_ln1118_87_fu_570_p3 = esl_concat<14,3>(shl_ln1118_87_fu_570_p1.read(), ap_const_lv3_0);
}

void dense_resource_0_0_1::thread_shl_ln1118_88_fu_875_p3() {
    shl_ln1118_88_fu_875_p3 = esl_concat<14,5>(data_6_V_read_4_reg_1123.read(), ap_const_lv5_0);
}

void dense_resource_0_0_1::thread_shl_ln1118_89_fu_886_p3() {
    shl_ln1118_89_fu_886_p3 = esl_concat<14,2>(data_6_V_read_4_reg_1123.read(), ap_const_lv2_0);
}

void dense_resource_0_0_1::thread_shl_ln1118_90_fu_917_p3() {
    shl_ln1118_90_fu_917_p3 = esl_concat<14,4>(data_7_V_read_4_reg_1117.read(), ap_const_lv4_0);
}

void dense_resource_0_0_1::thread_shl_ln_fu_319_p1() {
    shl_ln_fu_319_p1 = data_2_V_read.read();
}

void dense_resource_0_0_1::thread_shl_ln_fu_319_p3() {
    shl_ln_fu_319_p3 = esl_concat<14,2>(shl_ln_fu_319_p1.read(), ap_const_lv2_0);
}

void dense_resource_0_0_1::thread_sub_ln1118_69_fu_741_p2() {
    sub_ln1118_69_fu_741_p2 = (!sext_ln1118_161_fu_737_p1.read().is_01() || !sext_ln1118_156_fu_675_p1.read().is_01())? sc_lv<20>(): (sc_bigint<20>(sext_ln1118_161_fu_737_p1.read()) - sc_bigint<20>(sext_ln1118_156_fu_675_p1.read()));
}

void dense_resource_0_0_1::thread_sub_ln1118_70_fu_437_p2() {
    sub_ln1118_70_fu_437_p2 = (!ap_const_lv17_0.is_01() || !sext_ln1118_162_fu_433_p1.read().is_01())? sc_lv<17>(): (sc_biguint<17>(ap_const_lv17_0) - sc_bigint<17>(sext_ln1118_162_fu_433_p1.read()));
}

void dense_resource_0_0_1::thread_sub_ln1118_71_fu_443_p2() {
    sub_ln1118_71_fu_443_p2 = (!sub_ln1118_70_fu_437_p2.read().is_01() || !sext_ln1118_150_fu_189_p1.read().is_01())? sc_lv<17>(): (sc_biguint<17>(sub_ln1118_70_fu_437_p2.read()) - sc_bigint<17>(sext_ln1118_150_fu_189_p1.read()));
}

void dense_resource_0_0_1::thread_sub_ln1118_72_fu_497_p2() {
    sub_ln1118_72_fu_497_p2 = (!sext_ln1118_164_fu_481_p1.read().is_01() || !sext_ln1118_165_fu_493_p1.read().is_01())? sc_lv<20>(): (sc_bigint<20>(sext_ln1118_164_fu_481_p1.read()) - sc_bigint<20>(sext_ln1118_165_fu_493_p1.read()));
}

void dense_resource_0_0_1::thread_sub_ln1118_73_fu_808_p2() {
    sub_ln1118_73_fu_808_p2 = (!ap_const_lv17_0.is_01() || !sext_ln1118_167_fu_804_p1.read().is_01())? sc_lv<17>(): (sc_biguint<17>(ap_const_lv17_0) - sc_bigint<17>(sext_ln1118_167_fu_804_p1.read()));
}

void dense_resource_0_0_1::thread_sub_ln1118_74_fu_897_p2() {
    sub_ln1118_74_fu_897_p2 = (!sext_ln1118_170_fu_882_p1.read().is_01() || !sext_ln1118_171_fu_893_p1.read().is_01())? sc_lv<20>(): (sc_bigint<20>(sext_ln1118_170_fu_882_p1.read()) - sc_bigint<20>(sext_ln1118_171_fu_893_p1.read()));
}

void dense_resource_0_0_1::thread_sub_ln1118_75_fu_928_p2() {
    sub_ln1118_75_fu_928_p2 = (!sext_ln1118_166_fu_800_p1.read().is_01() || !sext_ln1118_172_fu_924_p1.read().is_01())? sc_lv<19>(): (sc_bigint<19>(sext_ln1118_166_fu_800_p1.read()) - sc_bigint<19>(sext_ln1118_172_fu_924_p1.read()));
}

void dense_resource_0_0_1::thread_sub_ln1118_99_fu_655_p2() {
    sub_ln1118_99_fu_655_p2 = (!sext_ln1118_155_fu_641_p1.read().is_01() || !sext_ln1118_216_fu_651_p1.read().is_01())? sc_lv<18>(): (sc_bigint<18>(sext_ln1118_155_fu_641_p1.read()) - sc_bigint<18>(sext_ln1118_216_fu_651_p1.read()));
}

void dense_resource_0_0_1::thread_sub_ln1118_fu_710_p2() {
    sub_ln1118_fu_710_p2 = (!sext_ln1118_216_fu_651_p1.read().is_01() || !sext_ln1118_155_fu_641_p1.read().is_01())? sc_lv<18>(): (sc_bigint<18>(sext_ln1118_216_fu_651_p1.read()) - sc_bigint<18>(sext_ln1118_155_fu_641_p1.read()));
}

void dense_resource_0_0_1::thread_tmp_44_fu_253_p1() {
    tmp_44_fu_253_p1 = data_7_V_read.read();
}

void dense_resource_0_0_1::thread_tmp_44_fu_253_p4() {
    tmp_44_fu_253_p4 = tmp_44_fu_253_p1.read().range(13, 2);
}

void dense_resource_0_0_1::thread_tmp_45_fu_934_p4() {
    tmp_45_fu_934_p4 = sub_ln1118_75_fu_928_p2.read().range(18, 7);
}

void dense_resource_0_0_1::thread_tmp_fu_644_p3() {
    tmp_fu_644_p3 = esl_concat<14,3>(data_4_V_read_7_reg_1136.read(), ap_const_lv3_0);
}

void dense_resource_0_0_1::thread_trunc_ln708_126_fu_223_p4() {
    trunc_ln708_126_fu_223_p4 = mul_ln1118_54_fu_1026_p2.read().range(19, 7);
}

void dense_resource_0_0_1::thread_trunc_ln708_127_fu_661_p4() {
    trunc_ln708_127_fu_661_p4 = sub_ln1118_99_fu_655_p2.read().range(17, 7);
}

void dense_resource_0_0_1::thread_trunc_ln708_128_fu_678_p4() {
    trunc_ln708_128_fu_678_p4 = mul_ln1118_56_fu_1103_p2.read().range(19, 7);
}

void dense_resource_0_0_1::thread_trunc_ln708_130_fu_337_p4() {
    trunc_ln708_130_fu_337_p4 = add_ln1118_fu_331_p2.read().range(16, 7);
}

void dense_resource_0_0_1::thread_trunc_ln708_131_fu_351_p4() {
    trunc_ln708_131_fu_351_p4 = mul_ln1118_60_fu_1054_p2.read().range(19, 7);
}

void dense_resource_0_0_1::thread_trunc_ln708_132_fu_716_p4() {
    trunc_ln708_132_fu_716_p4 = sub_ln1118_fu_710_p2.read().range(17, 7);
}

void dense_resource_0_0_1::thread_trunc_ln708_133_fu_747_p4() {
    trunc_ln708_133_fu_747_p4 = sub_ln1118_69_fu_741_p2.read().range(19, 7);
}

void dense_resource_0_0_1::thread_trunc_ln708_134_fu_373_p4() {
    trunc_ln708_134_fu_373_p4 = mul_ln1118_62_fu_1068_p2.read().range(19, 7);
}

void dense_resource_0_0_1::thread_trunc_ln708_135_fu_449_p4() {
    trunc_ln708_135_fu_449_p4 = sub_ln1118_71_fu_443_p2.read().range(16, 7);
}

void dense_resource_0_0_1::thread_trunc_ln708_136_fu_463_p1() {
    trunc_ln708_136_fu_463_p1 = data_2_V_read.read();
}

void dense_resource_0_0_1::thread_trunc_ln708_137_fu_503_p4() {
    trunc_ln708_137_fu_503_p4 = sub_ln1118_72_fu_497_p2.read().range(19, 7);
}

void dense_resource_0_0_1::thread_trunc_ln708_138_fu_517_p1() {
    trunc_ln708_138_fu_517_p1 = data_5_V_read.read();
}

void dense_resource_0_0_1::thread_trunc_ln708_138_fu_517_p4() {
    trunc_ln708_138_fu_517_p4 = trunc_ln708_138_fu_517_p1.read().range(13, 6);
}

void dense_resource_0_0_1::thread_trunc_ln708_139_fu_780_p4() {
    trunc_ln708_139_fu_780_p4 = mul_ln1118_64_fu_1110_p2.read().range(19, 7);
}

void dense_resource_0_0_1::thread_trunc_ln708_140_fu_814_p4() {
    trunc_ln708_140_fu_814_p4 = sub_ln1118_73_fu_808_p2.read().range(16, 7);
}

void dense_resource_0_0_1::thread_trunc_ln708_141_fu_607_p4() {
    trunc_ln708_141_fu_607_p4 = mul_ln1118_67_fu_1096_p2.read().range(19, 7);
}

void dense_resource_0_0_1::thread_trunc_ln708_142_fu_861_p4() {
    trunc_ln708_142_fu_861_p4 = mul_ln1118_68_fu_855_p2.read().range(18, 7);
}

void dense_resource_0_0_1::thread_trunc_ln708_143_fu_903_p4() {
    trunc_ln708_143_fu_903_p4 = sub_ln1118_74_fu_897_p2.read().range(19, 7);
}

void dense_resource_0_0_1::thread_trunc_ln708_64_fu_193_p4() {
    trunc_ln708_64_fu_193_p4 = mul_ln1118_52_fu_1012_p2.read().range(20, 7);
}

void dense_resource_0_0_1::thread_trunc_ln708_65_fu_210_p4() {
    trunc_ln708_65_fu_210_p4 = mul_ln1118_53_fu_1019_p2.read().range(20, 7);
}

void dense_resource_0_0_1::thread_trunc_ln708_69_fu_240_p4() {
    trunc_ln708_69_fu_240_p4 = mul_ln1118_57_fu_1033_p2.read().range(20, 7);
}

void dense_resource_0_0_1::thread_trunc_ln708_71_fu_301_p4() {
    trunc_ln708_71_fu_301_p4 = mul_ln1118_58_fu_1040_p2.read().range(20, 7);
}

void dense_resource_0_0_1::thread_trunc_ln708_72_fu_310_p4() {
    trunc_ln708_72_fu_310_p4 = mul_ln1118_59_fu_1047_p2.read().range(20, 7);
}

void dense_resource_0_0_1::thread_trunc_ln708_77_fu_364_p4() {
    trunc_ln708_77_fu_364_p4 = mul_ln1118_61_fu_1061_p2.read().range(20, 7);
}

void dense_resource_0_0_1::thread_trunc_ln708_79_fu_416_p4() {
    trunc_ln708_79_fu_416_p4 = mul_ln1118_63_fu_1075_p2.read().range(20, 7);
}

void dense_resource_0_0_1::thread_trunc_ln708_87_fu_549_p4() {
    trunc_ln708_87_fu_549_p4 = mul_ln1118_65_fu_1082_p2.read().range(20, 7);
}

void dense_resource_0_0_1::thread_trunc_ln708_88_fu_588_p4() {
    trunc_ln708_88_fu_588_p4 = add_ln1118_13_fu_582_p2.read().range(20, 7);
}

void dense_resource_0_0_1::thread_trunc_ln708_89_fu_598_p4() {
    trunc_ln708_89_fu_598_p4 = mul_ln1118_66_fu_1089_p2.read().range(20, 7);
}

void dense_resource_0_0_1::thread_trunc_ln_fu_172_p4() {
    trunc_ln_fu_172_p4 = mul_ln1118_fu_1005_p2.read().range(19, 7);
}

}

