// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dense_mult_3lyr.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dense_mult_3lyr::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dense_mult_3lyr::ap_const_logic_0 = sc_dt::Log_0;
const bool dense_mult_3lyr::ap_const_boolean_1 = true;
const bool dense_mult_3lyr::ap_const_boolean_0 = false;
const sc_lv<32> dense_mult_3lyr::ap_const_lv32_7 = "111";
const sc_lv<32> dense_mult_3lyr::ap_const_lv32_14 = "10100";
const sc_lv<4> dense_mult_3lyr::ap_const_lv4_0 = "0000";
const sc_lv<32> dense_mult_3lyr::ap_const_lv32_12 = "10010";
const sc_lv<19> dense_mult_3lyr::ap_const_lv19_0 = "0000000000000000000";
const sc_lv<2> dense_mult_3lyr::ap_const_lv2_0 = "00";
const sc_lv<5> dense_mult_3lyr::ap_const_lv5_0 = "00000";
const sc_lv<1> dense_mult_3lyr::ap_const_lv1_0 = "0";
const sc_lv<32> dense_mult_3lyr::ap_const_lv32_13 = "10011";
const sc_lv<32> dense_mult_3lyr::ap_const_lv32_6 = "110";
const sc_lv<32> dense_mult_3lyr::ap_const_lv32_D = "1101";
const sc_lv<19> dense_mult_3lyr::ap_const_lv19_7FFF3 = "1111111111111110011";
const sc_lv<17> dense_mult_3lyr::ap_const_lv17_0 = "00000000000000000";
const sc_lv<32> dense_mult_3lyr::ap_const_lv32_10 = "10000";
const sc_lv<3> dense_mult_3lyr::ap_const_lv3_0 = "000";
const sc_lv<32> dense_mult_3lyr::ap_const_lv32_11 = "10001";
const sc_lv<18> dense_mult_3lyr::ap_const_lv18_0 = "000000000000000000";
const sc_lv<32> dense_mult_3lyr::ap_const_lv32_1 = "1";
const sc_lv<14> dense_mult_3lyr::ap_const_lv14_58 = "1011000";
const sc_lv<20> dense_mult_3lyr::ap_const_lv20_0 = "00000000000000000000";
const sc_lv<14> dense_mult_3lyr::ap_const_lv14_70 = "1110000";
const sc_lv<8> dense_mult_3lyr::ap_const_lv8_D5 = "11010101";
const sc_lv<21> dense_mult_3lyr::ap_const_lv21_2E = "101110";
const sc_lv<21> dense_mult_3lyr::ap_const_lv21_1FFFCD = "111111111111111001101";
const sc_lv<21> dense_mult_3lyr::ap_const_lv21_1FFFDD = "111111111111111011101";
const sc_lv<21> dense_mult_3lyr::ap_const_lv21_1FFFDA = "111111111111111011010";
const sc_lv<21> dense_mult_3lyr::ap_const_lv21_23 = "100011";
const sc_lv<20> dense_mult_3lyr::ap_const_lv20_FFFED = "11111111111111101101";
const sc_lv<21> dense_mult_3lyr::ap_const_lv21_1FFFD2 = "111111111111111010010";
const sc_lv<20> dense_mult_3lyr::ap_const_lv20_16 = "10110";
const sc_lv<21> dense_mult_3lyr::ap_const_lv21_1FFFA7 = "111111111111110100111";
const sc_lv<21> dense_mult_3lyr::ap_const_lv21_5D = "1011101";
const sc_lv<21> dense_mult_3lyr::ap_const_lv21_27 = "100111";

dense_mult_3lyr::dense_mult_3lyr(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_dense_resource_1_0_fu_158 = new dense_resource_1_0("grp_dense_resource_1_0_fu_158");
    grp_dense_resource_1_0_fu_158->ap_clk(ap_clk);
    grp_dense_resource_1_0_fu_158->ap_rst(ap_rst);
    grp_dense_resource_1_0_fu_158->data_0_V_read(data0_0_V_reg_1163);
    grp_dense_resource_1_0_fu_158->data_1_V_read(data0_1_V_reg_1168);
    grp_dense_resource_1_0_fu_158->data_2_V_read(data0_2_V_reg_1173);
    grp_dense_resource_1_0_fu_158->data_3_V_read(data0_3_V_reg_1178);
    grp_dense_resource_1_0_fu_158->data_4_V_read(data0_4_V_reg_1183);
    grp_dense_resource_1_0_fu_158->data_5_V_read(data0_5_V_reg_1188);
    grp_dense_resource_1_0_fu_158->data_6_V_read(data0_6_V_reg_1193);
    grp_dense_resource_1_0_fu_158->data_7_V_read(data0_7_V_reg_1198);
    grp_dense_resource_1_0_fu_158->ap_return_0(grp_dense_resource_1_0_fu_158_ap_return_0);
    grp_dense_resource_1_0_fu_158->ap_return_1(grp_dense_resource_1_0_fu_158_ap_return_1);
    grp_dense_resource_1_0_fu_158->ap_return_2(grp_dense_resource_1_0_fu_158_ap_return_2);
    grp_dense_resource_1_0_fu_158->ap_return_3(grp_dense_resource_1_0_fu_158_ap_return_3);
    grp_dense_resource_1_0_fu_158->ap_return_4(grp_dense_resource_1_0_fu_158_ap_return_4);
    grp_dense_resource_1_0_fu_158->ap_return_5(grp_dense_resource_1_0_fu_158_ap_return_5);
    grp_dense_resource_1_0_fu_158->ap_return_6(grp_dense_resource_1_0_fu_158_ap_return_6);
    grp_dense_resource_1_0_fu_158->ap_return_7(grp_dense_resource_1_0_fu_158_ap_return_7);
    grp_dense_resource_1_0_fu_158->ap_ce(grp_dense_resource_1_0_fu_158_ap_ce);
    grp_dense_resource_0_0_2_fu_170 = new dense_resource_0_0_2("grp_dense_resource_0_0_2_fu_170");
    grp_dense_resource_0_0_2_fu_170->ap_clk(ap_clk);
    grp_dense_resource_0_0_2_fu_170->ap_rst(ap_rst);
    grp_dense_resource_0_0_2_fu_170->data_0_V_read(data_0_V_read_int_reg);
    grp_dense_resource_0_0_2_fu_170->data_1_V_read(data_1_V_read_int_reg);
    grp_dense_resource_0_0_2_fu_170->data_2_V_read(data_2_V_read_int_reg);
    grp_dense_resource_0_0_2_fu_170->data_3_V_read(data_3_V_read_int_reg);
    grp_dense_resource_0_0_2_fu_170->data_4_V_read(data_4_V_read_int_reg);
    grp_dense_resource_0_0_2_fu_170->data_5_V_read(data_5_V_read_int_reg);
    grp_dense_resource_0_0_2_fu_170->data_6_V_read(data_6_V_read_int_reg);
    grp_dense_resource_0_0_2_fu_170->ap_return_0(grp_dense_resource_0_0_2_fu_170_ap_return_0);
    grp_dense_resource_0_0_2_fu_170->ap_return_1(grp_dense_resource_0_0_2_fu_170_ap_return_1);
    grp_dense_resource_0_0_2_fu_170->ap_return_2(grp_dense_resource_0_0_2_fu_170_ap_return_2);
    grp_dense_resource_0_0_2_fu_170->ap_return_3(grp_dense_resource_0_0_2_fu_170_ap_return_3);
    grp_dense_resource_0_0_2_fu_170->ap_return_4(grp_dense_resource_0_0_2_fu_170_ap_return_4);
    grp_dense_resource_0_0_2_fu_170->ap_return_5(grp_dense_resource_0_0_2_fu_170_ap_return_5);
    grp_dense_resource_0_0_2_fu_170->ap_return_6(grp_dense_resource_0_0_2_fu_170_ap_return_6);
    grp_dense_resource_0_0_2_fu_170->ap_return_7(grp_dense_resource_0_0_2_fu_170_ap_return_7);
    grp_dense_resource_0_0_2_fu_170->ap_ce(grp_dense_resource_0_0_2_fu_170_ap_ce);
    call_ret2_relu_fu_188 = new relu("call_ret2_relu_fu_188");
    call_ret2_relu_fu_188->ap_ready(call_ret2_relu_fu_188_ap_ready);
    call_ret2_relu_fu_188->data_0_V_read(data0_logits_0_V_reg_1123);
    call_ret2_relu_fu_188->data_1_V_read(data0_logits_1_V_reg_1128);
    call_ret2_relu_fu_188->data_2_V_read(data0_logits_2_V_reg_1133);
    call_ret2_relu_fu_188->data_3_V_read(data0_logits_3_V_reg_1138);
    call_ret2_relu_fu_188->data_4_V_read(data0_logits_4_V_reg_1143);
    call_ret2_relu_fu_188->data_5_V_read(data0_logits_5_V_reg_1148);
    call_ret2_relu_fu_188->data_6_V_read(data0_logits_6_V_reg_1153);
    call_ret2_relu_fu_188->data_7_V_read(data0_logits_7_V_reg_1158);
    call_ret2_relu_fu_188->ap_return_0(call_ret2_relu_fu_188_ap_return_0);
    call_ret2_relu_fu_188->ap_return_1(call_ret2_relu_fu_188_ap_return_1);
    call_ret2_relu_fu_188->ap_return_2(call_ret2_relu_fu_188_ap_return_2);
    call_ret2_relu_fu_188->ap_return_3(call_ret2_relu_fu_188_ap_return_3);
    call_ret2_relu_fu_188->ap_return_4(call_ret2_relu_fu_188_ap_return_4);
    call_ret2_relu_fu_188->ap_return_5(call_ret2_relu_fu_188_ap_return_5);
    call_ret2_relu_fu_188->ap_return_6(call_ret2_relu_fu_188_ap_return_6);
    call_ret2_relu_fu_188->ap_return_7(call_ret2_relu_fu_188_ap_return_7);
    call_ret_relu_fu_200 = new relu("call_ret_relu_fu_200");
    call_ret_relu_fu_200->ap_ready(call_ret_relu_fu_200_ap_ready);
    call_ret_relu_fu_200->data_0_V_read(data1_logits_0_V_reg_1203);
    call_ret_relu_fu_200->data_1_V_read(data1_logits_1_V_reg_1208);
    call_ret_relu_fu_200->data_2_V_read(data1_logits_2_V_reg_1213);
    call_ret_relu_fu_200->data_3_V_read(data1_logits_3_V_reg_1218);
    call_ret_relu_fu_200->data_4_V_read(data1_logits_4_V_reg_1223);
    call_ret_relu_fu_200->data_5_V_read(data1_logits_5_V_reg_1228);
    call_ret_relu_fu_200->data_6_V_read(data1_logits_6_V_reg_1233);
    call_ret_relu_fu_200->data_7_V_read(data1_logits_7_V_reg_1238);
    call_ret_relu_fu_200->ap_return_0(call_ret_relu_fu_200_ap_return_0);
    call_ret_relu_fu_200->ap_return_1(call_ret_relu_fu_200_ap_return_1);
    call_ret_relu_fu_200->ap_return_2(call_ret_relu_fu_200_ap_return_2);
    call_ret_relu_fu_200->ap_return_3(call_ret_relu_fu_200_ap_return_3);
    call_ret_relu_fu_200->ap_return_4(call_ret_relu_fu_200_ap_return_4);
    call_ret_relu_fu_200->ap_return_5(call_ret_relu_fu_200_ap_return_5);
    call_ret_relu_fu_200->ap_return_6(call_ret_relu_fu_200_ap_return_6);
    call_ret_relu_fu_200->ap_return_7(call_ret_relu_fu_200_ap_return_7);
    example_mul_mul_1ncg_U1591 = new example_mul_mul_1ncg<1,1,14,7,21>("example_mul_mul_1ncg_U1591");
    example_mul_mul_1ncg_U1591->din0(call_ret_relu_fu_200_ap_return_0);
    example_mul_mul_1ncg_U1591->din1(mul_ln1118_fu_1046_p1);
    example_mul_mul_1ncg_U1591->dout(mul_ln1118_fu_1046_p2);
    example_mul_mul_1ocq_U1592 = new example_mul_mul_1ocq<1,1,14,7,21>("example_mul_mul_1ocq_U1592");
    example_mul_mul_1ocq_U1592->din0(mul_ln1118_127_fu_1053_p0);
    example_mul_mul_1ocq_U1592->din1(mul_ln1118_127_fu_1053_p1);
    example_mul_mul_1ocq_U1592->dout(mul_ln1118_127_fu_1053_p2);
    example_mul_mul_1ocq_U1593 = new example_mul_mul_1ocq<1,1,14,7,21>("example_mul_mul_1ocq_U1593");
    example_mul_mul_1ocq_U1593->din0(mul_ln1118_128_fu_1060_p0);
    example_mul_mul_1ocq_U1593->din1(mul_ln1118_128_fu_1060_p1);
    example_mul_mul_1ocq_U1593->dout(mul_ln1118_128_fu_1060_p2);
    example_mul_mul_1ocq_U1594 = new example_mul_mul_1ocq<1,1,14,7,21>("example_mul_mul_1ocq_U1594");
    example_mul_mul_1ocq_U1594->din0(call_ret_relu_fu_200_ap_return_2);
    example_mul_mul_1ocq_U1594->din1(mul_ln1118_129_fu_1067_p1);
    example_mul_mul_1ocq_U1594->dout(mul_ln1118_129_fu_1067_p2);
    example_mul_mul_1ncg_U1595 = new example_mul_mul_1ncg<1,1,14,7,21>("example_mul_mul_1ncg_U1595");
    example_mul_mul_1ncg_U1595->din0(call_ret_relu_fu_200_ap_return_3);
    example_mul_mul_1ncg_U1595->din1(mul_ln1118_130_fu_1074_p1);
    example_mul_mul_1ncg_U1595->dout(mul_ln1118_130_fu_1074_p2);
    example_mul_mul_1rcU_U1596 = new example_mul_mul_1rcU<1,1,14,6,20>("example_mul_mul_1rcU_U1596");
    example_mul_mul_1rcU_U1596->din0(call_ret_relu_fu_200_ap_return_0);
    example_mul_mul_1rcU_U1596->din1(mul_ln1118_133_fu_1081_p1);
    example_mul_mul_1rcU_U1596->dout(mul_ln1118_133_fu_1081_p2);
    example_mul_mul_1ocq_U1597 = new example_mul_mul_1ocq<1,1,14,7,21>("example_mul_mul_1ocq_U1597");
    example_mul_mul_1ocq_U1597->din0(mul_ln1118_134_fu_1088_p0);
    example_mul_mul_1ocq_U1597->din1(mul_ln1118_134_fu_1088_p1);
    example_mul_mul_1ocq_U1597->dout(mul_ln1118_134_fu_1088_p2);
    example_mul_mul_1tde_U1598 = new example_mul_mul_1tde<1,1,14,6,20>("example_mul_mul_1tde_U1598");
    example_mul_mul_1tde_U1598->din0(call_ret_relu_fu_200_ap_return_3);
    example_mul_mul_1tde_U1598->din1(mul_ln1118_135_fu_1095_p1);
    example_mul_mul_1tde_U1598->dout(mul_ln1118_135_fu_1095_p2);
    example_mul_mul_1sc4_U1599 = new example_mul_mul_1sc4<1,1,14,8,21>("example_mul_mul_1sc4_U1599");
    example_mul_mul_1sc4_U1599->din0(mul_ln1118_136_fu_1102_p0);
    example_mul_mul_1sc4_U1599->din1(mul_ln1118_136_fu_1102_p1);
    example_mul_mul_1sc4_U1599->dout(mul_ln1118_136_fu_1102_p2);
    example_mul_mul_1wdI_U1600 = new example_mul_mul_1wdI<1,1,14,8,21>("example_mul_mul_1wdI_U1600");
    example_mul_mul_1wdI_U1600->din0(call_ret_relu_fu_200_ap_return_6);
    example_mul_mul_1wdI_U1600->din1(mul_ln1118_137_fu_1109_p1);
    example_mul_mul_1wdI_U1600->dout(mul_ln1118_137_fu_1109_p2);
    example_mul_mul_1ncg_U1601 = new example_mul_mul_1ncg<1,1,14,7,21>("example_mul_mul_1ncg_U1601");
    example_mul_mul_1ncg_U1601->din0(data1_7_V_reg_1243);
    example_mul_mul_1ncg_U1601->din1(mul_ln1118_132_fu_1116_p1);
    example_mul_mul_1ncg_U1601->dout(mul_ln1118_132_fu_1116_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln703_292_fu_545_p2);
    sensitive << ( sext_ln1118_254_fu_472_p1 );
    sensitive << ( sext_ln1118_253_fu_410_p1 );

    SC_METHOD(thread_add_ln703_293_fu_555_p2);
    sensitive << ( add_ln703_fu_539_p2 );
    sensitive << ( sext_ln703_40_fu_551_p1 );

    SC_METHOD(thread_add_ln703_294_fu_561_p2);
    sensitive << ( sext_ln708_fu_535_p1 );
    sensitive << ( trunc_ln708_197_fu_480_p4 );

    SC_METHOD(thread_add_ln703_295_fu_943_p2);
    sensitive << ( sext_ln708_123_fu_939_p1 );

    SC_METHOD(thread_add_ln703_296_fu_949_p2);
    sensitive << ( add_ln703_294_reg_1255 );
    sensitive << ( add_ln703_295_fu_943_p2 );

    SC_METHOD(thread_add_ln703_297_fu_954_p2);
    sensitive << ( add_ln703_293_reg_1250 );
    sensitive << ( add_ln703_296_fu_949_p2 );

    SC_METHOD(thread_add_ln703_298_fu_711_p2);
    sensitive << ( sext_ln708_125_fu_621_p1 );
    sensitive << ( sext_ln708_124_fu_607_p1 );

    SC_METHOD(thread_add_ln703_299_fu_717_p2);
    sensitive << ( trunc_ln708_203_fu_634_p4 );
    sensitive << ( trunc_ln708_202_fu_625_p4 );

    SC_METHOD(thread_add_ln703_300_fu_723_p2);
    sensitive << ( add_ln703_298_fu_711_p2 );
    sensitive << ( add_ln703_299_fu_717_p2 );

    SC_METHOD(thread_add_ln703_301_fu_729_p2);
    sensitive << ( sext_ln1118_255_fu_707_p1 );
    sensitive << ( sext_ln708_126_fu_659_p1 );

    SC_METHOD(thread_add_ln703_302_fu_974_p2);
    sensitive << ( sext_ln1118_248_fu_959_p1 );

    SC_METHOD(thread_add_ln703_303_fu_984_p2);
    sensitive << ( trunc_ln708_205_fu_962_p4 );
    sensitive << ( sext_ln703_fu_980_p1 );

    SC_METHOD(thread_add_ln703_304_fu_990_p2);
    sensitive << ( sext_ln703_41_fu_971_p1 );
    sensitive << ( add_ln703_303_fu_984_p2 );

    SC_METHOD(thread_add_ln703_305_fu_996_p2);
    sensitive << ( add_ln703_300_reg_1265 );
    sensitive << ( add_ln703_304_fu_990_p2 );

    SC_METHOD(thread_add_ln703_306_fu_876_p2);
    sensitive << ( trunc_ln708_207_fu_748_p4 );
    sensitive << ( sext_ln708_127_fu_744_p1 );

    SC_METHOD(thread_add_ln703_307_fu_1007_p2);
    sensitive << ( sext_ln708_129_fu_1004_p1 );
    sensitive << ( sext_ln708_128_fu_1001_p1 );

    SC_METHOD(thread_add_ln703_308_fu_1013_p2);
    sensitive << ( add_ln703_306_reg_1285 );
    sensitive << ( add_ln703_307_fu_1007_p2 );

    SC_METHOD(thread_add_ln703_309_fu_882_p2);
    sensitive << ( trunc_ln708_211_fu_844_p4 );
    sensitive << ( sext_ln708_130_fu_840_p1 );

    SC_METHOD(thread_add_ln703_310_fu_888_p2);
    sensitive << ( sext_ln708_131_fu_872_p1 );

    SC_METHOD(thread_add_ln703_311_fu_894_p2);
    sensitive << ( trunc_ln708_212_fu_853_p4 );
    sensitive << ( add_ln703_310_fu_888_p2 );

    SC_METHOD(thread_add_ln703_312_fu_1018_p2);
    sensitive << ( add_ln703_309_reg_1290 );
    sensitive << ( add_ln703_311_reg_1295 );

    SC_METHOD(thread_add_ln703_313_fu_1022_p2);
    sensitive << ( add_ln703_308_fu_1013_p2 );
    sensitive << ( add_ln703_312_fu_1018_p2 );

    SC_METHOD(thread_add_ln703_fu_539_p2);
    sensitive << ( trunc_ln708_s_fu_361_p4 );
    sensitive << ( trunc_ln_fu_348_p4 );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_11001_ignoreCallOp15);

    SC_METHOD(thread_ap_block_pp0_stage0_11001_ignoreCallOp34);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0_ignore_call25);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0_ignore_call7);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1_ignore_call25);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1_ignore_call7);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2_ignore_call25);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2_ignore_call7);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3_ignore_call25);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3_ignore_call7);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter4_ignore_call25);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter4_ignore_call7);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter5);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter5_ignore_call25);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter5_ignore_call7);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter6);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter6_ignore_call25);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter6_ignore_call7);

    SC_METHOD(thread_ap_return_0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( add_ln703_297_fu_954_p2 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( add_ln703_305_fu_996_p2 );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( add_ln703_313_fu_1022_p2 );

    SC_METHOD(thread_grp_dense_resource_0_0_2_fu_170_ap_ce);
    sensitive << ( ap_block_pp0_stage0_11001_ignoreCallOp15 );

    SC_METHOD(thread_grp_dense_resource_1_0_fu_158_ap_ce);
    sensitive << ( ap_block_pp0_stage0_11001_ignoreCallOp34 );

    SC_METHOD(thread_mul_ln1118_127_fu_1053_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1118_228_fu_357_p1 );

    SC_METHOD(thread_mul_ln1118_127_fu_1053_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_128_fu_1060_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1118_238_fu_476_p1 );

    SC_METHOD(thread_mul_ln1118_128_fu_1060_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_129_fu_1067_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_130_fu_1074_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_131_fu_643_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1118_235_fu_422_p0 );

    SC_METHOD(thread_mul_ln1118_131_fu_643_p2);
    sensitive << ( mul_ln1118_131_fu_643_p0 );

    SC_METHOD(thread_mul_ln1118_132_fu_1116_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_133_fu_1081_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_134_fu_1088_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1118_228_fu_357_p1 );

    SC_METHOD(thread_mul_ln1118_134_fu_1088_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_135_fu_1095_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_136_fu_1102_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1118_238_fu_476_p1 );

    SC_METHOD(thread_mul_ln1118_136_fu_1102_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_137_fu_1109_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_fu_1046_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_sext_ln1118_228_fu_357_p0);
    sensitive << ( call_ret_relu_fu_200_ap_return_1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_sext_ln1118_228_fu_357_p1);
    sensitive << ( sext_ln1118_228_fu_357_p0 );

    SC_METHOD(thread_sext_ln1118_230_fu_374_p0);
    sensitive << ( call_ret_relu_fu_200_ap_return_2 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_sext_ln1118_230_fu_374_p1);
    sensitive << ( sext_ln1118_230_fu_374_p0 );

    SC_METHOD(thread_sext_ln1118_231_fu_378_p0);
    sensitive << ( call_ret_relu_fu_200_ap_return_2 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_sext_ln1118_231_fu_378_p1);
    sensitive << ( sext_ln1118_231_fu_378_p0 );

    SC_METHOD(thread_sext_ln1118_232_fu_390_p1);
    sensitive << ( tmp_fu_382_p3 );

    SC_METHOD(thread_sext_ln1118_235_fu_422_p0);
    sensitive << ( call_ret_relu_fu_200_ap_return_4 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_sext_ln1118_236_fu_434_p1);
    sensitive << ( shl_ln_fu_426_p3 );

    SC_METHOD(thread_sext_ln1118_237_fu_452_p1);
    sensitive << ( shl_ln1118_s_fu_444_p3 );

    SC_METHOD(thread_sext_ln1118_238_fu_476_p0);
    sensitive << ( call_ret_relu_fu_200_ap_return_5 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_sext_ln1118_238_fu_476_p1);
    sensitive << ( sext_ln1118_238_fu_476_p0 );

    SC_METHOD(thread_sext_ln1118_240_fu_493_p0);
    sensitive << ( call_ret_relu_fu_200_ap_return_6 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_sext_ln1118_240_fu_493_p1);
    sensitive << ( sext_ln1118_240_fu_493_p0 );

    SC_METHOD(thread_sext_ln1118_241_fu_497_p0);
    sensitive << ( call_ret_relu_fu_200_ap_return_6 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_sext_ln1118_241_fu_497_p1);
    sensitive << ( sext_ln1118_241_fu_497_p0 );

    SC_METHOD(thread_sext_ln1118_242_fu_509_p1);
    sensitive << ( shl_ln1118_107_fu_501_p3 );

    SC_METHOD(thread_sext_ln1118_244_fu_903_p1);
    sensitive << ( data1_7_V_reg_1243 );

    SC_METHOD(thread_sext_ln1118_245_fu_913_p1);
    sensitive << ( shl_ln1118_108_fu_906_p3 );

    SC_METHOD(thread_sext_ln1118_246_fu_575_p1);
    sensitive << ( shl_ln1118_109_fu_567_p3 );

    SC_METHOD(thread_sext_ln1118_247_fu_587_p1);
    sensitive << ( shl_ln1118_110_fu_579_p3 );

    SC_METHOD(thread_sext_ln1118_248_fu_959_p1);
    sensitive << ( trunc_ln708_204_reg_1260 );

    SC_METHOD(thread_sext_ln1118_249_fu_681_p1);
    sensitive << ( shl_ln1118_111_fu_673_p3 );

    SC_METHOD(thread_sext_ln1118_250_fu_765_p1);
    sensitive << ( tmp_s_fu_757_p3 );

    SC_METHOD(thread_sext_ln1118_251_fu_802_p1);
    sensitive << ( shl_ln1118_112_fu_794_p3 );

    SC_METHOD(thread_sext_ln1118_252_fu_820_p1);
    sensitive << ( shl_ln1118_113_fu_812_p3 );

    SC_METHOD(thread_sext_ln1118_253_fu_410_p1);
    sensitive << ( tmp_47_fu_400_p4 );

    SC_METHOD(thread_sext_ln1118_254_fu_472_p1);
    sensitive << ( tmp_48_fu_462_p4 );

    SC_METHOD(thread_sext_ln1118_255_fu_707_p1);
    sensitive << ( tmp_50_fu_697_p4 );

    SC_METHOD(thread_sext_ln703_40_fu_551_p1);
    sensitive << ( add_ln703_292_fu_545_p2 );

    SC_METHOD(thread_sext_ln703_41_fu_971_p1);
    sensitive << ( add_ln703_301_reg_1270 );

    SC_METHOD(thread_sext_ln703_fu_980_p1);
    sensitive << ( add_ln703_302_fu_974_p2 );

    SC_METHOD(thread_sext_ln708_123_fu_939_p1);
    sensitive << ( trunc_ln708_199_fu_929_p4 );

    SC_METHOD(thread_sext_ln708_124_fu_607_p1);
    sensitive << ( trunc_ln708_200_fu_597_p4 );

    SC_METHOD(thread_sext_ln708_125_fu_621_p1);
    sensitive << ( trunc_ln708_201_fu_611_p4 );

    SC_METHOD(thread_sext_ln708_126_fu_659_p1);
    sensitive << ( tmp_49_fu_649_p4 );

    SC_METHOD(thread_sext_ln708_127_fu_744_p1);
    sensitive << ( trunc_ln708_206_fu_735_p4 );

    SC_METHOD(thread_sext_ln708_128_fu_1001_p1);
    sensitive << ( trunc_ln708_208_reg_1275 );

    SC_METHOD(thread_sext_ln708_129_fu_1004_p1);
    sensitive << ( trunc_ln708_209_reg_1280 );

    SC_METHOD(thread_sext_ln708_130_fu_840_p1);
    sensitive << ( trunc_ln708_210_fu_830_p4 );

    SC_METHOD(thread_sext_ln708_131_fu_872_p1);
    sensitive << ( trunc_ln708_213_fu_862_p4 );

    SC_METHOD(thread_sext_ln708_fu_535_p1);
    sensitive << ( trunc_ln708_198_fu_525_p4 );

    SC_METHOD(thread_shl_ln1118_107_fu_501_p1);
    sensitive << ( call_ret_relu_fu_200_ap_return_6 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_shl_ln1118_107_fu_501_p3);
    sensitive << ( shl_ln1118_107_fu_501_p1 );

    SC_METHOD(thread_shl_ln1118_108_fu_906_p3);
    sensitive << ( data1_7_V_reg_1243 );

    SC_METHOD(thread_shl_ln1118_109_fu_567_p1);
    sensitive << ( call_ret_relu_fu_200_ap_return_0 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_shl_ln1118_109_fu_567_p3);
    sensitive << ( shl_ln1118_109_fu_567_p1 );

    SC_METHOD(thread_shl_ln1118_110_fu_579_p1);
    sensitive << ( call_ret_relu_fu_200_ap_return_0 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_shl_ln1118_110_fu_579_p3);
    sensitive << ( shl_ln1118_110_fu_579_p1 );

    SC_METHOD(thread_shl_ln1118_111_fu_673_p1);
    sensitive << ( call_ret_relu_fu_200_ap_return_6 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_shl_ln1118_111_fu_673_p3);
    sensitive << ( shl_ln1118_111_fu_673_p1 );

    SC_METHOD(thread_shl_ln1118_112_fu_794_p1);
    sensitive << ( call_ret_relu_fu_200_ap_return_4 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_shl_ln1118_112_fu_794_p3);
    sensitive << ( shl_ln1118_112_fu_794_p1 );

    SC_METHOD(thread_shl_ln1118_113_fu_812_p1);
    sensitive << ( call_ret_relu_fu_200_ap_return_4 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_shl_ln1118_113_fu_812_p3);
    sensitive << ( shl_ln1118_113_fu_812_p1 );

    SC_METHOD(thread_shl_ln1118_s_fu_444_p1);
    sensitive << ( call_ret_relu_fu_200_ap_return_4 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_shl_ln1118_s_fu_444_p3);
    sensitive << ( shl_ln1118_s_fu_444_p1 );

    SC_METHOD(thread_shl_ln_fu_426_p1);
    sensitive << ( call_ret_relu_fu_200_ap_return_4 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_shl_ln_fu_426_p3);
    sensitive << ( shl_ln_fu_426_p1 );

    SC_METHOD(thread_sub_ln1118_103_fu_394_p2);
    sensitive << ( sext_ln1118_231_fu_378_p1 );
    sensitive << ( sext_ln1118_232_fu_390_p1 );

    SC_METHOD(thread_sub_ln1118_104_fu_456_p2);
    sensitive << ( sub_ln1118_fu_438_p2 );
    sensitive << ( sext_ln1118_237_fu_452_p1 );

    SC_METHOD(thread_sub_ln1118_105_fu_513_p2);
    sensitive << ( sext_ln1118_242_fu_509_p1 );

    SC_METHOD(thread_sub_ln1118_106_fu_519_p2);
    sensitive << ( sub_ln1118_105_fu_513_p2 );
    sensitive << ( sext_ln1118_241_fu_497_p1 );

    SC_METHOD(thread_sub_ln1118_107_fu_917_p2);
    sensitive << ( sext_ln1118_245_fu_913_p1 );

    SC_METHOD(thread_sub_ln1118_108_fu_923_p2);
    sensitive << ( sub_ln1118_107_fu_917_p2 );
    sensitive << ( sext_ln1118_244_fu_903_p1 );

    SC_METHOD(thread_sub_ln1118_109_fu_591_p2);
    sensitive << ( sext_ln1118_247_fu_587_p1 );
    sensitive << ( sext_ln1118_246_fu_575_p1 );

    SC_METHOD(thread_sub_ln1118_110_fu_685_p2);
    sensitive << ( sext_ln1118_249_fu_681_p1 );

    SC_METHOD(thread_sub_ln1118_111_fu_691_p2);
    sensitive << ( sub_ln1118_110_fu_685_p2 );
    sensitive << ( sext_ln1118_240_fu_493_p1 );

    SC_METHOD(thread_sub_ln1118_112_fu_769_p2);
    sensitive << ( sext_ln1118_230_fu_374_p1 );
    sensitive << ( sext_ln1118_250_fu_765_p1 );

    SC_METHOD(thread_sub_ln1118_113_fu_806_p2);
    sensitive << ( sext_ln1118_251_fu_802_p1 );

    SC_METHOD(thread_sub_ln1118_114_fu_824_p2);
    sensitive << ( sub_ln1118_113_fu_806_p2 );
    sensitive << ( sext_ln1118_252_fu_820_p1 );

    SC_METHOD(thread_sub_ln1118_fu_438_p2);
    sensitive << ( sext_ln1118_236_fu_434_p1 );

    SC_METHOD(thread_tmp_47_fu_400_p4);
    sensitive << ( sub_ln1118_103_fu_394_p2 );

    SC_METHOD(thread_tmp_48_fu_462_p4);
    sensitive << ( sub_ln1118_104_fu_456_p2 );

    SC_METHOD(thread_tmp_49_fu_649_p4);
    sensitive << ( mul_ln1118_131_fu_643_p2 );

    SC_METHOD(thread_tmp_50_fu_697_p4);
    sensitive << ( sub_ln1118_111_fu_691_p2 );

    SC_METHOD(thread_tmp_fu_382_p1);
    sensitive << ( call_ret_relu_fu_200_ap_return_2 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_tmp_fu_382_p3);
    sensitive << ( tmp_fu_382_p1 );

    SC_METHOD(thread_tmp_s_fu_757_p1);
    sensitive << ( call_ret_relu_fu_200_ap_return_2 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_tmp_s_fu_757_p3);
    sensitive << ( tmp_s_fu_757_p1 );

    SC_METHOD(thread_trunc_ln708_197_fu_480_p4);
    sensitive << ( mul_ln1118_128_fu_1060_p2 );

    SC_METHOD(thread_trunc_ln708_198_fu_525_p4);
    sensitive << ( sub_ln1118_106_fu_519_p2 );

    SC_METHOD(thread_trunc_ln708_199_fu_929_p4);
    sensitive << ( sub_ln1118_108_fu_923_p2 );

    SC_METHOD(thread_trunc_ln708_200_fu_597_p4);
    sensitive << ( sub_ln1118_109_fu_591_p2 );

    SC_METHOD(thread_trunc_ln708_201_fu_611_p1);
    sensitive << ( call_ret_relu_fu_200_ap_return_1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_trunc_ln708_201_fu_611_p4);
    sensitive << ( trunc_ln708_201_fu_611_p1 );

    SC_METHOD(thread_trunc_ln708_202_fu_625_p4);
    sensitive << ( mul_ln1118_129_fu_1067_p2 );

    SC_METHOD(thread_trunc_ln708_203_fu_634_p4);
    sensitive << ( mul_ln1118_130_fu_1074_p2 );

    SC_METHOD(thread_trunc_ln708_204_fu_663_p1);
    sensitive << ( call_ret_relu_fu_200_ap_return_5 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_trunc_ln708_205_fu_962_p4);
    sensitive << ( mul_ln1118_132_fu_1116_p2 );

    SC_METHOD(thread_trunc_ln708_206_fu_735_p4);
    sensitive << ( mul_ln1118_133_fu_1081_p2 );

    SC_METHOD(thread_trunc_ln708_207_fu_748_p4);
    sensitive << ( mul_ln1118_134_fu_1088_p2 );

    SC_METHOD(thread_trunc_ln708_210_fu_830_p4);
    sensitive << ( sub_ln1118_114_fu_824_p2 );

    SC_METHOD(thread_trunc_ln708_211_fu_844_p4);
    sensitive << ( mul_ln1118_136_fu_1102_p2 );

    SC_METHOD(thread_trunc_ln708_212_fu_853_p4);
    sensitive << ( mul_ln1118_137_fu_1109_p2 );

    SC_METHOD(thread_trunc_ln708_213_fu_862_p1);
    sensitive << ( call_ret_relu_fu_200_ap_return_7 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_trunc_ln708_213_fu_862_p4);
    sensitive << ( trunc_ln708_213_fu_862_p1 );

    SC_METHOD(thread_trunc_ln708_s_fu_361_p4);
    sensitive << ( mul_ln1118_127_fu_1053_p2 );

    SC_METHOD(thread_trunc_ln_fu_348_p4);
    sensitive << ( mul_ln1118_fu_1046_p2 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dense_mult_3lyr_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, data_0_V_read, "(port)data_0_V_read");
    sc_trace(mVcdFile, data_1_V_read, "(port)data_1_V_read");
    sc_trace(mVcdFile, data_2_V_read, "(port)data_2_V_read");
    sc_trace(mVcdFile, data_3_V_read, "(port)data_3_V_read");
    sc_trace(mVcdFile, data_4_V_read, "(port)data_4_V_read");
    sc_trace(mVcdFile, data_5_V_read, "(port)data_5_V_read");
    sc_trace(mVcdFile, data_6_V_read, "(port)data_6_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, data0_logits_0_V_reg_1123, "data0_logits_0_V_reg_1123");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3, "ap_block_state4_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter4, "ap_block_state5_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter5, "ap_block_state6_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter6, "ap_block_state7_pp0_stage0_iter6");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, data0_logits_1_V_reg_1128, "data0_logits_1_V_reg_1128");
    sc_trace(mVcdFile, data0_logits_2_V_reg_1133, "data0_logits_2_V_reg_1133");
    sc_trace(mVcdFile, data0_logits_3_V_reg_1138, "data0_logits_3_V_reg_1138");
    sc_trace(mVcdFile, data0_logits_4_V_reg_1143, "data0_logits_4_V_reg_1143");
    sc_trace(mVcdFile, data0_logits_5_V_reg_1148, "data0_logits_5_V_reg_1148");
    sc_trace(mVcdFile, data0_logits_6_V_reg_1153, "data0_logits_6_V_reg_1153");
    sc_trace(mVcdFile, data0_logits_7_V_reg_1158, "data0_logits_7_V_reg_1158");
    sc_trace(mVcdFile, data0_0_V_reg_1163, "data0_0_V_reg_1163");
    sc_trace(mVcdFile, data0_1_V_reg_1168, "data0_1_V_reg_1168");
    sc_trace(mVcdFile, data0_2_V_reg_1173, "data0_2_V_reg_1173");
    sc_trace(mVcdFile, data0_3_V_reg_1178, "data0_3_V_reg_1178");
    sc_trace(mVcdFile, data0_4_V_reg_1183, "data0_4_V_reg_1183");
    sc_trace(mVcdFile, data0_5_V_reg_1188, "data0_5_V_reg_1188");
    sc_trace(mVcdFile, data0_6_V_reg_1193, "data0_6_V_reg_1193");
    sc_trace(mVcdFile, data0_7_V_reg_1198, "data0_7_V_reg_1198");
    sc_trace(mVcdFile, data1_logits_0_V_reg_1203, "data1_logits_0_V_reg_1203");
    sc_trace(mVcdFile, data1_logits_1_V_reg_1208, "data1_logits_1_V_reg_1208");
    sc_trace(mVcdFile, data1_logits_2_V_reg_1213, "data1_logits_2_V_reg_1213");
    sc_trace(mVcdFile, data1_logits_3_V_reg_1218, "data1_logits_3_V_reg_1218");
    sc_trace(mVcdFile, data1_logits_4_V_reg_1223, "data1_logits_4_V_reg_1223");
    sc_trace(mVcdFile, data1_logits_5_V_reg_1228, "data1_logits_5_V_reg_1228");
    sc_trace(mVcdFile, data1_logits_6_V_reg_1233, "data1_logits_6_V_reg_1233");
    sc_trace(mVcdFile, data1_logits_7_V_reg_1238, "data1_logits_7_V_reg_1238");
    sc_trace(mVcdFile, data1_7_V_reg_1243, "data1_7_V_reg_1243");
    sc_trace(mVcdFile, add_ln703_293_fu_555_p2, "add_ln703_293_fu_555_p2");
    sc_trace(mVcdFile, add_ln703_293_reg_1250, "add_ln703_293_reg_1250");
    sc_trace(mVcdFile, add_ln703_294_fu_561_p2, "add_ln703_294_fu_561_p2");
    sc_trace(mVcdFile, add_ln703_294_reg_1255, "add_ln703_294_reg_1255");
    sc_trace(mVcdFile, trunc_ln708_204_reg_1260, "trunc_ln708_204_reg_1260");
    sc_trace(mVcdFile, add_ln703_300_fu_723_p2, "add_ln703_300_fu_723_p2");
    sc_trace(mVcdFile, add_ln703_300_reg_1265, "add_ln703_300_reg_1265");
    sc_trace(mVcdFile, add_ln703_301_fu_729_p2, "add_ln703_301_fu_729_p2");
    sc_trace(mVcdFile, add_ln703_301_reg_1270, "add_ln703_301_reg_1270");
    sc_trace(mVcdFile, trunc_ln708_208_reg_1275, "trunc_ln708_208_reg_1275");
    sc_trace(mVcdFile, trunc_ln708_209_reg_1280, "trunc_ln708_209_reg_1280");
    sc_trace(mVcdFile, add_ln703_306_fu_876_p2, "add_ln703_306_fu_876_p2");
    sc_trace(mVcdFile, add_ln703_306_reg_1285, "add_ln703_306_reg_1285");
    sc_trace(mVcdFile, add_ln703_309_fu_882_p2, "add_ln703_309_fu_882_p2");
    sc_trace(mVcdFile, add_ln703_309_reg_1290, "add_ln703_309_reg_1290");
    sc_trace(mVcdFile, add_ln703_311_fu_894_p2, "add_ln703_311_fu_894_p2");
    sc_trace(mVcdFile, add_ln703_311_reg_1295, "add_ln703_311_reg_1295");
    sc_trace(mVcdFile, grp_dense_resource_1_0_fu_158_ap_return_0, "grp_dense_resource_1_0_fu_158_ap_return_0");
    sc_trace(mVcdFile, grp_dense_resource_1_0_fu_158_ap_return_1, "grp_dense_resource_1_0_fu_158_ap_return_1");
    sc_trace(mVcdFile, grp_dense_resource_1_0_fu_158_ap_return_2, "grp_dense_resource_1_0_fu_158_ap_return_2");
    sc_trace(mVcdFile, grp_dense_resource_1_0_fu_158_ap_return_3, "grp_dense_resource_1_0_fu_158_ap_return_3");
    sc_trace(mVcdFile, grp_dense_resource_1_0_fu_158_ap_return_4, "grp_dense_resource_1_0_fu_158_ap_return_4");
    sc_trace(mVcdFile, grp_dense_resource_1_0_fu_158_ap_return_5, "grp_dense_resource_1_0_fu_158_ap_return_5");
    sc_trace(mVcdFile, grp_dense_resource_1_0_fu_158_ap_return_6, "grp_dense_resource_1_0_fu_158_ap_return_6");
    sc_trace(mVcdFile, grp_dense_resource_1_0_fu_158_ap_return_7, "grp_dense_resource_1_0_fu_158_ap_return_7");
    sc_trace(mVcdFile, grp_dense_resource_1_0_fu_158_ap_ce, "grp_dense_resource_1_0_fu_158_ap_ce");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0_ignore_call25, "ap_block_state1_pp0_stage0_iter0_ignore_call25");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1_ignore_call25, "ap_block_state2_pp0_stage0_iter1_ignore_call25");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2_ignore_call25, "ap_block_state3_pp0_stage0_iter2_ignore_call25");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3_ignore_call25, "ap_block_state4_pp0_stage0_iter3_ignore_call25");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter4_ignore_call25, "ap_block_state5_pp0_stage0_iter4_ignore_call25");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter5_ignore_call25, "ap_block_state6_pp0_stage0_iter5_ignore_call25");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter6_ignore_call25, "ap_block_state7_pp0_stage0_iter6_ignore_call25");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001_ignoreCallOp34, "ap_block_pp0_stage0_11001_ignoreCallOp34");
    sc_trace(mVcdFile, grp_dense_resource_0_0_2_fu_170_ap_return_0, "grp_dense_resource_0_0_2_fu_170_ap_return_0");
    sc_trace(mVcdFile, grp_dense_resource_0_0_2_fu_170_ap_return_1, "grp_dense_resource_0_0_2_fu_170_ap_return_1");
    sc_trace(mVcdFile, grp_dense_resource_0_0_2_fu_170_ap_return_2, "grp_dense_resource_0_0_2_fu_170_ap_return_2");
    sc_trace(mVcdFile, grp_dense_resource_0_0_2_fu_170_ap_return_3, "grp_dense_resource_0_0_2_fu_170_ap_return_3");
    sc_trace(mVcdFile, grp_dense_resource_0_0_2_fu_170_ap_return_4, "grp_dense_resource_0_0_2_fu_170_ap_return_4");
    sc_trace(mVcdFile, grp_dense_resource_0_0_2_fu_170_ap_return_5, "grp_dense_resource_0_0_2_fu_170_ap_return_5");
    sc_trace(mVcdFile, grp_dense_resource_0_0_2_fu_170_ap_return_6, "grp_dense_resource_0_0_2_fu_170_ap_return_6");
    sc_trace(mVcdFile, grp_dense_resource_0_0_2_fu_170_ap_return_7, "grp_dense_resource_0_0_2_fu_170_ap_return_7");
    sc_trace(mVcdFile, grp_dense_resource_0_0_2_fu_170_ap_ce, "grp_dense_resource_0_0_2_fu_170_ap_ce");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0_ignore_call7, "ap_block_state1_pp0_stage0_iter0_ignore_call7");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1_ignore_call7, "ap_block_state2_pp0_stage0_iter1_ignore_call7");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2_ignore_call7, "ap_block_state3_pp0_stage0_iter2_ignore_call7");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3_ignore_call7, "ap_block_state4_pp0_stage0_iter3_ignore_call7");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter4_ignore_call7, "ap_block_state5_pp0_stage0_iter4_ignore_call7");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter5_ignore_call7, "ap_block_state6_pp0_stage0_iter5_ignore_call7");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter6_ignore_call7, "ap_block_state7_pp0_stage0_iter6_ignore_call7");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001_ignoreCallOp15, "ap_block_pp0_stage0_11001_ignoreCallOp15");
    sc_trace(mVcdFile, call_ret2_relu_fu_188_ap_ready, "call_ret2_relu_fu_188_ap_ready");
    sc_trace(mVcdFile, call_ret2_relu_fu_188_ap_return_0, "call_ret2_relu_fu_188_ap_return_0");
    sc_trace(mVcdFile, call_ret2_relu_fu_188_ap_return_1, "call_ret2_relu_fu_188_ap_return_1");
    sc_trace(mVcdFile, call_ret2_relu_fu_188_ap_return_2, "call_ret2_relu_fu_188_ap_return_2");
    sc_trace(mVcdFile, call_ret2_relu_fu_188_ap_return_3, "call_ret2_relu_fu_188_ap_return_3");
    sc_trace(mVcdFile, call_ret2_relu_fu_188_ap_return_4, "call_ret2_relu_fu_188_ap_return_4");
    sc_trace(mVcdFile, call_ret2_relu_fu_188_ap_return_5, "call_ret2_relu_fu_188_ap_return_5");
    sc_trace(mVcdFile, call_ret2_relu_fu_188_ap_return_6, "call_ret2_relu_fu_188_ap_return_6");
    sc_trace(mVcdFile, call_ret2_relu_fu_188_ap_return_7, "call_ret2_relu_fu_188_ap_return_7");
    sc_trace(mVcdFile, call_ret_relu_fu_200_ap_ready, "call_ret_relu_fu_200_ap_ready");
    sc_trace(mVcdFile, call_ret_relu_fu_200_ap_return_0, "call_ret_relu_fu_200_ap_return_0");
    sc_trace(mVcdFile, call_ret_relu_fu_200_ap_return_1, "call_ret_relu_fu_200_ap_return_1");
    sc_trace(mVcdFile, call_ret_relu_fu_200_ap_return_2, "call_ret_relu_fu_200_ap_return_2");
    sc_trace(mVcdFile, call_ret_relu_fu_200_ap_return_3, "call_ret_relu_fu_200_ap_return_3");
    sc_trace(mVcdFile, call_ret_relu_fu_200_ap_return_4, "call_ret_relu_fu_200_ap_return_4");
    sc_trace(mVcdFile, call_ret_relu_fu_200_ap_return_5, "call_ret_relu_fu_200_ap_return_5");
    sc_trace(mVcdFile, call_ret_relu_fu_200_ap_return_6, "call_ret_relu_fu_200_ap_return_6");
    sc_trace(mVcdFile, call_ret_relu_fu_200_ap_return_7, "call_ret_relu_fu_200_ap_return_7");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, mul_ln1118_fu_1046_p2, "mul_ln1118_fu_1046_p2");
    sc_trace(mVcdFile, sext_ln1118_228_fu_357_p0, "sext_ln1118_228_fu_357_p0");
    sc_trace(mVcdFile, mul_ln1118_127_fu_1053_p2, "mul_ln1118_127_fu_1053_p2");
    sc_trace(mVcdFile, sext_ln1118_230_fu_374_p0, "sext_ln1118_230_fu_374_p0");
    sc_trace(mVcdFile, sext_ln1118_231_fu_378_p0, "sext_ln1118_231_fu_378_p0");
    sc_trace(mVcdFile, tmp_fu_382_p1, "tmp_fu_382_p1");
    sc_trace(mVcdFile, tmp_fu_382_p3, "tmp_fu_382_p3");
    sc_trace(mVcdFile, sext_ln1118_231_fu_378_p1, "sext_ln1118_231_fu_378_p1");
    sc_trace(mVcdFile, sext_ln1118_232_fu_390_p1, "sext_ln1118_232_fu_390_p1");
    sc_trace(mVcdFile, sub_ln1118_103_fu_394_p2, "sub_ln1118_103_fu_394_p2");
    sc_trace(mVcdFile, tmp_47_fu_400_p4, "tmp_47_fu_400_p4");
    sc_trace(mVcdFile, sext_ln1118_235_fu_422_p0, "sext_ln1118_235_fu_422_p0");
    sc_trace(mVcdFile, shl_ln_fu_426_p1, "shl_ln_fu_426_p1");
    sc_trace(mVcdFile, shl_ln_fu_426_p3, "shl_ln_fu_426_p3");
    sc_trace(mVcdFile, sext_ln1118_236_fu_434_p1, "sext_ln1118_236_fu_434_p1");
    sc_trace(mVcdFile, shl_ln1118_s_fu_444_p1, "shl_ln1118_s_fu_444_p1");
    sc_trace(mVcdFile, shl_ln1118_s_fu_444_p3, "shl_ln1118_s_fu_444_p3");
    sc_trace(mVcdFile, sub_ln1118_fu_438_p2, "sub_ln1118_fu_438_p2");
    sc_trace(mVcdFile, sext_ln1118_237_fu_452_p1, "sext_ln1118_237_fu_452_p1");
    sc_trace(mVcdFile, sub_ln1118_104_fu_456_p2, "sub_ln1118_104_fu_456_p2");
    sc_trace(mVcdFile, tmp_48_fu_462_p4, "tmp_48_fu_462_p4");
    sc_trace(mVcdFile, sext_ln1118_238_fu_476_p0, "sext_ln1118_238_fu_476_p0");
    sc_trace(mVcdFile, mul_ln1118_128_fu_1060_p2, "mul_ln1118_128_fu_1060_p2");
    sc_trace(mVcdFile, sext_ln1118_240_fu_493_p0, "sext_ln1118_240_fu_493_p0");
    sc_trace(mVcdFile, sext_ln1118_241_fu_497_p0, "sext_ln1118_241_fu_497_p0");
    sc_trace(mVcdFile, shl_ln1118_107_fu_501_p1, "shl_ln1118_107_fu_501_p1");
    sc_trace(mVcdFile, shl_ln1118_107_fu_501_p3, "shl_ln1118_107_fu_501_p3");
    sc_trace(mVcdFile, sext_ln1118_242_fu_509_p1, "sext_ln1118_242_fu_509_p1");
    sc_trace(mVcdFile, sub_ln1118_105_fu_513_p2, "sub_ln1118_105_fu_513_p2");
    sc_trace(mVcdFile, sext_ln1118_241_fu_497_p1, "sext_ln1118_241_fu_497_p1");
    sc_trace(mVcdFile, sub_ln1118_106_fu_519_p2, "sub_ln1118_106_fu_519_p2");
    sc_trace(mVcdFile, trunc_ln708_198_fu_525_p4, "trunc_ln708_198_fu_525_p4");
    sc_trace(mVcdFile, trunc_ln708_s_fu_361_p4, "trunc_ln708_s_fu_361_p4");
    sc_trace(mVcdFile, trunc_ln_fu_348_p4, "trunc_ln_fu_348_p4");
    sc_trace(mVcdFile, sext_ln1118_254_fu_472_p1, "sext_ln1118_254_fu_472_p1");
    sc_trace(mVcdFile, sext_ln1118_253_fu_410_p1, "sext_ln1118_253_fu_410_p1");
    sc_trace(mVcdFile, add_ln703_292_fu_545_p2, "add_ln703_292_fu_545_p2");
    sc_trace(mVcdFile, add_ln703_fu_539_p2, "add_ln703_fu_539_p2");
    sc_trace(mVcdFile, sext_ln703_40_fu_551_p1, "sext_ln703_40_fu_551_p1");
    sc_trace(mVcdFile, sext_ln708_fu_535_p1, "sext_ln708_fu_535_p1");
    sc_trace(mVcdFile, trunc_ln708_197_fu_480_p4, "trunc_ln708_197_fu_480_p4");
    sc_trace(mVcdFile, shl_ln1118_109_fu_567_p1, "shl_ln1118_109_fu_567_p1");
    sc_trace(mVcdFile, shl_ln1118_109_fu_567_p3, "shl_ln1118_109_fu_567_p3");
    sc_trace(mVcdFile, shl_ln1118_110_fu_579_p1, "shl_ln1118_110_fu_579_p1");
    sc_trace(mVcdFile, shl_ln1118_110_fu_579_p3, "shl_ln1118_110_fu_579_p3");
    sc_trace(mVcdFile, sext_ln1118_247_fu_587_p1, "sext_ln1118_247_fu_587_p1");
    sc_trace(mVcdFile, sext_ln1118_246_fu_575_p1, "sext_ln1118_246_fu_575_p1");
    sc_trace(mVcdFile, sub_ln1118_109_fu_591_p2, "sub_ln1118_109_fu_591_p2");
    sc_trace(mVcdFile, trunc_ln708_200_fu_597_p4, "trunc_ln708_200_fu_597_p4");
    sc_trace(mVcdFile, trunc_ln708_201_fu_611_p1, "trunc_ln708_201_fu_611_p1");
    sc_trace(mVcdFile, trunc_ln708_201_fu_611_p4, "trunc_ln708_201_fu_611_p4");
    sc_trace(mVcdFile, mul_ln1118_129_fu_1067_p2, "mul_ln1118_129_fu_1067_p2");
    sc_trace(mVcdFile, mul_ln1118_130_fu_1074_p2, "mul_ln1118_130_fu_1074_p2");
    sc_trace(mVcdFile, mul_ln1118_131_fu_643_p0, "mul_ln1118_131_fu_643_p0");
    sc_trace(mVcdFile, mul_ln1118_131_fu_643_p2, "mul_ln1118_131_fu_643_p2");
    sc_trace(mVcdFile, tmp_49_fu_649_p4, "tmp_49_fu_649_p4");
    sc_trace(mVcdFile, trunc_ln708_204_fu_663_p1, "trunc_ln708_204_fu_663_p1");
    sc_trace(mVcdFile, shl_ln1118_111_fu_673_p1, "shl_ln1118_111_fu_673_p1");
    sc_trace(mVcdFile, shl_ln1118_111_fu_673_p3, "shl_ln1118_111_fu_673_p3");
    sc_trace(mVcdFile, sext_ln1118_249_fu_681_p1, "sext_ln1118_249_fu_681_p1");
    sc_trace(mVcdFile, sub_ln1118_110_fu_685_p2, "sub_ln1118_110_fu_685_p2");
    sc_trace(mVcdFile, sext_ln1118_240_fu_493_p1, "sext_ln1118_240_fu_493_p1");
    sc_trace(mVcdFile, sub_ln1118_111_fu_691_p2, "sub_ln1118_111_fu_691_p2");
    sc_trace(mVcdFile, tmp_50_fu_697_p4, "tmp_50_fu_697_p4");
    sc_trace(mVcdFile, sext_ln708_125_fu_621_p1, "sext_ln708_125_fu_621_p1");
    sc_trace(mVcdFile, sext_ln708_124_fu_607_p1, "sext_ln708_124_fu_607_p1");
    sc_trace(mVcdFile, trunc_ln708_203_fu_634_p4, "trunc_ln708_203_fu_634_p4");
    sc_trace(mVcdFile, trunc_ln708_202_fu_625_p4, "trunc_ln708_202_fu_625_p4");
    sc_trace(mVcdFile, add_ln703_298_fu_711_p2, "add_ln703_298_fu_711_p2");
    sc_trace(mVcdFile, add_ln703_299_fu_717_p2, "add_ln703_299_fu_717_p2");
    sc_trace(mVcdFile, sext_ln1118_255_fu_707_p1, "sext_ln1118_255_fu_707_p1");
    sc_trace(mVcdFile, sext_ln708_126_fu_659_p1, "sext_ln708_126_fu_659_p1");
    sc_trace(mVcdFile, mul_ln1118_133_fu_1081_p2, "mul_ln1118_133_fu_1081_p2");
    sc_trace(mVcdFile, trunc_ln708_206_fu_735_p4, "trunc_ln708_206_fu_735_p4");
    sc_trace(mVcdFile, mul_ln1118_134_fu_1088_p2, "mul_ln1118_134_fu_1088_p2");
    sc_trace(mVcdFile, tmp_s_fu_757_p1, "tmp_s_fu_757_p1");
    sc_trace(mVcdFile, tmp_s_fu_757_p3, "tmp_s_fu_757_p3");
    sc_trace(mVcdFile, sext_ln1118_230_fu_374_p1, "sext_ln1118_230_fu_374_p1");
    sc_trace(mVcdFile, sext_ln1118_250_fu_765_p1, "sext_ln1118_250_fu_765_p1");
    sc_trace(mVcdFile, sub_ln1118_112_fu_769_p2, "sub_ln1118_112_fu_769_p2");
    sc_trace(mVcdFile, mul_ln1118_135_fu_1095_p2, "mul_ln1118_135_fu_1095_p2");
    sc_trace(mVcdFile, shl_ln1118_112_fu_794_p1, "shl_ln1118_112_fu_794_p1");
    sc_trace(mVcdFile, shl_ln1118_112_fu_794_p3, "shl_ln1118_112_fu_794_p3");
    sc_trace(mVcdFile, sext_ln1118_251_fu_802_p1, "sext_ln1118_251_fu_802_p1");
    sc_trace(mVcdFile, shl_ln1118_113_fu_812_p1, "shl_ln1118_113_fu_812_p1");
    sc_trace(mVcdFile, shl_ln1118_113_fu_812_p3, "shl_ln1118_113_fu_812_p3");
    sc_trace(mVcdFile, sub_ln1118_113_fu_806_p2, "sub_ln1118_113_fu_806_p2");
    sc_trace(mVcdFile, sext_ln1118_252_fu_820_p1, "sext_ln1118_252_fu_820_p1");
    sc_trace(mVcdFile, sub_ln1118_114_fu_824_p2, "sub_ln1118_114_fu_824_p2");
    sc_trace(mVcdFile, trunc_ln708_210_fu_830_p4, "trunc_ln708_210_fu_830_p4");
    sc_trace(mVcdFile, mul_ln1118_136_fu_1102_p2, "mul_ln1118_136_fu_1102_p2");
    sc_trace(mVcdFile, mul_ln1118_137_fu_1109_p2, "mul_ln1118_137_fu_1109_p2");
    sc_trace(mVcdFile, trunc_ln708_213_fu_862_p1, "trunc_ln708_213_fu_862_p1");
    sc_trace(mVcdFile, trunc_ln708_213_fu_862_p4, "trunc_ln708_213_fu_862_p4");
    sc_trace(mVcdFile, trunc_ln708_207_fu_748_p4, "trunc_ln708_207_fu_748_p4");
    sc_trace(mVcdFile, sext_ln708_127_fu_744_p1, "sext_ln708_127_fu_744_p1");
    sc_trace(mVcdFile, trunc_ln708_211_fu_844_p4, "trunc_ln708_211_fu_844_p4");
    sc_trace(mVcdFile, sext_ln708_130_fu_840_p1, "sext_ln708_130_fu_840_p1");
    sc_trace(mVcdFile, sext_ln708_131_fu_872_p1, "sext_ln708_131_fu_872_p1");
    sc_trace(mVcdFile, trunc_ln708_212_fu_853_p4, "trunc_ln708_212_fu_853_p4");
    sc_trace(mVcdFile, add_ln703_310_fu_888_p2, "add_ln703_310_fu_888_p2");
    sc_trace(mVcdFile, shl_ln1118_108_fu_906_p3, "shl_ln1118_108_fu_906_p3");
    sc_trace(mVcdFile, sext_ln1118_245_fu_913_p1, "sext_ln1118_245_fu_913_p1");
    sc_trace(mVcdFile, sub_ln1118_107_fu_917_p2, "sub_ln1118_107_fu_917_p2");
    sc_trace(mVcdFile, sext_ln1118_244_fu_903_p1, "sext_ln1118_244_fu_903_p1");
    sc_trace(mVcdFile, sub_ln1118_108_fu_923_p2, "sub_ln1118_108_fu_923_p2");
    sc_trace(mVcdFile, trunc_ln708_199_fu_929_p4, "trunc_ln708_199_fu_929_p4");
    sc_trace(mVcdFile, sext_ln708_123_fu_939_p1, "sext_ln708_123_fu_939_p1");
    sc_trace(mVcdFile, add_ln703_295_fu_943_p2, "add_ln703_295_fu_943_p2");
    sc_trace(mVcdFile, add_ln703_296_fu_949_p2, "add_ln703_296_fu_949_p2");
    sc_trace(mVcdFile, mul_ln1118_132_fu_1116_p2, "mul_ln1118_132_fu_1116_p2");
    sc_trace(mVcdFile, sext_ln1118_248_fu_959_p1, "sext_ln1118_248_fu_959_p1");
    sc_trace(mVcdFile, add_ln703_302_fu_974_p2, "add_ln703_302_fu_974_p2");
    sc_trace(mVcdFile, trunc_ln708_205_fu_962_p4, "trunc_ln708_205_fu_962_p4");
    sc_trace(mVcdFile, sext_ln703_fu_980_p1, "sext_ln703_fu_980_p1");
    sc_trace(mVcdFile, sext_ln703_41_fu_971_p1, "sext_ln703_41_fu_971_p1");
    sc_trace(mVcdFile, add_ln703_303_fu_984_p2, "add_ln703_303_fu_984_p2");
    sc_trace(mVcdFile, add_ln703_304_fu_990_p2, "add_ln703_304_fu_990_p2");
    sc_trace(mVcdFile, sext_ln708_129_fu_1004_p1, "sext_ln708_129_fu_1004_p1");
    sc_trace(mVcdFile, sext_ln708_128_fu_1001_p1, "sext_ln708_128_fu_1001_p1");
    sc_trace(mVcdFile, add_ln703_307_fu_1007_p2, "add_ln703_307_fu_1007_p2");
    sc_trace(mVcdFile, add_ln703_308_fu_1013_p2, "add_ln703_308_fu_1013_p2");
    sc_trace(mVcdFile, add_ln703_312_fu_1018_p2, "add_ln703_312_fu_1018_p2");
    sc_trace(mVcdFile, add_ln703_297_fu_954_p2, "add_ln703_297_fu_954_p2");
    sc_trace(mVcdFile, add_ln703_305_fu_996_p2, "add_ln703_305_fu_996_p2");
    sc_trace(mVcdFile, add_ln703_313_fu_1022_p2, "add_ln703_313_fu_1022_p2");
    sc_trace(mVcdFile, mul_ln1118_fu_1046_p1, "mul_ln1118_fu_1046_p1");
    sc_trace(mVcdFile, mul_ln1118_127_fu_1053_p0, "mul_ln1118_127_fu_1053_p0");
    sc_trace(mVcdFile, sext_ln1118_228_fu_357_p1, "sext_ln1118_228_fu_357_p1");
    sc_trace(mVcdFile, mul_ln1118_127_fu_1053_p1, "mul_ln1118_127_fu_1053_p1");
    sc_trace(mVcdFile, mul_ln1118_128_fu_1060_p0, "mul_ln1118_128_fu_1060_p0");
    sc_trace(mVcdFile, sext_ln1118_238_fu_476_p1, "sext_ln1118_238_fu_476_p1");
    sc_trace(mVcdFile, mul_ln1118_128_fu_1060_p1, "mul_ln1118_128_fu_1060_p1");
    sc_trace(mVcdFile, mul_ln1118_129_fu_1067_p1, "mul_ln1118_129_fu_1067_p1");
    sc_trace(mVcdFile, mul_ln1118_130_fu_1074_p1, "mul_ln1118_130_fu_1074_p1");
    sc_trace(mVcdFile, mul_ln1118_133_fu_1081_p1, "mul_ln1118_133_fu_1081_p1");
    sc_trace(mVcdFile, mul_ln1118_134_fu_1088_p0, "mul_ln1118_134_fu_1088_p0");
    sc_trace(mVcdFile, mul_ln1118_134_fu_1088_p1, "mul_ln1118_134_fu_1088_p1");
    sc_trace(mVcdFile, mul_ln1118_135_fu_1095_p1, "mul_ln1118_135_fu_1095_p1");
    sc_trace(mVcdFile, mul_ln1118_136_fu_1102_p0, "mul_ln1118_136_fu_1102_p0");
    sc_trace(mVcdFile, mul_ln1118_136_fu_1102_p1, "mul_ln1118_136_fu_1102_p1");
    sc_trace(mVcdFile, mul_ln1118_137_fu_1109_p1, "mul_ln1118_137_fu_1109_p1");
    sc_trace(mVcdFile, mul_ln1118_132_fu_1116_p1, "mul_ln1118_132_fu_1116_p1");
    sc_trace(mVcdFile, data_0_V_read_int_reg, "data_0_V_read_int_reg");
    sc_trace(mVcdFile, data_1_V_read_int_reg, "data_1_V_read_int_reg");
    sc_trace(mVcdFile, data_2_V_read_int_reg, "data_2_V_read_int_reg");
    sc_trace(mVcdFile, data_3_V_read_int_reg, "data_3_V_read_int_reg");
    sc_trace(mVcdFile, data_4_V_read_int_reg, "data_4_V_read_int_reg");
    sc_trace(mVcdFile, data_5_V_read_int_reg, "data_5_V_read_int_reg");
    sc_trace(mVcdFile, data_6_V_read_int_reg, "data_6_V_read_int_reg");
#endif

    }
}

dense_mult_3lyr::~dense_mult_3lyr() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_dense_resource_1_0_fu_158;
    delete grp_dense_resource_0_0_2_fu_170;
    delete call_ret2_relu_fu_188;
    delete call_ret_relu_fu_200;
    delete example_mul_mul_1ncg_U1591;
    delete example_mul_mul_1ocq_U1592;
    delete example_mul_mul_1ocq_U1593;
    delete example_mul_mul_1ocq_U1594;
    delete example_mul_mul_1ncg_U1595;
    delete example_mul_mul_1rcU_U1596;
    delete example_mul_mul_1ocq_U1597;
    delete example_mul_mul_1tde_U1598;
    delete example_mul_mul_1sc4_U1599;
    delete example_mul_mul_1wdI_U1600;
    delete example_mul_mul_1ncg_U1601;
}

void dense_mult_3lyr::thread_ap_clk_no_reset_() {
    data_0_V_read_int_reg = data_0_V_read.read();
    data_1_V_read_int_reg = data_1_V_read.read();
    data_2_V_read_int_reg = data_2_V_read.read();
    data_3_V_read_int_reg = data_3_V_read.read();
    data_4_V_read_int_reg = data_4_V_read.read();
    data_5_V_read_int_reg = data_5_V_read.read();
    data_6_V_read_int_reg = data_6_V_read.read();
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        add_ln703_293_reg_1250 = add_ln703_293_fu_555_p2.read();
        add_ln703_294_reg_1255 = add_ln703_294_fu_561_p2.read();
        add_ln703_300_reg_1265 = add_ln703_300_fu_723_p2.read();
        add_ln703_301_reg_1270 = add_ln703_301_fu_729_p2.read();
        add_ln703_306_reg_1285 = add_ln703_306_fu_876_p2.read();
        add_ln703_309_reg_1290 = add_ln703_309_fu_882_p2.read();
        add_ln703_311_reg_1295 = add_ln703_311_fu_894_p2.read();
        data0_0_V_reg_1163 = call_ret2_relu_fu_188_ap_return_0.read();
        data0_1_V_reg_1168 = call_ret2_relu_fu_188_ap_return_1.read();
        data0_2_V_reg_1173 = call_ret2_relu_fu_188_ap_return_2.read();
        data0_3_V_reg_1178 = call_ret2_relu_fu_188_ap_return_3.read();
        data0_4_V_reg_1183 = call_ret2_relu_fu_188_ap_return_4.read();
        data0_5_V_reg_1188 = call_ret2_relu_fu_188_ap_return_5.read();
        data0_6_V_reg_1193 = call_ret2_relu_fu_188_ap_return_6.read();
        data0_7_V_reg_1198 = call_ret2_relu_fu_188_ap_return_7.read();
        data0_logits_0_V_reg_1123 = grp_dense_resource_0_0_2_fu_170_ap_return_0.read();
        data0_logits_1_V_reg_1128 = grp_dense_resource_0_0_2_fu_170_ap_return_1.read();
        data0_logits_2_V_reg_1133 = grp_dense_resource_0_0_2_fu_170_ap_return_2.read();
        data0_logits_3_V_reg_1138 = grp_dense_resource_0_0_2_fu_170_ap_return_3.read();
        data0_logits_4_V_reg_1143 = grp_dense_resource_0_0_2_fu_170_ap_return_4.read();
        data0_logits_5_V_reg_1148 = grp_dense_resource_0_0_2_fu_170_ap_return_5.read();
        data0_logits_6_V_reg_1153 = grp_dense_resource_0_0_2_fu_170_ap_return_6.read();
        data0_logits_7_V_reg_1158 = grp_dense_resource_0_0_2_fu_170_ap_return_7.read();
        data1_7_V_reg_1243 = call_ret_relu_fu_200_ap_return_7.read();
        data1_logits_0_V_reg_1203 = grp_dense_resource_1_0_fu_158_ap_return_0.read();
        data1_logits_1_V_reg_1208 = grp_dense_resource_1_0_fu_158_ap_return_1.read();
        data1_logits_2_V_reg_1213 = grp_dense_resource_1_0_fu_158_ap_return_2.read();
        data1_logits_3_V_reg_1218 = grp_dense_resource_1_0_fu_158_ap_return_3.read();
        data1_logits_4_V_reg_1223 = grp_dense_resource_1_0_fu_158_ap_return_4.read();
        data1_logits_5_V_reg_1228 = grp_dense_resource_1_0_fu_158_ap_return_5.read();
        data1_logits_6_V_reg_1233 = grp_dense_resource_1_0_fu_158_ap_return_6.read();
        data1_logits_7_V_reg_1238 = grp_dense_resource_1_0_fu_158_ap_return_7.read();
        trunc_ln708_204_reg_1260 = trunc_ln708_204_fu_663_p1.read().range(13, 7);
        trunc_ln708_208_reg_1275 = sub_ln1118_112_fu_769_p2.read().range(17, 7);
        trunc_ln708_209_reg_1280 = mul_ln1118_135_fu_1095_p2.read().range(19, 7);
    }
}

void dense_mult_3lyr::thread_add_ln703_292_fu_545_p2() {
    add_ln703_292_fu_545_p2 = (!sext_ln1118_254_fu_472_p1.read().is_01() || !sext_ln1118_253_fu_410_p1.read().is_01())? sc_lv<13>(): (sc_bigint<13>(sext_ln1118_254_fu_472_p1.read()) + sc_bigint<13>(sext_ln1118_253_fu_410_p1.read()));
}

void dense_mult_3lyr::thread_add_ln703_293_fu_555_p2() {
    add_ln703_293_fu_555_p2 = (!add_ln703_fu_539_p2.read().is_01() || !sext_ln703_40_fu_551_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(add_ln703_fu_539_p2.read()) + sc_bigint<14>(sext_ln703_40_fu_551_p1.read()));
}

void dense_mult_3lyr::thread_add_ln703_294_fu_561_p2() {
    add_ln703_294_fu_561_p2 = (!sext_ln708_fu_535_p1.read().is_01() || !trunc_ln708_197_fu_480_p4.read().is_01())? sc_lv<14>(): (sc_bigint<14>(sext_ln708_fu_535_p1.read()) + sc_biguint<14>(trunc_ln708_197_fu_480_p4.read()));
}

void dense_mult_3lyr::thread_add_ln703_295_fu_943_p2() {
    add_ln703_295_fu_943_p2 = (!sext_ln708_123_fu_939_p1.read().is_01() || !ap_const_lv14_70.is_01())? sc_lv<14>(): (sc_bigint<14>(sext_ln708_123_fu_939_p1.read()) + sc_biguint<14>(ap_const_lv14_70));
}

void dense_mult_3lyr::thread_add_ln703_296_fu_949_p2() {
    add_ln703_296_fu_949_p2 = (!add_ln703_294_reg_1255.read().is_01() || !add_ln703_295_fu_943_p2.read().is_01())? sc_lv<14>(): (sc_biguint<14>(add_ln703_294_reg_1255.read()) + sc_biguint<14>(add_ln703_295_fu_943_p2.read()));
}

void dense_mult_3lyr::thread_add_ln703_297_fu_954_p2() {
    add_ln703_297_fu_954_p2 = (!add_ln703_293_reg_1250.read().is_01() || !add_ln703_296_fu_949_p2.read().is_01())? sc_lv<14>(): (sc_biguint<14>(add_ln703_293_reg_1250.read()) + sc_biguint<14>(add_ln703_296_fu_949_p2.read()));
}

void dense_mult_3lyr::thread_add_ln703_298_fu_711_p2() {
    add_ln703_298_fu_711_p2 = (!sext_ln708_125_fu_621_p1.read().is_01() || !sext_ln708_124_fu_607_p1.read().is_01())? sc_lv<14>(): (sc_bigint<14>(sext_ln708_125_fu_621_p1.read()) + sc_bigint<14>(sext_ln708_124_fu_607_p1.read()));
}

void dense_mult_3lyr::thread_add_ln703_299_fu_717_p2() {
    add_ln703_299_fu_717_p2 = (!trunc_ln708_203_fu_634_p4.read().is_01() || !trunc_ln708_202_fu_625_p4.read().is_01())? sc_lv<14>(): (sc_biguint<14>(trunc_ln708_203_fu_634_p4.read()) + sc_biguint<14>(trunc_ln708_202_fu_625_p4.read()));
}

void dense_mult_3lyr::thread_add_ln703_300_fu_723_p2() {
    add_ln703_300_fu_723_p2 = (!add_ln703_298_fu_711_p2.read().is_01() || !add_ln703_299_fu_717_p2.read().is_01())? sc_lv<14>(): (sc_biguint<14>(add_ln703_298_fu_711_p2.read()) + sc_biguint<14>(add_ln703_299_fu_717_p2.read()));
}

void dense_mult_3lyr::thread_add_ln703_301_fu_729_p2() {
    add_ln703_301_fu_729_p2 = (!sext_ln1118_255_fu_707_p1.read().is_01() || !sext_ln708_126_fu_659_p1.read().is_01())? sc_lv<13>(): (sc_bigint<13>(sext_ln1118_255_fu_707_p1.read()) + sc_bigint<13>(sext_ln708_126_fu_659_p1.read()));
}

void dense_mult_3lyr::thread_add_ln703_302_fu_974_p2() {
    add_ln703_302_fu_974_p2 = (!sext_ln1118_248_fu_959_p1.read().is_01() || !ap_const_lv8_D5.is_01())? sc_lv<8>(): (sc_bigint<8>(sext_ln1118_248_fu_959_p1.read()) + sc_bigint<8>(ap_const_lv8_D5));
}

void dense_mult_3lyr::thread_add_ln703_303_fu_984_p2() {
    add_ln703_303_fu_984_p2 = (!trunc_ln708_205_fu_962_p4.read().is_01() || !sext_ln703_fu_980_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(trunc_ln708_205_fu_962_p4.read()) + sc_bigint<14>(sext_ln703_fu_980_p1.read()));
}

void dense_mult_3lyr::thread_add_ln703_304_fu_990_p2() {
    add_ln703_304_fu_990_p2 = (!sext_ln703_41_fu_971_p1.read().is_01() || !add_ln703_303_fu_984_p2.read().is_01())? sc_lv<14>(): (sc_bigint<14>(sext_ln703_41_fu_971_p1.read()) + sc_biguint<14>(add_ln703_303_fu_984_p2.read()));
}

void dense_mult_3lyr::thread_add_ln703_305_fu_996_p2() {
    add_ln703_305_fu_996_p2 = (!add_ln703_300_reg_1265.read().is_01() || !add_ln703_304_fu_990_p2.read().is_01())? sc_lv<14>(): (sc_biguint<14>(add_ln703_300_reg_1265.read()) + sc_biguint<14>(add_ln703_304_fu_990_p2.read()));
}

void dense_mult_3lyr::thread_add_ln703_306_fu_876_p2() {
    add_ln703_306_fu_876_p2 = (!trunc_ln708_207_fu_748_p4.read().is_01() || !sext_ln708_127_fu_744_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(trunc_ln708_207_fu_748_p4.read()) + sc_bigint<14>(sext_ln708_127_fu_744_p1.read()));
}

void dense_mult_3lyr::thread_add_ln703_307_fu_1007_p2() {
    add_ln703_307_fu_1007_p2 = (!sext_ln708_129_fu_1004_p1.read().is_01() || !sext_ln708_128_fu_1001_p1.read().is_01())? sc_lv<14>(): (sc_bigint<14>(sext_ln708_129_fu_1004_p1.read()) + sc_bigint<14>(sext_ln708_128_fu_1001_p1.read()));
}

void dense_mult_3lyr::thread_add_ln703_308_fu_1013_p2() {
    add_ln703_308_fu_1013_p2 = (!add_ln703_306_reg_1285.read().is_01() || !add_ln703_307_fu_1007_p2.read().is_01())? sc_lv<14>(): (sc_biguint<14>(add_ln703_306_reg_1285.read()) + sc_biguint<14>(add_ln703_307_fu_1007_p2.read()));
}

void dense_mult_3lyr::thread_add_ln703_309_fu_882_p2() {
    add_ln703_309_fu_882_p2 = (!trunc_ln708_211_fu_844_p4.read().is_01() || !sext_ln708_130_fu_840_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(trunc_ln708_211_fu_844_p4.read()) + sc_bigint<14>(sext_ln708_130_fu_840_p1.read()));
}

void dense_mult_3lyr::thread_add_ln703_310_fu_888_p2() {
    add_ln703_310_fu_888_p2 = (!sext_ln708_131_fu_872_p1.read().is_01() || !ap_const_lv14_58.is_01())? sc_lv<14>(): (sc_bigint<14>(sext_ln708_131_fu_872_p1.read()) + sc_biguint<14>(ap_const_lv14_58));
}

void dense_mult_3lyr::thread_add_ln703_311_fu_894_p2() {
    add_ln703_311_fu_894_p2 = (!trunc_ln708_212_fu_853_p4.read().is_01() || !add_ln703_310_fu_888_p2.read().is_01())? sc_lv<14>(): (sc_biguint<14>(trunc_ln708_212_fu_853_p4.read()) + sc_biguint<14>(add_ln703_310_fu_888_p2.read()));
}

void dense_mult_3lyr::thread_add_ln703_312_fu_1018_p2() {
    add_ln703_312_fu_1018_p2 = (!add_ln703_309_reg_1290.read().is_01() || !add_ln703_311_reg_1295.read().is_01())? sc_lv<14>(): (sc_biguint<14>(add_ln703_309_reg_1290.read()) + sc_biguint<14>(add_ln703_311_reg_1295.read()));
}

void dense_mult_3lyr::thread_add_ln703_313_fu_1022_p2() {
    add_ln703_313_fu_1022_p2 = (!add_ln703_308_fu_1013_p2.read().is_01() || !add_ln703_312_fu_1018_p2.read().is_01())? sc_lv<14>(): (sc_biguint<14>(add_ln703_308_fu_1013_p2.read()) + sc_biguint<14>(add_ln703_312_fu_1018_p2.read()));
}

void dense_mult_3lyr::thread_add_ln703_fu_539_p2() {
    add_ln703_fu_539_p2 = (!trunc_ln708_s_fu_361_p4.read().is_01() || !trunc_ln_fu_348_p4.read().is_01())? sc_lv<14>(): (sc_biguint<14>(trunc_ln708_s_fu_361_p4.read()) + sc_biguint<14>(trunc_ln_fu_348_p4.read()));
}

void dense_mult_3lyr::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_mult_3lyr::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_mult_3lyr::thread_ap_block_pp0_stage0_11001_ignoreCallOp15() {
    ap_block_pp0_stage0_11001_ignoreCallOp15 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_mult_3lyr::thread_ap_block_pp0_stage0_11001_ignoreCallOp34() {
    ap_block_pp0_stage0_11001_ignoreCallOp34 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_mult_3lyr::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_mult_3lyr::thread_ap_block_state1_pp0_stage0_iter0_ignore_call25() {
    ap_block_state1_pp0_stage0_iter0_ignore_call25 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_mult_3lyr::thread_ap_block_state1_pp0_stage0_iter0_ignore_call7() {
    ap_block_state1_pp0_stage0_iter0_ignore_call7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_mult_3lyr::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_mult_3lyr::thread_ap_block_state2_pp0_stage0_iter1_ignore_call25() {
    ap_block_state2_pp0_stage0_iter1_ignore_call25 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_mult_3lyr::thread_ap_block_state2_pp0_stage0_iter1_ignore_call7() {
    ap_block_state2_pp0_stage0_iter1_ignore_call7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_mult_3lyr::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_mult_3lyr::thread_ap_block_state3_pp0_stage0_iter2_ignore_call25() {
    ap_block_state3_pp0_stage0_iter2_ignore_call25 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_mult_3lyr::thread_ap_block_state3_pp0_stage0_iter2_ignore_call7() {
    ap_block_state3_pp0_stage0_iter2_ignore_call7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_mult_3lyr::thread_ap_block_state4_pp0_stage0_iter3() {
    ap_block_state4_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_mult_3lyr::thread_ap_block_state4_pp0_stage0_iter3_ignore_call25() {
    ap_block_state4_pp0_stage0_iter3_ignore_call25 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_mult_3lyr::thread_ap_block_state4_pp0_stage0_iter3_ignore_call7() {
    ap_block_state4_pp0_stage0_iter3_ignore_call7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_mult_3lyr::thread_ap_block_state5_pp0_stage0_iter4() {
    ap_block_state5_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_mult_3lyr::thread_ap_block_state5_pp0_stage0_iter4_ignore_call25() {
    ap_block_state5_pp0_stage0_iter4_ignore_call25 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_mult_3lyr::thread_ap_block_state5_pp0_stage0_iter4_ignore_call7() {
    ap_block_state5_pp0_stage0_iter4_ignore_call7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_mult_3lyr::thread_ap_block_state6_pp0_stage0_iter5() {
    ap_block_state6_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_mult_3lyr::thread_ap_block_state6_pp0_stage0_iter5_ignore_call25() {
    ap_block_state6_pp0_stage0_iter5_ignore_call25 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_mult_3lyr::thread_ap_block_state6_pp0_stage0_iter5_ignore_call7() {
    ap_block_state6_pp0_stage0_iter5_ignore_call7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_mult_3lyr::thread_ap_block_state7_pp0_stage0_iter6() {
    ap_block_state7_pp0_stage0_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_mult_3lyr::thread_ap_block_state7_pp0_stage0_iter6_ignore_call25() {
    ap_block_state7_pp0_stage0_iter6_ignore_call25 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_mult_3lyr::thread_ap_block_state7_pp0_stage0_iter6_ignore_call7() {
    ap_block_state7_pp0_stage0_iter6_ignore_call7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_mult_3lyr::thread_ap_return_0() {
    ap_return_0 = add_ln703_297_fu_954_p2.read();
}

void dense_mult_3lyr::thread_ap_return_1() {
    ap_return_1 = add_ln703_305_fu_996_p2.read();
}

void dense_mult_3lyr::thread_ap_return_2() {
    ap_return_2 = add_ln703_313_fu_1022_p2.read();
}

void dense_mult_3lyr::thread_grp_dense_resource_0_0_2_fu_170_ap_ce() {
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001_ignoreCallOp15.read(), ap_const_boolean_0)) {
        grp_dense_resource_0_0_2_fu_170_ap_ce = ap_const_logic_1;
    } else {
        grp_dense_resource_0_0_2_fu_170_ap_ce = ap_const_logic_0;
    }
}

void dense_mult_3lyr::thread_grp_dense_resource_1_0_fu_158_ap_ce() {
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001_ignoreCallOp34.read(), ap_const_boolean_0)) {
        grp_dense_resource_1_0_fu_158_ap_ce = ap_const_logic_1;
    } else {
        grp_dense_resource_1_0_fu_158_ap_ce = ap_const_logic_0;
    }
}

void dense_mult_3lyr::thread_mul_ln1118_127_fu_1053_p0() {
    mul_ln1118_127_fu_1053_p0 =  (sc_lv<14>) (sext_ln1118_228_fu_357_p1.read());
}

void dense_mult_3lyr::thread_mul_ln1118_127_fu_1053_p1() {
    mul_ln1118_127_fu_1053_p1 =  (sc_lv<7>) (ap_const_lv21_1FFFCD);
}

void dense_mult_3lyr::thread_mul_ln1118_128_fu_1060_p0() {
    mul_ln1118_128_fu_1060_p0 =  (sc_lv<14>) (sext_ln1118_238_fu_476_p1.read());
}

void dense_mult_3lyr::thread_mul_ln1118_128_fu_1060_p1() {
    mul_ln1118_128_fu_1060_p1 =  (sc_lv<7>) (ap_const_lv21_1FFFDD);
}

void dense_mult_3lyr::thread_mul_ln1118_129_fu_1067_p1() {
    mul_ln1118_129_fu_1067_p1 =  (sc_lv<7>) (ap_const_lv21_1FFFDA);
}

void dense_mult_3lyr::thread_mul_ln1118_130_fu_1074_p1() {
    mul_ln1118_130_fu_1074_p1 =  (sc_lv<7>) (ap_const_lv21_23);
}

void dense_mult_3lyr::thread_mul_ln1118_131_fu_643_p0() {
    mul_ln1118_131_fu_643_p0 = sext_ln1118_235_fu_422_p0.read();
}

void dense_mult_3lyr::thread_mul_ln1118_131_fu_643_p2() {
    mul_ln1118_131_fu_643_p2 = (!mul_ln1118_131_fu_643_p0.read().is_01() || !ap_const_lv19_7FFF3.is_01())? sc_lv<19>(): sc_bigint<14>(mul_ln1118_131_fu_643_p0.read()) * sc_bigint<19>(ap_const_lv19_7FFF3);
}

void dense_mult_3lyr::thread_mul_ln1118_132_fu_1116_p1() {
    mul_ln1118_132_fu_1116_p1 =  (sc_lv<7>) (ap_const_lv21_27);
}

void dense_mult_3lyr::thread_mul_ln1118_133_fu_1081_p1() {
    mul_ln1118_133_fu_1081_p1 =  (sc_lv<6>) (ap_const_lv20_FFFED);
}

void dense_mult_3lyr::thread_mul_ln1118_134_fu_1088_p0() {
    mul_ln1118_134_fu_1088_p0 =  (sc_lv<14>) (sext_ln1118_228_fu_357_p1.read());
}

void dense_mult_3lyr::thread_mul_ln1118_134_fu_1088_p1() {
    mul_ln1118_134_fu_1088_p1 =  (sc_lv<7>) (ap_const_lv21_1FFFD2);
}

void dense_mult_3lyr::thread_mul_ln1118_135_fu_1095_p1() {
    mul_ln1118_135_fu_1095_p1 =  (sc_lv<6>) (ap_const_lv20_16);
}

void dense_mult_3lyr::thread_mul_ln1118_136_fu_1102_p0() {
    mul_ln1118_136_fu_1102_p0 =  (sc_lv<14>) (sext_ln1118_238_fu_476_p1.read());
}

void dense_mult_3lyr::thread_mul_ln1118_136_fu_1102_p1() {
    mul_ln1118_136_fu_1102_p1 =  (sc_lv<8>) (ap_const_lv21_1FFFA7);
}

void dense_mult_3lyr::thread_mul_ln1118_137_fu_1109_p1() {
    mul_ln1118_137_fu_1109_p1 =  (sc_lv<8>) (ap_const_lv21_5D);
}

void dense_mult_3lyr::thread_mul_ln1118_fu_1046_p1() {
    mul_ln1118_fu_1046_p1 =  (sc_lv<7>) (ap_const_lv21_2E);
}

void dense_mult_3lyr::thread_sext_ln1118_228_fu_357_p0() {
    sext_ln1118_228_fu_357_p0 = call_ret_relu_fu_200_ap_return_1.read();
}

void dense_mult_3lyr::thread_sext_ln1118_228_fu_357_p1() {
    sext_ln1118_228_fu_357_p1 = esl_sext<21,14>(sext_ln1118_228_fu_357_p0.read());
}

void dense_mult_3lyr::thread_sext_ln1118_230_fu_374_p0() {
    sext_ln1118_230_fu_374_p0 = call_ret_relu_fu_200_ap_return_2.read();
}

void dense_mult_3lyr::thread_sext_ln1118_230_fu_374_p1() {
    sext_ln1118_230_fu_374_p1 = esl_sext<18,14>(sext_ln1118_230_fu_374_p0.read());
}

void dense_mult_3lyr::thread_sext_ln1118_231_fu_378_p0() {
    sext_ln1118_231_fu_378_p0 = call_ret_relu_fu_200_ap_return_2.read();
}

void dense_mult_3lyr::thread_sext_ln1118_231_fu_378_p1() {
    sext_ln1118_231_fu_378_p1 = esl_sext<19,14>(sext_ln1118_231_fu_378_p0.read());
}

void dense_mult_3lyr::thread_sext_ln1118_232_fu_390_p1() {
    sext_ln1118_232_fu_390_p1 = esl_sext<19,18>(tmp_fu_382_p3.read());
}

void dense_mult_3lyr::thread_sext_ln1118_235_fu_422_p0() {
    sext_ln1118_235_fu_422_p0 = call_ret_relu_fu_200_ap_return_4.read();
}

void dense_mult_3lyr::thread_sext_ln1118_236_fu_434_p1() {
    sext_ln1118_236_fu_434_p1 = esl_sext<19,18>(shl_ln_fu_426_p3.read());
}

void dense_mult_3lyr::thread_sext_ln1118_237_fu_452_p1() {
    sext_ln1118_237_fu_452_p1 = esl_sext<19,16>(shl_ln1118_s_fu_444_p3.read());
}

void dense_mult_3lyr::thread_sext_ln1118_238_fu_476_p0() {
    sext_ln1118_238_fu_476_p0 = call_ret_relu_fu_200_ap_return_5.read();
}

void dense_mult_3lyr::thread_sext_ln1118_238_fu_476_p1() {
    sext_ln1118_238_fu_476_p1 = esl_sext<21,14>(sext_ln1118_238_fu_476_p0.read());
}

void dense_mult_3lyr::thread_sext_ln1118_240_fu_493_p0() {
    sext_ln1118_240_fu_493_p0 = call_ret_relu_fu_200_ap_return_6.read();
}

void dense_mult_3lyr::thread_sext_ln1118_240_fu_493_p1() {
    sext_ln1118_240_fu_493_p1 = esl_sext<17,14>(sext_ln1118_240_fu_493_p0.read());
}

void dense_mult_3lyr::thread_sext_ln1118_241_fu_497_p0() {
    sext_ln1118_241_fu_497_p0 = call_ret_relu_fu_200_ap_return_6.read();
}

void dense_mult_3lyr::thread_sext_ln1118_241_fu_497_p1() {
    sext_ln1118_241_fu_497_p1 = esl_sext<19,14>(sext_ln1118_241_fu_497_p0.read());
}

void dense_mult_3lyr::thread_sext_ln1118_242_fu_509_p1() {
    sext_ln1118_242_fu_509_p1 = esl_sext<19,18>(shl_ln1118_107_fu_501_p3.read());
}

void dense_mult_3lyr::thread_sext_ln1118_244_fu_903_p1() {
    sext_ln1118_244_fu_903_p1 = esl_sext<20,14>(data1_7_V_reg_1243.read());
}

void dense_mult_3lyr::thread_sext_ln1118_245_fu_913_p1() {
    sext_ln1118_245_fu_913_p1 = esl_sext<20,19>(shl_ln1118_108_fu_906_p3.read());
}

void dense_mult_3lyr::thread_sext_ln1118_246_fu_575_p1() {
    sext_ln1118_246_fu_575_p1 = esl_sext<20,19>(shl_ln1118_109_fu_567_p3.read());
}

void dense_mult_3lyr::thread_sext_ln1118_247_fu_587_p1() {
    sext_ln1118_247_fu_587_p1 = esl_sext<20,15>(shl_ln1118_110_fu_579_p3.read());
}

void dense_mult_3lyr::thread_sext_ln1118_248_fu_959_p1() {
    sext_ln1118_248_fu_959_p1 = esl_sext<8,7>(trunc_ln708_204_reg_1260.read());
}

void dense_mult_3lyr::thread_sext_ln1118_249_fu_681_p1() {
    sext_ln1118_249_fu_681_p1 = esl_sext<17,16>(shl_ln1118_111_fu_673_p3.read());
}

void dense_mult_3lyr::thread_sext_ln1118_250_fu_765_p1() {
    sext_ln1118_250_fu_765_p1 = esl_sext<18,17>(tmp_s_fu_757_p3.read());
}

void dense_mult_3lyr::thread_sext_ln1118_251_fu_802_p1() {
    sext_ln1118_251_fu_802_p1 = esl_sext<18,17>(shl_ln1118_112_fu_794_p3.read());
}

void dense_mult_3lyr::thread_sext_ln1118_252_fu_820_p1() {
    sext_ln1118_252_fu_820_p1 = esl_sext<18,15>(shl_ln1118_113_fu_812_p3.read());
}

void dense_mult_3lyr::thread_sext_ln1118_253_fu_410_p1() {
    sext_ln1118_253_fu_410_p1 = esl_sext<13,12>(tmp_47_fu_400_p4.read());
}

void dense_mult_3lyr::thread_sext_ln1118_254_fu_472_p1() {
    sext_ln1118_254_fu_472_p1 = esl_sext<13,12>(tmp_48_fu_462_p4.read());
}

void dense_mult_3lyr::thread_sext_ln1118_255_fu_707_p1() {
    sext_ln1118_255_fu_707_p1 = esl_sext<13,10>(tmp_50_fu_697_p4.read());
}

void dense_mult_3lyr::thread_sext_ln703_40_fu_551_p1() {
    sext_ln703_40_fu_551_p1 = esl_sext<14,13>(add_ln703_292_fu_545_p2.read());
}

void dense_mult_3lyr::thread_sext_ln703_41_fu_971_p1() {
    sext_ln703_41_fu_971_p1 = esl_sext<14,13>(add_ln703_301_reg_1270.read());
}

void dense_mult_3lyr::thread_sext_ln703_fu_980_p1() {
    sext_ln703_fu_980_p1 = esl_sext<14,8>(add_ln703_302_fu_974_p2.read());
}

void dense_mult_3lyr::thread_sext_ln708_123_fu_939_p1() {
    sext_ln708_123_fu_939_p1 = esl_sext<14,13>(trunc_ln708_199_fu_929_p4.read());
}

void dense_mult_3lyr::thread_sext_ln708_124_fu_607_p1() {
    sext_ln708_124_fu_607_p1 = esl_sext<14,13>(trunc_ln708_200_fu_597_p4.read());
}

void dense_mult_3lyr::thread_sext_ln708_125_fu_621_p1() {
    sext_ln708_125_fu_621_p1 = esl_sext<14,8>(trunc_ln708_201_fu_611_p4.read());
}

void dense_mult_3lyr::thread_sext_ln708_126_fu_659_p1() {
    sext_ln708_126_fu_659_p1 = esl_sext<13,12>(tmp_49_fu_649_p4.read());
}

void dense_mult_3lyr::thread_sext_ln708_127_fu_744_p1() {
    sext_ln708_127_fu_744_p1 = esl_sext<14,13>(trunc_ln708_206_fu_735_p4.read());
}

void dense_mult_3lyr::thread_sext_ln708_128_fu_1001_p1() {
    sext_ln708_128_fu_1001_p1 = esl_sext<14,11>(trunc_ln708_208_reg_1275.read());
}

void dense_mult_3lyr::thread_sext_ln708_129_fu_1004_p1() {
    sext_ln708_129_fu_1004_p1 = esl_sext<14,13>(trunc_ln708_209_reg_1280.read());
}

void dense_mult_3lyr::thread_sext_ln708_130_fu_840_p1() {
    sext_ln708_130_fu_840_p1 = esl_sext<14,11>(trunc_ln708_210_fu_830_p4.read());
}

void dense_mult_3lyr::thread_sext_ln708_131_fu_872_p1() {
    sext_ln708_131_fu_872_p1 = esl_sext<14,13>(trunc_ln708_213_fu_862_p4.read());
}

void dense_mult_3lyr::thread_sext_ln708_fu_535_p1() {
    sext_ln708_fu_535_p1 = esl_sext<14,12>(trunc_ln708_198_fu_525_p4.read());
}

void dense_mult_3lyr::thread_shl_ln1118_107_fu_501_p1() {
    shl_ln1118_107_fu_501_p1 = call_ret_relu_fu_200_ap_return_6.read();
}

void dense_mult_3lyr::thread_shl_ln1118_107_fu_501_p3() {
    shl_ln1118_107_fu_501_p3 = esl_concat<14,4>(shl_ln1118_107_fu_501_p1.read(), ap_const_lv4_0);
}

void dense_mult_3lyr::thread_shl_ln1118_108_fu_906_p3() {
    shl_ln1118_108_fu_906_p3 = esl_concat<14,5>(data1_7_V_reg_1243.read(), ap_const_lv5_0);
}

void dense_mult_3lyr::thread_shl_ln1118_109_fu_567_p1() {
    shl_ln1118_109_fu_567_p1 = call_ret_relu_fu_200_ap_return_0.read();
}

void dense_mult_3lyr::thread_shl_ln1118_109_fu_567_p3() {
    shl_ln1118_109_fu_567_p3 = esl_concat<14,5>(shl_ln1118_109_fu_567_p1.read(), ap_const_lv5_0);
}

void dense_mult_3lyr::thread_shl_ln1118_110_fu_579_p1() {
    shl_ln1118_110_fu_579_p1 = call_ret_relu_fu_200_ap_return_0.read();
}

void dense_mult_3lyr::thread_shl_ln1118_110_fu_579_p3() {
    shl_ln1118_110_fu_579_p3 = esl_concat<14,1>(shl_ln1118_110_fu_579_p1.read(), ap_const_lv1_0);
}

void dense_mult_3lyr::thread_shl_ln1118_111_fu_673_p1() {
    shl_ln1118_111_fu_673_p1 = call_ret_relu_fu_200_ap_return_6.read();
}

void dense_mult_3lyr::thread_shl_ln1118_111_fu_673_p3() {
    shl_ln1118_111_fu_673_p3 = esl_concat<14,2>(shl_ln1118_111_fu_673_p1.read(), ap_const_lv2_0);
}

void dense_mult_3lyr::thread_shl_ln1118_112_fu_794_p1() {
    shl_ln1118_112_fu_794_p1 = call_ret_relu_fu_200_ap_return_4.read();
}

void dense_mult_3lyr::thread_shl_ln1118_112_fu_794_p3() {
    shl_ln1118_112_fu_794_p3 = esl_concat<14,3>(shl_ln1118_112_fu_794_p1.read(), ap_const_lv3_0);
}

void dense_mult_3lyr::thread_shl_ln1118_113_fu_812_p1() {
    shl_ln1118_113_fu_812_p1 = call_ret_relu_fu_200_ap_return_4.read();
}

void dense_mult_3lyr::thread_shl_ln1118_113_fu_812_p3() {
    shl_ln1118_113_fu_812_p3 = esl_concat<14,1>(shl_ln1118_113_fu_812_p1.read(), ap_const_lv1_0);
}

void dense_mult_3lyr::thread_shl_ln1118_s_fu_444_p1() {
    shl_ln1118_s_fu_444_p1 = call_ret_relu_fu_200_ap_return_4.read();
}

void dense_mult_3lyr::thread_shl_ln1118_s_fu_444_p3() {
    shl_ln1118_s_fu_444_p3 = esl_concat<14,2>(shl_ln1118_s_fu_444_p1.read(), ap_const_lv2_0);
}

void dense_mult_3lyr::thread_shl_ln_fu_426_p1() {
    shl_ln_fu_426_p1 = call_ret_relu_fu_200_ap_return_4.read();
}

void dense_mult_3lyr::thread_shl_ln_fu_426_p3() {
    shl_ln_fu_426_p3 = esl_concat<14,4>(shl_ln_fu_426_p1.read(), ap_const_lv4_0);
}

void dense_mult_3lyr::thread_sub_ln1118_103_fu_394_p2() {
    sub_ln1118_103_fu_394_p2 = (!sext_ln1118_231_fu_378_p1.read().is_01() || !sext_ln1118_232_fu_390_p1.read().is_01())? sc_lv<19>(): (sc_bigint<19>(sext_ln1118_231_fu_378_p1.read()) - sc_bigint<19>(sext_ln1118_232_fu_390_p1.read()));
}

void dense_mult_3lyr::thread_sub_ln1118_104_fu_456_p2() {
    sub_ln1118_104_fu_456_p2 = (!sub_ln1118_fu_438_p2.read().is_01() || !sext_ln1118_237_fu_452_p1.read().is_01())? sc_lv<19>(): (sc_biguint<19>(sub_ln1118_fu_438_p2.read()) - sc_bigint<19>(sext_ln1118_237_fu_452_p1.read()));
}

void dense_mult_3lyr::thread_sub_ln1118_105_fu_513_p2() {
    sub_ln1118_105_fu_513_p2 = (!ap_const_lv19_0.is_01() || !sext_ln1118_242_fu_509_p1.read().is_01())? sc_lv<19>(): (sc_biguint<19>(ap_const_lv19_0) - sc_bigint<19>(sext_ln1118_242_fu_509_p1.read()));
}

void dense_mult_3lyr::thread_sub_ln1118_106_fu_519_p2() {
    sub_ln1118_106_fu_519_p2 = (!sub_ln1118_105_fu_513_p2.read().is_01() || !sext_ln1118_241_fu_497_p1.read().is_01())? sc_lv<19>(): (sc_biguint<19>(sub_ln1118_105_fu_513_p2.read()) - sc_bigint<19>(sext_ln1118_241_fu_497_p1.read()));
}

void dense_mult_3lyr::thread_sub_ln1118_107_fu_917_p2() {
    sub_ln1118_107_fu_917_p2 = (!ap_const_lv20_0.is_01() || !sext_ln1118_245_fu_913_p1.read().is_01())? sc_lv<20>(): (sc_biguint<20>(ap_const_lv20_0) - sc_bigint<20>(sext_ln1118_245_fu_913_p1.read()));
}

void dense_mult_3lyr::thread_sub_ln1118_108_fu_923_p2() {
    sub_ln1118_108_fu_923_p2 = (!sub_ln1118_107_fu_917_p2.read().is_01() || !sext_ln1118_244_fu_903_p1.read().is_01())? sc_lv<20>(): (sc_biguint<20>(sub_ln1118_107_fu_917_p2.read()) - sc_bigint<20>(sext_ln1118_244_fu_903_p1.read()));
}

void dense_mult_3lyr::thread_sub_ln1118_109_fu_591_p2() {
    sub_ln1118_109_fu_591_p2 = (!sext_ln1118_247_fu_587_p1.read().is_01() || !sext_ln1118_246_fu_575_p1.read().is_01())? sc_lv<20>(): (sc_bigint<20>(sext_ln1118_247_fu_587_p1.read()) - sc_bigint<20>(sext_ln1118_246_fu_575_p1.read()));
}

void dense_mult_3lyr::thread_sub_ln1118_110_fu_685_p2() {
    sub_ln1118_110_fu_685_p2 = (!ap_const_lv17_0.is_01() || !sext_ln1118_249_fu_681_p1.read().is_01())? sc_lv<17>(): (sc_biguint<17>(ap_const_lv17_0) - sc_bigint<17>(sext_ln1118_249_fu_681_p1.read()));
}

void dense_mult_3lyr::thread_sub_ln1118_111_fu_691_p2() {
    sub_ln1118_111_fu_691_p2 = (!sub_ln1118_110_fu_685_p2.read().is_01() || !sext_ln1118_240_fu_493_p1.read().is_01())? sc_lv<17>(): (sc_biguint<17>(sub_ln1118_110_fu_685_p2.read()) - sc_bigint<17>(sext_ln1118_240_fu_493_p1.read()));
}

void dense_mult_3lyr::thread_sub_ln1118_112_fu_769_p2() {
    sub_ln1118_112_fu_769_p2 = (!sext_ln1118_230_fu_374_p1.read().is_01() || !sext_ln1118_250_fu_765_p1.read().is_01())? sc_lv<18>(): (sc_bigint<18>(sext_ln1118_230_fu_374_p1.read()) - sc_bigint<18>(sext_ln1118_250_fu_765_p1.read()));
}

void dense_mult_3lyr::thread_sub_ln1118_113_fu_806_p2() {
    sub_ln1118_113_fu_806_p2 = (!ap_const_lv18_0.is_01() || !sext_ln1118_251_fu_802_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(ap_const_lv18_0) - sc_bigint<18>(sext_ln1118_251_fu_802_p1.read()));
}

void dense_mult_3lyr::thread_sub_ln1118_114_fu_824_p2() {
    sub_ln1118_114_fu_824_p2 = (!sub_ln1118_113_fu_806_p2.read().is_01() || !sext_ln1118_252_fu_820_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(sub_ln1118_113_fu_806_p2.read()) - sc_bigint<18>(sext_ln1118_252_fu_820_p1.read()));
}

void dense_mult_3lyr::thread_sub_ln1118_fu_438_p2() {
    sub_ln1118_fu_438_p2 = (!ap_const_lv19_0.is_01() || !sext_ln1118_236_fu_434_p1.read().is_01())? sc_lv<19>(): (sc_biguint<19>(ap_const_lv19_0) - sc_bigint<19>(sext_ln1118_236_fu_434_p1.read()));
}

void dense_mult_3lyr::thread_tmp_47_fu_400_p4() {
    tmp_47_fu_400_p4 = sub_ln1118_103_fu_394_p2.read().range(18, 7);
}

void dense_mult_3lyr::thread_tmp_48_fu_462_p4() {
    tmp_48_fu_462_p4 = sub_ln1118_104_fu_456_p2.read().range(18, 7);
}

void dense_mult_3lyr::thread_tmp_49_fu_649_p4() {
    tmp_49_fu_649_p4 = mul_ln1118_131_fu_643_p2.read().range(18, 7);
}

void dense_mult_3lyr::thread_tmp_50_fu_697_p4() {
    tmp_50_fu_697_p4 = sub_ln1118_111_fu_691_p2.read().range(16, 7);
}

void dense_mult_3lyr::thread_tmp_fu_382_p1() {
    tmp_fu_382_p1 = call_ret_relu_fu_200_ap_return_2.read();
}

void dense_mult_3lyr::thread_tmp_fu_382_p3() {
    tmp_fu_382_p3 = esl_concat<14,4>(tmp_fu_382_p1.read(), ap_const_lv4_0);
}

void dense_mult_3lyr::thread_tmp_s_fu_757_p1() {
    tmp_s_fu_757_p1 = call_ret_relu_fu_200_ap_return_2.read();
}

void dense_mult_3lyr::thread_tmp_s_fu_757_p3() {
    tmp_s_fu_757_p3 = esl_concat<14,3>(tmp_s_fu_757_p1.read(), ap_const_lv3_0);
}

void dense_mult_3lyr::thread_trunc_ln708_197_fu_480_p4() {
    trunc_ln708_197_fu_480_p4 = mul_ln1118_128_fu_1060_p2.read().range(20, 7);
}

void dense_mult_3lyr::thread_trunc_ln708_198_fu_525_p4() {
    trunc_ln708_198_fu_525_p4 = sub_ln1118_106_fu_519_p2.read().range(18, 7);
}

void dense_mult_3lyr::thread_trunc_ln708_199_fu_929_p4() {
    trunc_ln708_199_fu_929_p4 = sub_ln1118_108_fu_923_p2.read().range(19, 7);
}

void dense_mult_3lyr::thread_trunc_ln708_200_fu_597_p4() {
    trunc_ln708_200_fu_597_p4 = sub_ln1118_109_fu_591_p2.read().range(19, 7);
}

void dense_mult_3lyr::thread_trunc_ln708_201_fu_611_p1() {
    trunc_ln708_201_fu_611_p1 = call_ret_relu_fu_200_ap_return_1.read();
}

void dense_mult_3lyr::thread_trunc_ln708_201_fu_611_p4() {
    trunc_ln708_201_fu_611_p4 = trunc_ln708_201_fu_611_p1.read().range(13, 6);
}

void dense_mult_3lyr::thread_trunc_ln708_202_fu_625_p4() {
    trunc_ln708_202_fu_625_p4 = mul_ln1118_129_fu_1067_p2.read().range(20, 7);
}

void dense_mult_3lyr::thread_trunc_ln708_203_fu_634_p4() {
    trunc_ln708_203_fu_634_p4 = mul_ln1118_130_fu_1074_p2.read().range(20, 7);
}

void dense_mult_3lyr::thread_trunc_ln708_204_fu_663_p1() {
    trunc_ln708_204_fu_663_p1 = call_ret_relu_fu_200_ap_return_5.read();
}

void dense_mult_3lyr::thread_trunc_ln708_205_fu_962_p4() {
    trunc_ln708_205_fu_962_p4 = mul_ln1118_132_fu_1116_p2.read().range(20, 7);
}

void dense_mult_3lyr::thread_trunc_ln708_206_fu_735_p4() {
    trunc_ln708_206_fu_735_p4 = mul_ln1118_133_fu_1081_p2.read().range(19, 7);
}

void dense_mult_3lyr::thread_trunc_ln708_207_fu_748_p4() {
    trunc_ln708_207_fu_748_p4 = mul_ln1118_134_fu_1088_p2.read().range(20, 7);
}

void dense_mult_3lyr::thread_trunc_ln708_210_fu_830_p4() {
    trunc_ln708_210_fu_830_p4 = sub_ln1118_114_fu_824_p2.read().range(17, 7);
}

void dense_mult_3lyr::thread_trunc_ln708_211_fu_844_p4() {
    trunc_ln708_211_fu_844_p4 = mul_ln1118_136_fu_1102_p2.read().range(20, 7);
}

void dense_mult_3lyr::thread_trunc_ln708_212_fu_853_p4() {
    trunc_ln708_212_fu_853_p4 = mul_ln1118_137_fu_1109_p2.read().range(20, 7);
}

void dense_mult_3lyr::thread_trunc_ln708_213_fu_862_p1() {
    trunc_ln708_213_fu_862_p1 = call_ret_relu_fu_200_ap_return_7.read();
}

void dense_mult_3lyr::thread_trunc_ln708_213_fu_862_p4() {
    trunc_ln708_213_fu_862_p4 = trunc_ln708_213_fu_862_p1.read().range(13, 1);
}

void dense_mult_3lyr::thread_trunc_ln708_s_fu_361_p4() {
    trunc_ln708_s_fu_361_p4 = mul_ln1118_127_fu_1053_p2.read().range(20, 7);
}

void dense_mult_3lyr::thread_trunc_ln_fu_348_p4() {
    trunc_ln_fu_348_p4 = mul_ln1118_fu_1046_p2.read().range(20, 7);
}

}

