// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_resource_0_0_2 (
        ap_clk,
        ap_rst,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [13:0] data_0_V_read;
input  [13:0] data_1_V_read;
input  [13:0] data_2_V_read;
input  [13:0] data_3_V_read;
input  [13:0] data_4_V_read;
input  [13:0] data_5_V_read;
input  [13:0] data_6_V_read;
output  [13:0] ap_return_0;
output  [13:0] ap_return_1;
output  [13:0] ap_return_2;
output  [13:0] ap_return_3;
output  [13:0] ap_return_4;
output  [13:0] ap_return_5;
output  [13:0] ap_return_6;
output  [13:0] ap_return_7;
input   ap_ce;

reg[13:0] ap_return_0;
reg[13:0] ap_return_1;
reg[13:0] ap_return_2;
reg[13:0] ap_return_3;
reg[13:0] ap_return_4;
reg[13:0] ap_return_5;
reg[13:0] ap_return_6;
reg[13:0] ap_return_7;

reg  signed [13:0] data_6_V_read12_reg_2006;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
reg  signed [13:0] data_5_V_read11_reg_2017;
reg  signed [13:0] data_4_V_read_6_reg_2026;
wire   [13:0] add_ln703_219_fu_280_p2;
reg   [13:0] add_ln703_219_reg_2038;
wire   [13:0] add_ln703_226_fu_369_p2;
reg   [13:0] add_ln703_226_reg_2043;
wire   [13:0] add_ln703_233_fu_516_p2;
reg   [13:0] add_ln703_233_reg_2048;
wire   [13:0] add_ln703_239_fu_586_p2;
reg   [13:0] add_ln703_239_reg_2053;
wire   [13:0] add_ln703_246_fu_703_p2;
reg   [13:0] add_ln703_246_reg_2058;
wire   [13:0] add_ln703_253_fu_842_p2;
reg   [13:0] add_ln703_253_reg_2063;
wire   [13:0] add_ln703_260_fu_940_p2;
reg   [13:0] add_ln703_260_reg_2068;
wire   [13:0] add_ln703_267_fu_1022_p2;
reg   [13:0] add_ln703_267_reg_2073;
wire  signed [13:0] sext_ln1118_fu_192_p0;
wire    ap_block_pp0_stage0;
wire  signed [13:0] sext_ln1118_165_fu_196_p0;
wire  signed [20:0] mul_ln1118_fu_1824_p2;
wire  signed [13:0] sext_ln1118_166_fu_209_p0;
wire  signed [13:0] sext_ln1118_168_fu_217_p0;
wire  signed [13:0] sext_ln1118_169_fu_221_p0;
wire  signed [20:0] mul_ln1118_69_fu_1831_p2;
wire  signed [13:0] sext_ln1118_170_fu_234_p0;
wire  signed [13:0] sext_ln1118_171_fu_238_p0;
wire  signed [20:0] mul_ln1118_70_fu_1838_p2;
wire  signed [13:0] sext_ln1118_172_fu_251_p0;
wire  signed [13:0] sext_ln1118_173_fu_255_p0;
wire  signed [20:0] mul_ln1118_71_fu_1845_p2;
wire   [13:0] trunc_ln708_125_fu_225_p4;
wire   [13:0] trunc_ln_fu_200_p4;
wire   [13:0] trunc_ln708_127_fu_259_p4;
wire   [13:0] trunc_ln708_126_fu_242_p4;
wire   [13:0] add_ln703_fu_268_p2;
wire   [13:0] add_ln703_218_fu_274_p2;
wire  signed [13:0] shl_ln1118_82_fu_286_p1;
wire   [17:0] shl_ln1118_82_fu_286_p3;
wire  signed [13:0] shl_ln1118_83_fu_298_p1;
wire   [14:0] shl_ln1118_83_fu_298_p3;
wire  signed [18:0] sext_ln1118_181_fu_294_p1;
wire  signed [18:0] sext_ln1118_182_fu_306_p1;
wire   [18:0] add_ln1118_fu_310_p2;
wire   [11:0] trunc_ln708_146_fu_316_p4;
wire  signed [20:0] mul_ln1118_74_fu_1852_p2;
wire  signed [20:0] mul_ln1118_75_fu_1859_p2;
wire  signed [20:0] mul_ln1118_76_fu_1866_p2;
wire   [13:0] trunc_ln708_132_fu_330_p4;
wire  signed [13:0] sext_ln708_101_fu_326_p1;
wire   [13:0] trunc_ln708_134_fu_348_p4;
wire   [13:0] trunc_ln708_133_fu_339_p4;
wire   [13:0] add_ln703_224_fu_357_p2;
wire   [13:0] add_ln703_225_fu_363_p2;
wire  signed [13:0] tmp_fu_375_p1;
wire  signed [15:0] tmp_fu_375_p3;
wire  signed [16:0] sext_ln1118_165_fu_196_p1;
wire  signed [16:0] sext_ln1118_183_fu_383_p1;
wire   [16:0] sub_ln1118_75_fu_387_p2;
wire   [9:0] tmp_37_fu_393_p4;
wire  signed [13:0] tmp_8_fu_407_p1;
wire  signed [15:0] tmp_8_fu_407_p3;
wire  signed [16:0] sext_ln1118_168_fu_217_p1;
wire  signed [16:0] sext_ln1118_184_fu_415_p1;
wire   [16:0] sub_ln1118_76_fu_419_p2;
wire  signed [9:0] tmp_38_fu_425_p4;
wire  signed [13:0] shl_ln1118_84_fu_443_p1;
wire   [18:0] shl_ln1118_84_fu_443_p3;
wire  signed [13:0] shl_ln1118_85_fu_455_p1;
wire  signed [16:0] shl_ln1118_85_fu_455_p3;
wire  signed [19:0] sext_ln1118_187_fu_467_p1;
wire  signed [19:0] sext_ln1118_185_fu_451_p1;
wire   [19:0] sub_ln1118_77_fu_471_p2;
wire   [12:0] trunc_ln708_153_fu_477_p4;
wire  signed [20:0] mul_ln1118_82_fu_1873_p2;
wire  signed [10:0] sext_ln1118_217_fu_439_p1;
wire  signed [10:0] sext_ln1118_195_fu_403_p1;
wire   [10:0] add_ln703_231_fu_500_p2;
wire   [13:0] trunc_ln708_141_fu_491_p4;
wire  signed [13:0] sext_ln708_103_fu_487_p1;
wire  signed [13:0] sext_ln703_fu_506_p1;
wire   [13:0] add_ln703_232_fu_510_p2;
wire   [18:0] sub_ln1118_79_fu_522_p2;
wire  signed [18:0] sext_ln1118_190_fu_532_p1;
wire   [18:0] sub_ln1118_80_fu_536_p2;
wire   [11:0] trunc_ln708_158_fu_542_p4;
wire  signed [13:0] mul_ln1118_85_fu_556_p0;
wire   [18:0] mul_ln1118_85_fu_556_p2;
wire   [11:0] tmp_39_fu_562_p4;
wire  signed [12:0] sext_ln1118_218_fu_572_p1;
wire  signed [12:0] sext_ln1118_216_fu_435_p1;
wire   [12:0] add_ln703_238_fu_576_p2;
wire  signed [13:0] sext_ln708_106_fu_552_p1;
wire  signed [13:0] sext_ln703_28_fu_582_p1;
wire  signed [13:0] shl_ln1118_88_fu_592_p1;
wire   [19:0] shl_ln1118_88_fu_592_p3;
wire  signed [20:0] sext_ln1118_189_fu_528_p1;
wire  signed [20:0] sext_ln1118_193_fu_600_p1;
wire   [20:0] sub_ln1118_82_fu_604_p2;
wire   [16:0] sub_ln1118_83_fu_624_p2;
wire   [16:0] sub_ln1118_84_fu_630_p2;
wire   [9:0] trunc_ln708_162_fu_636_p4;
wire  signed [13:0] tmp_9_fu_650_p1;
wire   [15:0] tmp_9_fu_650_p3;
wire  signed [16:0] sext_ln1118_171_fu_238_p1;
wire  signed [16:0] sext_ln1118_196_fu_658_p1;
wire   [16:0] sub_ln1118_98_fu_662_p2;
wire   [9:0] trunc_ln708_163_fu_668_p4;
wire  signed [20:0] mul_ln1118_89_fu_1880_p2;
wire  signed [13:0] sext_ln708_108_fu_646_p1;
wire   [13:0] trunc_ln708_152_fu_610_p4;
wire   [13:0] trunc_ln708_155_fu_682_p4;
wire  signed [13:0] sext_ln708_109_fu_678_p1;
wire   [13:0] add_ln703_244_fu_691_p2;
wire   [13:0] add_ln703_245_fu_697_p2;
wire  signed [20:0] mul_ln1118_91_fu_1887_p2;
wire  signed [13:0] shl_ln1118_91_fu_718_p1;
wire   [16:0] shl_ln1118_91_fu_718_p3;
wire  signed [17:0] sext_ln1118_200_fu_726_p1;
wire  signed [17:0] sext_ln1118_169_fu_221_p1;
wire   [17:0] sub_ln1118_86_fu_730_p2;
wire   [10:0] trunc_ln708_169_fu_736_p4;
wire  signed [13:0] shl_ln1118_92_fu_750_p1;
wire   [14:0] shl_ln1118_92_fu_750_p3;
wire  signed [17:0] sext_ln1118_201_fu_758_p1;
wire  signed [17:0] sext_ln1118_186_fu_463_p1;
wire   [17:0] sub_ln1118_87_fu_762_p2;
wire   [10:0] tmp_41_fu_768_p4;
wire  signed [13:0] shl_ln1118_93_fu_782_p1;
wire   [17:0] shl_ln1118_93_fu_782_p3;
wire  signed [13:0] shl_ln1118_94_fu_794_p1;
wire   [15:0] shl_ln1118_94_fu_794_p3;
wire  signed [18:0] sext_ln1118_202_fu_790_p1;
wire  signed [18:0] sext_ln1118_203_fu_802_p1;
wire   [18:0] add_ln1118_15_fu_806_p2;
wire   [11:0] tmp_42_fu_812_p4;
wire  signed [13:0] sext_ln708_111_fu_746_p1;
wire   [13:0] trunc_ln708_159_fu_709_p4;
wire  signed [12:0] sext_ln1118_220_fu_822_p1;
wire  signed [12:0] sext_ln1118_219_fu_778_p1;
wire   [12:0] add_ln703_252_fu_832_p2;
wire   [13:0] add_ln703_251_fu_826_p2;
wire  signed [13:0] sext_ln703_31_fu_838_p1;
wire  signed [13:0] trunc_ln708_175_fu_848_p1;
wire   [12:0] trunc_ln708_175_fu_848_p4;
wire  signed [19:0] mul_ln1118_92_fu_1894_p2;
wire   [12:0] trunc_ln708_179_fu_862_p4;
wire  signed [20:0] mul_ln1118_93_fu_1901_p2;
wire  signed [13:0] shl_ln1118_99_fu_884_p1;
wire   [18:0] shl_ln1118_99_fu_884_p3;
wire  signed [13:0] shl_ln1118_100_fu_896_p1;
wire   [14:0] shl_ln1118_100_fu_896_p3;
wire  signed [19:0] sext_ln1118_208_fu_892_p1;
wire  signed [19:0] sext_ln1118_209_fu_904_p1;
wire   [19:0] sub_ln1118_92_fu_908_p2;
wire   [12:0] trunc_ln708_180_fu_914_p4;
wire  signed [13:0] sext_ln708_114_fu_871_p1;
wire  signed [13:0] sext_ln708_113_fu_858_p1;
wire  signed [13:0] sext_ln708_115_fu_924_p1;
wire   [13:0] trunc_ln708_168_fu_875_p4;
wire   [13:0] add_ln703_258_fu_928_p2;
wire   [13:0] add_ln703_259_fu_934_p2;
wire  signed [20:0] mul_ln1118_95_fu_1908_p2;
wire  signed [13:0] shl_ln1118_104_fu_955_p1;
wire   [17:0] shl_ln1118_104_fu_955_p3;
wire  signed [18:0] sext_ln1118_214_fu_963_p1;
wire  signed [18:0] sext_ln1118_194_fu_620_p1;
wire   [18:0] add_ln1118_17_fu_967_p2;
wire   [11:0] trunc_ln708_183_fu_973_p4;
wire  signed [13:0] trunc_ln708_184_fu_987_p1;
wire   [7:0] trunc_ln708_184_fu_987_p4;
wire  signed [20:0] mul_ln1118_96_fu_1915_p2;
wire  signed [13:0] sext_ln708_117_fu_983_p1;
wire   [13:0] trunc_ln708_173_fu_946_p4;
wire   [13:0] trunc_ln708_176_fu_1001_p4;
wire  signed [13:0] sext_ln708_118_fu_997_p1;
wire   [13:0] add_ln703_265_fu_1010_p2;
wire   [13:0] add_ln703_266_fu_1016_p2;
wire   [18:0] shl_ln_fu_1034_p3;
wire  signed [19:0] sext_ln1118_176_fu_1041_p1;
wire   [16:0] shl_ln1118_s_fu_1051_p3;
wire   [19:0] sub_ln1118_fu_1045_p2;
wire  signed [19:0] sext_ln1118_177_fu_1058_p1;
wire   [19:0] sub_ln1118_74_fu_1062_p2;
wire   [12:0] trunc_ln708_145_fu_1068_p4;
wire  signed [20:0] mul_ln1118_72_fu_1922_p2;
wire  signed [20:0] mul_ln1118_73_fu_1929_p2;
wire   [13:0] trunc_ln708_129_fu_1088_p4;
wire  signed [13:0] sext_ln708_fu_1078_p1;
wire   [13:0] trunc_ln708_130_fu_1100_p4;
wire   [13:0] add_ln703_220_fu_1109_p2;
wire   [13:0] add_ln703_221_fu_1115_p2;
wire   [13:0] add_ln703_222_fu_1121_p2;
wire  signed [19:0] mul_ln1118_77_fu_1936_p2;
wire   [12:0] trunc_ln708_147_fu_1132_p4;
wire  signed [20:0] mul_ln1118_78_fu_1943_p2;
wire  signed [20:0] mul_ln1118_79_fu_1950_p2;
wire   [13:0] trunc_ln708_136_fu_1145_p4;
wire  signed [13:0] sext_ln708_102_fu_1141_p1;
wire   [13:0] trunc_ln708_137_fu_1154_p4;
wire   [13:0] add_ln703_227_fu_1163_p2;
wire   [13:0] add_ln703_228_fu_1169_p2;
wire   [13:0] add_ln703_229_fu_1175_p2;
wire  signed [19:0] mul_ln1118_83_fu_1957_p2;
wire   [12:0] trunc_ln708_154_fu_1186_p4;
wire   [17:0] shl_ln1118_86_fu_1199_p3;
wire  signed [18:0] sext_ln1118_188_fu_1206_p1;
wire   [18:0] sub_ln1118_78_fu_1210_p2;
wire   [11:0] trunc_ln708_157_fu_1216_p4;
wire  signed [20:0] mul_ln1118_84_fu_1964_p2;
wire  signed [13:0] sext_ln708_105_fu_1226_p1;
wire  signed [13:0] sext_ln708_104_fu_1195_p1;
wire   [13:0] trunc_ln708_144_fu_1230_p4;
wire   [13:0] add_ln703_234_fu_1239_p2;
wire   [13:0] add_ln703_235_fu_1245_p2;
wire   [13:0] add_ln703_236_fu_1251_p2;
wire  signed [14:0] shl_ln1118_87_fu_1262_p3;
wire  signed [19:0] sext_ln1118_192_fu_1273_p1;
wire   [19:0] sub_ln1118_81_fu_1277_p2;
wire   [12:0] trunc_ln708_161_fu_1283_p4;
wire  signed [20:0] mul_ln1118_86_fu_1971_p2;
wire  signed [20:0] mul_ln1118_87_fu_1978_p2;
wire   [13:0] trunc_ln708_150_fu_1297_p4;
wire  signed [13:0] sext_ln708_107_fu_1293_p1;
wire   [13:0] trunc_ln708_151_fu_1306_p4;
wire   [13:0] add_ln703_240_fu_1315_p2;
wire   [13:0] add_ln703_241_fu_1321_p2;
wire   [13:0] add_ln703_242_fu_1327_p2;
wire  signed [20:0] mul_ln1118_90_fu_1985_p2;
wire  signed [18:0] sext_ln1118_179_fu_1085_p1;
wire   [18:0] add_ln1118_14_fu_1347_p2;
wire   [11:0] trunc_ln708_166_fu_1353_p4;
wire   [16:0] shl_ln1118_89_fu_1367_p3;
wire  signed [14:0] shl_ln1118_90_fu_1378_p3;
wire  signed [17:0] sext_ln1118_197_fu_1374_p1;
wire  signed [17:0] sext_ln1118_199_fu_1389_p1;
wire   [17:0] sub_ln1118_85_fu_1393_p2;
wire   [10:0] tmp_40_fu_1399_p4;
wire  signed [13:0] sext_ln708_110_fu_1363_p1;
wire   [13:0] trunc_ln708_156_fu_1338_p4;
wire  signed [11:0] sext_ln703_29_fu_1409_p1;
wire   [11:0] add_ln703_248_fu_1419_p2;
wire   [13:0] add_ln703_247_fu_1413_p2;
wire  signed [13:0] sext_ln703_30_fu_1425_p1;
wire   [13:0] add_ln703_249_fu_1429_p2;
wire   [17:0] shl_ln1118_95_fu_1440_p3;
wire  signed [18:0] sext_ln1118_191_fu_1269_p1;
wire  signed [18:0] sext_ln1118_204_fu_1447_p1;
wire   [18:0] sub_ln1118_88_fu_1451_p2;
wire   [11:0] trunc_ln708_174_fu_1457_p4;
wire   [19:0] shl_ln1118_96_fu_1471_p3;
wire  signed [20:0] sext_ln1118_205_fu_1478_p1;
wire   [15:0] shl_ln1118_97_fu_1488_p3;
wire   [20:0] sub_ln1118_89_fu_1482_p2;
wire  signed [20:0] sext_ln1118_206_fu_1495_p1;
wire   [20:0] sub_ln1118_90_fu_1499_p2;
wire   [19:0] shl_ln1118_98_fu_1515_p3;
wire  signed [20:0] sext_ln1118_207_fu_1522_p1;
wire  signed [20:0] sext_ln1118_180_fu_1097_p1;
wire   [20:0] sub_ln1118_91_fu_1526_p2;
wire   [13:0] trunc_ln708_164_fu_1505_p4;
wire  signed [13:0] sext_ln708_112_fu_1467_p1;
wire   [13:0] trunc_ln708_165_fu_1532_p4;
wire   [13:0] add_ln703_254_fu_1542_p2;
wire   [13:0] add_ln703_255_fu_1548_p2;
wire   [13:0] add_ln703_256_fu_1554_p2;
wire  signed [15:0] shl_ln1118_101_fu_1565_p3;
wire  signed [18:0] sext_ln1118_210_fu_1572_p1;
wire   [18:0] add_ln1118_16_fu_1580_p2;
wire   [11:0] trunc_ln708_181_fu_1586_p4;
wire  signed [20:0] mul_ln1118_94_fu_1992_p2;
wire   [17:0] shl_ln1118_102_fu_1609_p3;
wire  signed [18:0] sext_ln1118_212_fu_1616_p1;
wire   [15:0] shl_ln1118_103_fu_1626_p3;
wire   [18:0] sub_ln1118_93_fu_1620_p2;
wire  signed [18:0] sext_ln1118_213_fu_1633_p1;
wire   [18:0] sub_ln1118_94_fu_1637_p2;
wire   [11:0] tmp_43_fu_1643_p4;
wire   [13:0] trunc_ln708_171_fu_1600_p4;
wire  signed [13:0] sext_ln708_116_fu_1596_p1;
wire  signed [12:0] sext_ln703_32_fu_1653_p1;
wire   [12:0] add_ln703_262_fu_1663_p2;
wire   [13:0] add_ln703_261_fu_1657_p2;
wire  signed [13:0] sext_ln703_33_fu_1669_p1;
wire   [13:0] add_ln703_263_fu_1673_p2;
wire   [20:0] shl_ln1118_105_fu_1684_p3;
wire  signed [20:0] sext_ln1118_211_fu_1576_p1;
wire   [20:0] sub_ln1118_95_fu_1691_p2;
wire  signed [20:0] mul_ln1118_97_fu_1999_p2;
wire   [18:0] shl_ln1118_106_fu_1716_p3;
wire  signed [19:0] sext_ln1118_215_fu_1723_p1;
wire   [19:0] sub_ln1118_96_fu_1727_p2;
wire  signed [19:0] sext_ln1118_198_fu_1385_p1;
wire   [19:0] sub_ln1118_97_fu_1733_p2;
wire   [12:0] trunc_ln708_185_fu_1739_p4;
wire   [13:0] trunc_ln708_178_fu_1707_p4;
wire   [13:0] trunc_ln708_177_fu_1697_p4;
wire  signed [13:0] sext_ln708_119_fu_1749_p1;
wire   [13:0] add_ln703_268_fu_1753_p2;
wire   [13:0] add_ln703_269_fu_1759_p2;
wire   [13:0] add_ln703_270_fu_1765_p2;
wire   [13:0] add_ln703_230_fu_1127_p2;
wire   [13:0] add_ln703_237_fu_1181_p2;
wire   [13:0] add_ln703_243_fu_1257_p2;
wire   [13:0] add_ln703_250_fu_1333_p2;
wire   [13:0] add_ln703_257_fu_1435_p2;
wire   [13:0] add_ln703_264_fu_1560_p2;
wire   [13:0] add_ln703_271_fu_1679_p2;
wire   [13:0] add_ln703_272_fu_1771_p2;
wire  signed [13:0] mul_ln1118_fu_1824_p0;
wire  signed [20:0] sext_ln1118_fu_192_p1;
wire  signed [6:0] mul_ln1118_fu_1824_p1;
wire  signed [13:0] mul_ln1118_69_fu_1831_p0;
wire  signed [20:0] sext_ln1118_166_fu_209_p1;
wire  signed [6:0] mul_ln1118_69_fu_1831_p1;
wire  signed [13:0] mul_ln1118_70_fu_1838_p0;
wire  signed [20:0] sext_ln1118_170_fu_234_p1;
wire   [6:0] mul_ln1118_70_fu_1838_p1;
wire  signed [13:0] mul_ln1118_71_fu_1845_p0;
wire  signed [20:0] sext_ln1118_172_fu_251_p1;
wire   [6:0] mul_ln1118_71_fu_1845_p1;
wire  signed [13:0] mul_ln1118_74_fu_1852_p0;
wire   [6:0] mul_ln1118_74_fu_1852_p1;
wire  signed [13:0] mul_ln1118_75_fu_1859_p0;
wire   [8:0] mul_ln1118_75_fu_1859_p1;
wire  signed [13:0] mul_ln1118_76_fu_1866_p0;
wire   [6:0] mul_ln1118_76_fu_1866_p1;
wire  signed [13:0] mul_ln1118_82_fu_1873_p0;
wire   [7:0] mul_ln1118_82_fu_1873_p1;
wire  signed [13:0] mul_ln1118_89_fu_1880_p0;
wire   [6:0] mul_ln1118_89_fu_1880_p1;
wire  signed [13:0] mul_ln1118_91_fu_1887_p0;
wire  signed [7:0] mul_ln1118_91_fu_1887_p1;
wire   [5:0] mul_ln1118_92_fu_1894_p1;
wire  signed [13:0] mul_ln1118_93_fu_1901_p0;
wire  signed [8:0] mul_ln1118_93_fu_1901_p1;
wire  signed [13:0] mul_ln1118_95_fu_1908_p0;
wire  signed [7:0] mul_ln1118_95_fu_1908_p1;
wire  signed [13:0] mul_ln1118_96_fu_1915_p0;
wire  signed [7:0] mul_ln1118_96_fu_1915_p1;
wire  signed [13:0] mul_ln1118_72_fu_1922_p0;
wire  signed [20:0] sext_ln1118_178_fu_1082_p1;
wire  signed [7:0] mul_ln1118_72_fu_1922_p1;
wire  signed [13:0] mul_ln1118_73_fu_1929_p0;
wire   [7:0] mul_ln1118_73_fu_1929_p1;
wire  signed [13:0] mul_ln1118_77_fu_1936_p0;
wire  signed [19:0] sext_ln1118_175_fu_1031_p1;
wire   [5:0] mul_ln1118_77_fu_1936_p1;
wire  signed [13:0] mul_ln1118_78_fu_1943_p0;
wire  signed [7:0] mul_ln1118_78_fu_1943_p1;
wire  signed [13:0] mul_ln1118_79_fu_1950_p0;
wire   [7:0] mul_ln1118_79_fu_1950_p1;
wire  signed [13:0] mul_ln1118_83_fu_1957_p0;
wire   [5:0] mul_ln1118_83_fu_1957_p1;
wire  signed [13:0] mul_ln1118_84_fu_1964_p0;
wire   [7:0] mul_ln1118_84_fu_1964_p1;
wire  signed [13:0] mul_ln1118_86_fu_1971_p0;
wire  signed [8:0] mul_ln1118_86_fu_1971_p1;
wire  signed [13:0] mul_ln1118_87_fu_1978_p0;
wire   [8:0] mul_ln1118_87_fu_1978_p1;
wire   [6:0] mul_ln1118_90_fu_1985_p1;
wire  signed [13:0] mul_ln1118_94_fu_1992_p0;
wire  signed [6:0] mul_ln1118_94_fu_1992_p1;
wire  signed [13:0] mul_ln1118_97_fu_1999_p0;
wire   [6:0] mul_ln1118_97_fu_1999_p1;
reg    ap_ce_reg;
reg   [13:0] ap_return_0_int_reg;
reg   [13:0] ap_return_1_int_reg;
reg   [13:0] ap_return_2_int_reg;
reg   [13:0] ap_return_3_int_reg;
reg   [13:0] ap_return_4_int_reg;
reg   [13:0] ap_return_5_int_reg;
reg   [13:0] ap_return_6_int_reg;
reg   [13:0] ap_return_7_int_reg;

example_mul_mul_1ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1ocq_U1712(
    .din0(mul_ln1118_fu_1824_p0),
    .din1(mul_ln1118_fu_1824_p1),
    .dout(mul_ln1118_fu_1824_p2)
);

example_mul_mul_1ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1ocq_U1713(
    .din0(mul_ln1118_69_fu_1831_p0),
    .din1(mul_ln1118_69_fu_1831_p1),
    .dout(mul_ln1118_69_fu_1831_p2)
);

example_mul_mul_1ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1ncg_U1714(
    .din0(mul_ln1118_70_fu_1838_p0),
    .din1(mul_ln1118_70_fu_1838_p1),
    .dout(mul_ln1118_70_fu_1838_p2)
);

example_mul_mul_1ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1ncg_U1715(
    .din0(mul_ln1118_71_fu_1845_p0),
    .din1(mul_ln1118_71_fu_1845_p1),
    .dout(mul_ln1118_71_fu_1845_p2)
);

example_mul_mul_1ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1ncg_U1716(
    .din0(mul_ln1118_74_fu_1852_p0),
    .din1(mul_ln1118_74_fu_1852_p1),
    .dout(mul_ln1118_74_fu_1852_p2)
);

example_mul_mul_1udo #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1udo_U1717(
    .din0(mul_ln1118_75_fu_1859_p0),
    .din1(mul_ln1118_75_fu_1859_p1),
    .dout(mul_ln1118_75_fu_1859_p2)
);

example_mul_mul_1ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1ncg_U1718(
    .din0(mul_ln1118_76_fu_1866_p0),
    .din1(mul_ln1118_76_fu_1866_p1),
    .dout(mul_ln1118_76_fu_1866_p2)
);

example_mul_mul_1wdI #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1wdI_U1719(
    .din0(mul_ln1118_82_fu_1873_p0),
    .din1(mul_ln1118_82_fu_1873_p1),
    .dout(mul_ln1118_82_fu_1873_p2)
);

example_mul_mul_1ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1ncg_U1720(
    .din0(mul_ln1118_89_fu_1880_p0),
    .din1(mul_ln1118_89_fu_1880_p1),
    .dout(mul_ln1118_89_fu_1880_p2)
);

example_mul_mul_1sc4 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1sc4_U1721(
    .din0(mul_ln1118_91_fu_1887_p0),
    .din1(mul_ln1118_91_fu_1887_p1),
    .dout(mul_ln1118_91_fu_1887_p2)
);

example_mul_mul_1tde #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 20 ))
example_mul_mul_1tde_U1722(
    .din0(data_1_V_read),
    .din1(mul_ln1118_92_fu_1894_p1),
    .dout(mul_ln1118_92_fu_1894_p2)
);

example_mul_mul_1qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1qcK_U1723(
    .din0(mul_ln1118_93_fu_1901_p0),
    .din1(mul_ln1118_93_fu_1901_p1),
    .dout(mul_ln1118_93_fu_1901_p2)
);

example_mul_mul_1sc4 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1sc4_U1724(
    .din0(mul_ln1118_95_fu_1908_p0),
    .din1(mul_ln1118_95_fu_1908_p1),
    .dout(mul_ln1118_95_fu_1908_p2)
);

example_mul_mul_1sc4 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1sc4_U1725(
    .din0(mul_ln1118_96_fu_1915_p0),
    .din1(mul_ln1118_96_fu_1915_p1),
    .dout(mul_ln1118_96_fu_1915_p2)
);

example_mul_mul_1sc4 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1sc4_U1726(
    .din0(mul_ln1118_72_fu_1922_p0),
    .din1(mul_ln1118_72_fu_1922_p1),
    .dout(mul_ln1118_72_fu_1922_p2)
);

example_mul_mul_1wdI #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1wdI_U1727(
    .din0(mul_ln1118_73_fu_1929_p0),
    .din1(mul_ln1118_73_fu_1929_p1),
    .dout(mul_ln1118_73_fu_1929_p2)
);

example_mul_mul_1tde #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 20 ))
example_mul_mul_1tde_U1728(
    .din0(mul_ln1118_77_fu_1936_p0),
    .din1(mul_ln1118_77_fu_1936_p1),
    .dout(mul_ln1118_77_fu_1936_p2)
);

example_mul_mul_1sc4 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1sc4_U1729(
    .din0(mul_ln1118_78_fu_1943_p0),
    .din1(mul_ln1118_78_fu_1943_p1),
    .dout(mul_ln1118_78_fu_1943_p2)
);

example_mul_mul_1wdI #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1wdI_U1730(
    .din0(mul_ln1118_79_fu_1950_p0),
    .din1(mul_ln1118_79_fu_1950_p1),
    .dout(mul_ln1118_79_fu_1950_p2)
);

example_mul_mul_1tde #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 20 ))
example_mul_mul_1tde_U1731(
    .din0(mul_ln1118_83_fu_1957_p0),
    .din1(mul_ln1118_83_fu_1957_p1),
    .dout(mul_ln1118_83_fu_1957_p2)
);

example_mul_mul_1wdI #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1wdI_U1732(
    .din0(mul_ln1118_84_fu_1964_p0),
    .din1(mul_ln1118_84_fu_1964_p1),
    .dout(mul_ln1118_84_fu_1964_p2)
);

example_mul_mul_1qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1qcK_U1733(
    .din0(mul_ln1118_86_fu_1971_p0),
    .din1(mul_ln1118_86_fu_1971_p1),
    .dout(mul_ln1118_86_fu_1971_p2)
);

example_mul_mul_1udo #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1udo_U1734(
    .din0(mul_ln1118_87_fu_1978_p0),
    .din1(mul_ln1118_87_fu_1978_p1),
    .dout(mul_ln1118_87_fu_1978_p2)
);

example_mul_mul_1ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1ncg_U1735(
    .din0(data_4_V_read_6_reg_2026),
    .din1(mul_ln1118_90_fu_1985_p1),
    .dout(mul_ln1118_90_fu_1985_p2)
);

example_mul_mul_1ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1ocq_U1736(
    .din0(mul_ln1118_94_fu_1992_p0),
    .din1(mul_ln1118_94_fu_1992_p1),
    .dout(mul_ln1118_94_fu_1992_p2)
);

example_mul_mul_1ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1ncg_U1737(
    .din0(mul_ln1118_97_fu_1999_p0),
    .din1(mul_ln1118_97_fu_1999_p1),
    .dout(mul_ln1118_97_fu_1999_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1))) begin
        add_ln703_219_reg_2038 <= add_ln703_219_fu_280_p2;
        add_ln703_226_reg_2043 <= add_ln703_226_fu_369_p2;
        add_ln703_233_reg_2048 <= add_ln703_233_fu_516_p2;
        add_ln703_239_reg_2053 <= add_ln703_239_fu_586_p2;
        add_ln703_246_reg_2058 <= add_ln703_246_fu_703_p2;
        add_ln703_253_reg_2063 <= add_ln703_253_fu_842_p2;
        add_ln703_260_reg_2068 <= add_ln703_260_fu_940_p2;
        add_ln703_267_reg_2073 <= add_ln703_267_fu_1022_p2;
        data_4_V_read_6_reg_2026 <= data_4_V_read;
        data_5_V_read11_reg_2017 <= data_5_V_read;
        data_6_V_read12_reg_2006 <= data_6_V_read;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= add_ln703_230_fu_1127_p2;
        ap_return_1_int_reg <= add_ln703_237_fu_1181_p2;
        ap_return_2_int_reg <= add_ln703_243_fu_1257_p2;
        ap_return_3_int_reg <= add_ln703_250_fu_1333_p2;
        ap_return_4_int_reg <= add_ln703_257_fu_1435_p2;
        ap_return_5_int_reg <= add_ln703_264_fu_1560_p2;
        ap_return_6_int_reg <= add_ln703_271_fu_1679_p2;
        ap_return_7_int_reg <= add_ln703_272_fu_1771_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = add_ln703_230_fu_1127_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = add_ln703_237_fu_1181_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = add_ln703_243_fu_1257_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = add_ln703_250_fu_1333_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_4 = ap_return_4_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_4 = add_ln703_257_fu_1435_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_5 = ap_return_5_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_5 = add_ln703_264_fu_1560_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_6 = ap_return_6_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_6 = add_ln703_271_fu_1679_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_7 = ap_return_7_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_7 = add_ln703_272_fu_1771_p2;
    end
end

assign add_ln1118_14_fu_1347_p2 = ($signed(sext_ln1118_179_fu_1085_p1) + $signed(sext_ln1118_188_fu_1206_p1));

assign add_ln1118_15_fu_806_p2 = ($signed(sext_ln1118_202_fu_790_p1) + $signed(sext_ln1118_203_fu_802_p1));

assign add_ln1118_16_fu_1580_p2 = ($signed(sext_ln1118_204_fu_1447_p1) + $signed(sext_ln1118_210_fu_1572_p1));

assign add_ln1118_17_fu_967_p2 = ($signed(sext_ln1118_214_fu_963_p1) + $signed(sext_ln1118_194_fu_620_p1));

assign add_ln1118_fu_310_p2 = ($signed(sext_ln1118_181_fu_294_p1) + $signed(sext_ln1118_182_fu_306_p1));

assign add_ln703_218_fu_274_p2 = (trunc_ln708_127_fu_259_p4 + trunc_ln708_126_fu_242_p4);

assign add_ln703_219_fu_280_p2 = (add_ln703_fu_268_p2 + add_ln703_218_fu_274_p2);

assign add_ln703_220_fu_1109_p2 = ($signed(trunc_ln708_129_fu_1088_p4) + $signed(sext_ln708_fu_1078_p1));

assign add_ln703_221_fu_1115_p2 = ($signed(trunc_ln708_130_fu_1100_p4) + $signed(14'd16361));

assign add_ln703_222_fu_1121_p2 = (add_ln703_220_fu_1109_p2 + add_ln703_221_fu_1115_p2);

assign add_ln703_224_fu_357_p2 = ($signed(trunc_ln708_132_fu_330_p4) + $signed(sext_ln708_101_fu_326_p1));

assign add_ln703_225_fu_363_p2 = (trunc_ln708_134_fu_348_p4 + trunc_ln708_133_fu_339_p4);

assign add_ln703_226_fu_369_p2 = (add_ln703_224_fu_357_p2 + add_ln703_225_fu_363_p2);

assign add_ln703_227_fu_1163_p2 = ($signed(trunc_ln708_136_fu_1145_p4) + $signed(sext_ln708_102_fu_1141_p1));

assign add_ln703_228_fu_1169_p2 = (trunc_ln708_137_fu_1154_p4 + 14'd29);

assign add_ln703_229_fu_1175_p2 = (add_ln703_227_fu_1163_p2 + add_ln703_228_fu_1169_p2);

assign add_ln703_230_fu_1127_p2 = (add_ln703_219_reg_2038 + add_ln703_222_fu_1121_p2);

assign add_ln703_231_fu_500_p2 = ($signed(sext_ln1118_217_fu_439_p1) + $signed(sext_ln1118_195_fu_403_p1));

assign add_ln703_232_fu_510_p2 = ($signed(trunc_ln708_141_fu_491_p4) + $signed(sext_ln708_103_fu_487_p1));

assign add_ln703_233_fu_516_p2 = ($signed(sext_ln703_fu_506_p1) + $signed(add_ln703_232_fu_510_p2));

assign add_ln703_234_fu_1239_p2 = ($signed(sext_ln708_105_fu_1226_p1) + $signed(sext_ln708_104_fu_1195_p1));

assign add_ln703_235_fu_1245_p2 = ($signed(trunc_ln708_144_fu_1230_p4) + $signed(14'd16326));

assign add_ln703_236_fu_1251_p2 = (add_ln703_234_fu_1239_p2 + add_ln703_235_fu_1245_p2);

assign add_ln703_237_fu_1181_p2 = (add_ln703_226_reg_2043 + add_ln703_229_fu_1175_p2);

assign add_ln703_238_fu_576_p2 = ($signed(sext_ln1118_218_fu_572_p1) + $signed(sext_ln1118_216_fu_435_p1));

assign add_ln703_239_fu_586_p2 = ($signed(sext_ln708_106_fu_552_p1) + $signed(sext_ln703_28_fu_582_p1));

assign add_ln703_240_fu_1315_p2 = ($signed(trunc_ln708_150_fu_1297_p4) + $signed(sext_ln708_107_fu_1293_p1));

assign add_ln703_241_fu_1321_p2 = ($signed(trunc_ln708_151_fu_1306_p4) + $signed(14'd16272));

assign add_ln703_242_fu_1327_p2 = (add_ln703_240_fu_1315_p2 + add_ln703_241_fu_1321_p2);

assign add_ln703_243_fu_1257_p2 = (add_ln703_233_reg_2048 + add_ln703_236_fu_1251_p2);

assign add_ln703_244_fu_691_p2 = ($signed(sext_ln708_108_fu_646_p1) + $signed(trunc_ln708_152_fu_610_p4));

assign add_ln703_245_fu_697_p2 = ($signed(trunc_ln708_155_fu_682_p4) + $signed(sext_ln708_109_fu_678_p1));

assign add_ln703_246_fu_703_p2 = (add_ln703_244_fu_691_p2 + add_ln703_245_fu_697_p2);

assign add_ln703_247_fu_1413_p2 = ($signed(sext_ln708_110_fu_1363_p1) + $signed(trunc_ln708_156_fu_1338_p4));

assign add_ln703_248_fu_1419_p2 = ($signed(sext_ln703_29_fu_1409_p1) + $signed(12'd4023));

assign add_ln703_249_fu_1429_p2 = ($signed(add_ln703_247_fu_1413_p2) + $signed(sext_ln703_30_fu_1425_p1));

assign add_ln703_250_fu_1333_p2 = (add_ln703_239_reg_2053 + add_ln703_242_fu_1327_p2);

assign add_ln703_251_fu_826_p2 = ($signed(sext_ln708_111_fu_746_p1) + $signed(trunc_ln708_159_fu_709_p4));

assign add_ln703_252_fu_832_p2 = ($signed(sext_ln1118_220_fu_822_p1) + $signed(sext_ln1118_219_fu_778_p1));

assign add_ln703_253_fu_842_p2 = ($signed(add_ln703_251_fu_826_p2) + $signed(sext_ln703_31_fu_838_p1));

assign add_ln703_254_fu_1542_p2 = ($signed(trunc_ln708_164_fu_1505_p4) + $signed(sext_ln708_112_fu_1467_p1));

assign add_ln703_255_fu_1548_p2 = ($signed(trunc_ln708_165_fu_1532_p4) + $signed(14'd16372));

assign add_ln703_256_fu_1554_p2 = (add_ln703_254_fu_1542_p2 + add_ln703_255_fu_1548_p2);

assign add_ln703_257_fu_1435_p2 = (add_ln703_246_reg_2058 + add_ln703_249_fu_1429_p2);

assign add_ln703_258_fu_928_p2 = ($signed(sext_ln708_114_fu_871_p1) + $signed(sext_ln708_113_fu_858_p1));

assign add_ln703_259_fu_934_p2 = ($signed(sext_ln708_115_fu_924_p1) + $signed(trunc_ln708_168_fu_875_p4));

assign add_ln703_260_fu_940_p2 = (add_ln703_258_fu_928_p2 + add_ln703_259_fu_934_p2);

assign add_ln703_261_fu_1657_p2 = ($signed(trunc_ln708_171_fu_1600_p4) + $signed(sext_ln708_116_fu_1596_p1));

assign add_ln703_262_fu_1663_p2 = ($signed(sext_ln703_32_fu_1653_p1) + $signed(13'd8190));

assign add_ln703_263_fu_1673_p2 = ($signed(add_ln703_261_fu_1657_p2) + $signed(sext_ln703_33_fu_1669_p1));

assign add_ln703_264_fu_1560_p2 = (add_ln703_253_reg_2063 + add_ln703_256_fu_1554_p2);

assign add_ln703_265_fu_1010_p2 = ($signed(sext_ln708_117_fu_983_p1) + $signed(trunc_ln708_173_fu_946_p4));

assign add_ln703_266_fu_1016_p2 = ($signed(trunc_ln708_176_fu_1001_p4) + $signed(sext_ln708_118_fu_997_p1));

assign add_ln703_267_fu_1022_p2 = (add_ln703_265_fu_1010_p2 + add_ln703_266_fu_1016_p2);

assign add_ln703_268_fu_1753_p2 = (trunc_ln708_178_fu_1707_p4 + trunc_ln708_177_fu_1697_p4);

assign add_ln703_269_fu_1759_p2 = ($signed(sext_ln708_119_fu_1749_p1) + $signed(14'd16366));

assign add_ln703_270_fu_1765_p2 = (add_ln703_268_fu_1753_p2 + add_ln703_269_fu_1759_p2);

assign add_ln703_271_fu_1679_p2 = (add_ln703_260_reg_2068 + add_ln703_263_fu_1673_p2);

assign add_ln703_272_fu_1771_p2 = (add_ln703_267_reg_2073 + add_ln703_270_fu_1765_p2);

assign add_ln703_fu_268_p2 = (trunc_ln708_125_fu_225_p4 + trunc_ln_fu_200_p4);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign mul_ln1118_69_fu_1831_p0 = sext_ln1118_166_fu_209_p1;

assign mul_ln1118_69_fu_1831_p1 = 21'd2097110;

assign mul_ln1118_70_fu_1838_p0 = sext_ln1118_170_fu_234_p1;

assign mul_ln1118_70_fu_1838_p1 = 21'd39;

assign mul_ln1118_71_fu_1845_p0 = sext_ln1118_172_fu_251_p1;

assign mul_ln1118_71_fu_1845_p1 = 21'd39;

assign mul_ln1118_72_fu_1922_p0 = sext_ln1118_178_fu_1082_p1;

assign mul_ln1118_72_fu_1922_p1 = 21'd2097058;

assign mul_ln1118_73_fu_1929_p0 = sext_ln1118_180_fu_1097_p1;

assign mul_ln1118_73_fu_1929_p1 = 21'd90;

assign mul_ln1118_74_fu_1852_p0 = sext_ln1118_166_fu_209_p1;

assign mul_ln1118_74_fu_1852_p1 = 21'd54;

assign mul_ln1118_75_fu_1859_p0 = sext_ln1118_170_fu_234_p1;

assign mul_ln1118_75_fu_1859_p1 = 21'd146;

assign mul_ln1118_76_fu_1866_p0 = sext_ln1118_172_fu_251_p1;

assign mul_ln1118_76_fu_1866_p1 = 21'd42;

assign mul_ln1118_77_fu_1936_p0 = sext_ln1118_175_fu_1031_p1;

assign mul_ln1118_77_fu_1936_p1 = 20'd21;

assign mul_ln1118_78_fu_1943_p0 = sext_ln1118_178_fu_1082_p1;

assign mul_ln1118_78_fu_1943_p1 = 21'd2097081;

assign mul_ln1118_79_fu_1950_p0 = sext_ln1118_180_fu_1097_p1;

assign mul_ln1118_79_fu_1950_p1 = 21'd97;

assign mul_ln1118_82_fu_1873_p0 = sext_ln1118_172_fu_251_p1;

assign mul_ln1118_82_fu_1873_p1 = 21'd76;

assign mul_ln1118_83_fu_1957_p0 = sext_ln1118_175_fu_1031_p1;

assign mul_ln1118_83_fu_1957_p1 = 20'd29;

assign mul_ln1118_84_fu_1964_p0 = sext_ln1118_180_fu_1097_p1;

assign mul_ln1118_84_fu_1964_p1 = 21'd99;

assign mul_ln1118_85_fu_556_p0 = sext_ln1118_173_fu_255_p0;

assign mul_ln1118_85_fu_556_p2 = ($signed(mul_ln1118_85_fu_556_p0) * $signed('hB));

assign mul_ln1118_86_fu_1971_p0 = sext_ln1118_178_fu_1082_p1;

assign mul_ln1118_86_fu_1971_p1 = 21'd2096964;

assign mul_ln1118_87_fu_1978_p0 = sext_ln1118_180_fu_1097_p1;

assign mul_ln1118_87_fu_1978_p1 = 21'd139;

assign mul_ln1118_89_fu_1880_p0 = sext_ln1118_172_fu_251_p1;

assign mul_ln1118_89_fu_1880_p1 = 21'd50;

assign mul_ln1118_90_fu_1985_p1 = 21'd41;

assign mul_ln1118_91_fu_1887_p0 = sext_ln1118_fu_192_p1;

assign mul_ln1118_91_fu_1887_p1 = 21'd2097083;

assign mul_ln1118_92_fu_1894_p1 = 20'd29;

assign mul_ln1118_93_fu_1901_p0 = sext_ln1118_170_fu_234_p1;

assign mul_ln1118_93_fu_1901_p1 = 21'd2096929;

assign mul_ln1118_94_fu_1992_p0 = sext_ln1118_178_fu_1082_p1;

assign mul_ln1118_94_fu_1992_p1 = 21'd2097108;

assign mul_ln1118_95_fu_1908_p0 = sext_ln1118_fu_192_p1;

assign mul_ln1118_95_fu_1908_p1 = 21'd2097068;

assign mul_ln1118_96_fu_1915_p0 = sext_ln1118_172_fu_251_p1;

assign mul_ln1118_96_fu_1915_p1 = 21'd2097044;

assign mul_ln1118_97_fu_1999_p0 = sext_ln1118_178_fu_1082_p1;

assign mul_ln1118_97_fu_1999_p1 = 21'd50;

assign mul_ln1118_fu_1824_p0 = sext_ln1118_fu_192_p1;

assign mul_ln1118_fu_1824_p1 = 21'd2097113;

assign sext_ln1118_165_fu_196_p0 = data_0_V_read;

assign sext_ln1118_165_fu_196_p1 = sext_ln1118_165_fu_196_p0;

assign sext_ln1118_166_fu_209_p0 = data_1_V_read;

assign sext_ln1118_166_fu_209_p1 = sext_ln1118_166_fu_209_p0;

assign sext_ln1118_168_fu_217_p0 = data_1_V_read;

assign sext_ln1118_168_fu_217_p1 = sext_ln1118_168_fu_217_p0;

assign sext_ln1118_169_fu_221_p0 = data_1_V_read;

assign sext_ln1118_169_fu_221_p1 = sext_ln1118_169_fu_221_p0;

assign sext_ln1118_170_fu_234_p0 = data_2_V_read;

assign sext_ln1118_170_fu_234_p1 = sext_ln1118_170_fu_234_p0;

assign sext_ln1118_171_fu_238_p0 = data_2_V_read;

assign sext_ln1118_171_fu_238_p1 = sext_ln1118_171_fu_238_p0;

assign sext_ln1118_172_fu_251_p0 = data_3_V_read;

assign sext_ln1118_172_fu_251_p1 = sext_ln1118_172_fu_251_p0;

assign sext_ln1118_173_fu_255_p0 = data_3_V_read;

assign sext_ln1118_175_fu_1031_p1 = data_4_V_read_6_reg_2026;

assign sext_ln1118_176_fu_1041_p1 = $signed(shl_ln_fu_1034_p3);

assign sext_ln1118_177_fu_1058_p1 = $signed(shl_ln1118_s_fu_1051_p3);

assign sext_ln1118_178_fu_1082_p1 = data_5_V_read11_reg_2017;

assign sext_ln1118_179_fu_1085_p1 = data_5_V_read11_reg_2017;

assign sext_ln1118_180_fu_1097_p1 = data_6_V_read12_reg_2006;

assign sext_ln1118_181_fu_294_p1 = $signed(shl_ln1118_82_fu_286_p3);

assign sext_ln1118_182_fu_306_p1 = $signed(shl_ln1118_83_fu_298_p3);

assign sext_ln1118_183_fu_383_p1 = tmp_fu_375_p3;

assign sext_ln1118_184_fu_415_p1 = tmp_8_fu_407_p3;

assign sext_ln1118_185_fu_451_p1 = $signed(shl_ln1118_84_fu_443_p3);

assign sext_ln1118_186_fu_463_p1 = shl_ln1118_85_fu_455_p3;

assign sext_ln1118_187_fu_467_p1 = shl_ln1118_85_fu_455_p3;

assign sext_ln1118_188_fu_1206_p1 = $signed(shl_ln1118_86_fu_1199_p3);

assign sext_ln1118_189_fu_528_p1 = tmp_fu_375_p3;

assign sext_ln1118_190_fu_532_p1 = tmp_fu_375_p3;

assign sext_ln1118_191_fu_1269_p1 = shl_ln1118_87_fu_1262_p3;

assign sext_ln1118_192_fu_1273_p1 = shl_ln1118_87_fu_1262_p3;

assign sext_ln1118_193_fu_600_p1 = $signed(shl_ln1118_88_fu_592_p3);

assign sext_ln1118_194_fu_620_p1 = tmp_8_fu_407_p3;

assign sext_ln1118_195_fu_403_p1 = $signed(tmp_37_fu_393_p4);

assign sext_ln1118_196_fu_658_p1 = $signed(tmp_9_fu_650_p3);

assign sext_ln1118_197_fu_1374_p1 = $signed(shl_ln1118_89_fu_1367_p3);

assign sext_ln1118_198_fu_1385_p1 = shl_ln1118_90_fu_1378_p3;

assign sext_ln1118_199_fu_1389_p1 = shl_ln1118_90_fu_1378_p3;

assign sext_ln1118_200_fu_726_p1 = $signed(shl_ln1118_91_fu_718_p3);

assign sext_ln1118_201_fu_758_p1 = $signed(shl_ln1118_92_fu_750_p3);

assign sext_ln1118_202_fu_790_p1 = $signed(shl_ln1118_93_fu_782_p3);

assign sext_ln1118_203_fu_802_p1 = $signed(shl_ln1118_94_fu_794_p3);

assign sext_ln1118_204_fu_1447_p1 = $signed(shl_ln1118_95_fu_1440_p3);

assign sext_ln1118_205_fu_1478_p1 = $signed(shl_ln1118_96_fu_1471_p3);

assign sext_ln1118_206_fu_1495_p1 = $signed(shl_ln1118_97_fu_1488_p3);

assign sext_ln1118_207_fu_1522_p1 = $signed(shl_ln1118_98_fu_1515_p3);

assign sext_ln1118_208_fu_892_p1 = $signed(shl_ln1118_99_fu_884_p3);

assign sext_ln1118_209_fu_904_p1 = $signed(shl_ln1118_100_fu_896_p3);

assign sext_ln1118_210_fu_1572_p1 = shl_ln1118_101_fu_1565_p3;

assign sext_ln1118_211_fu_1576_p1 = shl_ln1118_101_fu_1565_p3;

assign sext_ln1118_212_fu_1616_p1 = $signed(shl_ln1118_102_fu_1609_p3);

assign sext_ln1118_213_fu_1633_p1 = $signed(shl_ln1118_103_fu_1626_p3);

assign sext_ln1118_214_fu_963_p1 = $signed(shl_ln1118_104_fu_955_p3);

assign sext_ln1118_215_fu_1723_p1 = $signed(shl_ln1118_106_fu_1716_p3);

assign sext_ln1118_216_fu_435_p1 = tmp_38_fu_425_p4;

assign sext_ln1118_217_fu_439_p1 = tmp_38_fu_425_p4;

assign sext_ln1118_218_fu_572_p1 = $signed(tmp_39_fu_562_p4);

assign sext_ln1118_219_fu_778_p1 = $signed(tmp_41_fu_768_p4);

assign sext_ln1118_220_fu_822_p1 = $signed(tmp_42_fu_812_p4);

assign sext_ln1118_fu_192_p0 = data_0_V_read;

assign sext_ln1118_fu_192_p1 = sext_ln1118_fu_192_p0;

assign sext_ln703_28_fu_582_p1 = $signed(add_ln703_238_fu_576_p2);

assign sext_ln703_29_fu_1409_p1 = $signed(tmp_40_fu_1399_p4);

assign sext_ln703_30_fu_1425_p1 = $signed(add_ln703_248_fu_1419_p2);

assign sext_ln703_31_fu_838_p1 = $signed(add_ln703_252_fu_832_p2);

assign sext_ln703_32_fu_1653_p1 = $signed(tmp_43_fu_1643_p4);

assign sext_ln703_33_fu_1669_p1 = $signed(add_ln703_262_fu_1663_p2);

assign sext_ln703_fu_506_p1 = $signed(add_ln703_231_fu_500_p2);

assign sext_ln708_101_fu_326_p1 = $signed(trunc_ln708_146_fu_316_p4);

assign sext_ln708_102_fu_1141_p1 = $signed(trunc_ln708_147_fu_1132_p4);

assign sext_ln708_103_fu_487_p1 = $signed(trunc_ln708_153_fu_477_p4);

assign sext_ln708_104_fu_1195_p1 = $signed(trunc_ln708_154_fu_1186_p4);

assign sext_ln708_105_fu_1226_p1 = $signed(trunc_ln708_157_fu_1216_p4);

assign sext_ln708_106_fu_552_p1 = $signed(trunc_ln708_158_fu_542_p4);

assign sext_ln708_107_fu_1293_p1 = $signed(trunc_ln708_161_fu_1283_p4);

assign sext_ln708_108_fu_646_p1 = $signed(trunc_ln708_162_fu_636_p4);

assign sext_ln708_109_fu_678_p1 = $signed(trunc_ln708_163_fu_668_p4);

assign sext_ln708_110_fu_1363_p1 = $signed(trunc_ln708_166_fu_1353_p4);

assign sext_ln708_111_fu_746_p1 = $signed(trunc_ln708_169_fu_736_p4);

assign sext_ln708_112_fu_1467_p1 = $signed(trunc_ln708_174_fu_1457_p4);

assign sext_ln708_113_fu_858_p1 = $signed(trunc_ln708_175_fu_848_p4);

assign sext_ln708_114_fu_871_p1 = $signed(trunc_ln708_179_fu_862_p4);

assign sext_ln708_115_fu_924_p1 = $signed(trunc_ln708_180_fu_914_p4);

assign sext_ln708_116_fu_1596_p1 = $signed(trunc_ln708_181_fu_1586_p4);

assign sext_ln708_117_fu_983_p1 = $signed(trunc_ln708_183_fu_973_p4);

assign sext_ln708_118_fu_997_p1 = $signed(trunc_ln708_184_fu_987_p4);

assign sext_ln708_119_fu_1749_p1 = $signed(trunc_ln708_185_fu_1739_p4);

assign sext_ln708_fu_1078_p1 = $signed(trunc_ln708_145_fu_1068_p4);

assign shl_ln1118_100_fu_896_p1 = data_3_V_read;

assign shl_ln1118_100_fu_896_p3 = {{shl_ln1118_100_fu_896_p1}, {1'd0}};

assign shl_ln1118_101_fu_1565_p3 = {{data_4_V_read_6_reg_2026}, {2'd0}};

assign shl_ln1118_102_fu_1609_p3 = {{data_6_V_read12_reg_2006}, {4'd0}};

assign shl_ln1118_103_fu_1626_p3 = {{data_6_V_read12_reg_2006}, {2'd0}};

assign shl_ln1118_104_fu_955_p1 = data_1_V_read;

assign shl_ln1118_104_fu_955_p3 = {{shl_ln1118_104_fu_955_p1}, {4'd0}};

assign shl_ln1118_105_fu_1684_p3 = {{data_4_V_read_6_reg_2026}, {7'd0}};

assign shl_ln1118_106_fu_1716_p3 = {{data_6_V_read12_reg_2006}, {5'd0}};

assign shl_ln1118_82_fu_286_p1 = data_0_V_read;

assign shl_ln1118_82_fu_286_p3 = {{shl_ln1118_82_fu_286_p1}, {4'd0}};

assign shl_ln1118_83_fu_298_p1 = data_0_V_read;

assign shl_ln1118_83_fu_298_p3 = {{shl_ln1118_83_fu_298_p1}, {1'd0}};

assign shl_ln1118_84_fu_443_p1 = data_2_V_read;

assign shl_ln1118_84_fu_443_p3 = {{shl_ln1118_84_fu_443_p1}, {5'd0}};

assign shl_ln1118_85_fu_455_p1 = data_2_V_read;

assign shl_ln1118_85_fu_455_p3 = {{shl_ln1118_85_fu_455_p1}, {3'd0}};

assign shl_ln1118_86_fu_1199_p3 = {{data_5_V_read11_reg_2017}, {4'd0}};

assign shl_ln1118_87_fu_1262_p3 = {{data_4_V_read_6_reg_2026}, {1'd0}};

assign shl_ln1118_88_fu_592_p1 = data_0_V_read;

assign shl_ln1118_88_fu_592_p3 = {{shl_ln1118_88_fu_592_p1}, {6'd0}};

assign shl_ln1118_89_fu_1367_p3 = {{data_6_V_read12_reg_2006}, {3'd0}};

assign shl_ln1118_90_fu_1378_p3 = {{data_6_V_read12_reg_2006}, {1'd0}};

assign shl_ln1118_91_fu_718_p1 = data_1_V_read;

assign shl_ln1118_91_fu_718_p3 = {{shl_ln1118_91_fu_718_p1}, {3'd0}};

assign shl_ln1118_92_fu_750_p1 = data_2_V_read;

assign shl_ln1118_92_fu_750_p3 = {{shl_ln1118_92_fu_750_p1}, {1'd0}};

assign shl_ln1118_93_fu_782_p1 = data_3_V_read;

assign shl_ln1118_93_fu_782_p3 = {{shl_ln1118_93_fu_782_p1}, {4'd0}};

assign shl_ln1118_94_fu_794_p1 = data_3_V_read;

assign shl_ln1118_94_fu_794_p3 = {{shl_ln1118_94_fu_794_p1}, {2'd0}};

assign shl_ln1118_95_fu_1440_p3 = {{data_4_V_read_6_reg_2026}, {4'd0}};

assign shl_ln1118_96_fu_1471_p3 = {{data_5_V_read11_reg_2017}, {6'd0}};

assign shl_ln1118_97_fu_1488_p3 = {{data_5_V_read11_reg_2017}, {2'd0}};

assign shl_ln1118_98_fu_1515_p3 = {{data_6_V_read12_reg_2006}, {6'd0}};

assign shl_ln1118_99_fu_884_p1 = data_3_V_read;

assign shl_ln1118_99_fu_884_p3 = {{shl_ln1118_99_fu_884_p1}, {5'd0}};

assign shl_ln1118_s_fu_1051_p3 = {{data_4_V_read_6_reg_2026}, {3'd0}};

assign shl_ln_fu_1034_p3 = {{data_4_V_read_6_reg_2026}, {5'd0}};

assign sub_ln1118_74_fu_1062_p2 = ($signed(sub_ln1118_fu_1045_p2) - $signed(sext_ln1118_177_fu_1058_p1));

assign sub_ln1118_75_fu_387_p2 = ($signed(sext_ln1118_165_fu_196_p1) - $signed(sext_ln1118_183_fu_383_p1));

assign sub_ln1118_76_fu_419_p2 = ($signed(sext_ln1118_168_fu_217_p1) - $signed(sext_ln1118_184_fu_415_p1));

assign sub_ln1118_77_fu_471_p2 = ($signed(sext_ln1118_187_fu_467_p1) - $signed(sext_ln1118_185_fu_451_p1));

assign sub_ln1118_78_fu_1210_p2 = ($signed(19'd0) - $signed(sext_ln1118_188_fu_1206_p1));

assign sub_ln1118_79_fu_522_p2 = ($signed(19'd0) - $signed(sext_ln1118_181_fu_294_p1));

assign sub_ln1118_80_fu_536_p2 = ($signed(sub_ln1118_79_fu_522_p2) - $signed(sext_ln1118_190_fu_532_p1));

assign sub_ln1118_81_fu_1277_p2 = ($signed(sext_ln1118_176_fu_1041_p1) - $signed(sext_ln1118_192_fu_1273_p1));

assign sub_ln1118_82_fu_604_p2 = ($signed(sext_ln1118_189_fu_528_p1) - $signed(sext_ln1118_193_fu_600_p1));

assign sub_ln1118_83_fu_624_p2 = ($signed(17'd0) - $signed(sext_ln1118_184_fu_415_p1));

assign sub_ln1118_84_fu_630_p2 = ($signed(sub_ln1118_83_fu_624_p2) - $signed(sext_ln1118_168_fu_217_p1));

assign sub_ln1118_85_fu_1393_p2 = ($signed(sext_ln1118_197_fu_1374_p1) - $signed(sext_ln1118_199_fu_1389_p1));

assign sub_ln1118_86_fu_730_p2 = ($signed(sext_ln1118_200_fu_726_p1) - $signed(sext_ln1118_169_fu_221_p1));

assign sub_ln1118_87_fu_762_p2 = ($signed(sext_ln1118_201_fu_758_p1) - $signed(sext_ln1118_186_fu_463_p1));

assign sub_ln1118_88_fu_1451_p2 = ($signed(sext_ln1118_191_fu_1269_p1) - $signed(sext_ln1118_204_fu_1447_p1));

assign sub_ln1118_89_fu_1482_p2 = ($signed(21'd0) - $signed(sext_ln1118_205_fu_1478_p1));

assign sub_ln1118_90_fu_1499_p2 = ($signed(sub_ln1118_89_fu_1482_p2) - $signed(sext_ln1118_206_fu_1495_p1));

assign sub_ln1118_91_fu_1526_p2 = ($signed(sext_ln1118_207_fu_1522_p1) - $signed(sext_ln1118_180_fu_1097_p1));

assign sub_ln1118_92_fu_908_p2 = ($signed(sext_ln1118_208_fu_892_p1) - $signed(sext_ln1118_209_fu_904_p1));

assign sub_ln1118_93_fu_1620_p2 = ($signed(19'd0) - $signed(sext_ln1118_212_fu_1616_p1));

assign sub_ln1118_94_fu_1637_p2 = ($signed(sub_ln1118_93_fu_1620_p2) - $signed(sext_ln1118_213_fu_1633_p1));

assign sub_ln1118_95_fu_1691_p2 = ($signed(shl_ln1118_105_fu_1684_p3) - $signed(sext_ln1118_211_fu_1576_p1));

assign sub_ln1118_96_fu_1727_p2 = ($signed(20'd0) - $signed(sext_ln1118_215_fu_1723_p1));

assign sub_ln1118_97_fu_1733_p2 = ($signed(sub_ln1118_96_fu_1727_p2) - $signed(sext_ln1118_198_fu_1385_p1));

assign sub_ln1118_98_fu_662_p2 = ($signed(sext_ln1118_171_fu_238_p1) - $signed(sext_ln1118_196_fu_658_p1));

assign sub_ln1118_fu_1045_p2 = ($signed(20'd0) - $signed(sext_ln1118_176_fu_1041_p1));

assign tmp_37_fu_393_p4 = {{sub_ln1118_75_fu_387_p2[16:7]}};

assign tmp_38_fu_425_p4 = {{sub_ln1118_76_fu_419_p2[16:7]}};

assign tmp_39_fu_562_p4 = {{mul_ln1118_85_fu_556_p2[18:7]}};

assign tmp_40_fu_1399_p4 = {{sub_ln1118_85_fu_1393_p2[17:7]}};

assign tmp_41_fu_768_p4 = {{sub_ln1118_87_fu_762_p2[17:7]}};

assign tmp_42_fu_812_p4 = {{add_ln1118_15_fu_806_p2[18:7]}};

assign tmp_43_fu_1643_p4 = {{sub_ln1118_94_fu_1637_p2[18:7]}};

assign tmp_8_fu_407_p1 = data_1_V_read;

assign tmp_8_fu_407_p3 = {{tmp_8_fu_407_p1}, {2'd0}};

assign tmp_9_fu_650_p1 = data_2_V_read;

assign tmp_9_fu_650_p3 = {{tmp_9_fu_650_p1}, {2'd0}};

assign tmp_fu_375_p1 = data_0_V_read;

assign tmp_fu_375_p3 = {{tmp_fu_375_p1}, {2'd0}};

assign trunc_ln708_125_fu_225_p4 = {{mul_ln1118_69_fu_1831_p2[20:7]}};

assign trunc_ln708_126_fu_242_p4 = {{mul_ln1118_70_fu_1838_p2[20:7]}};

assign trunc_ln708_127_fu_259_p4 = {{mul_ln1118_71_fu_1845_p2[20:7]}};

assign trunc_ln708_129_fu_1088_p4 = {{mul_ln1118_72_fu_1922_p2[20:7]}};

assign trunc_ln708_130_fu_1100_p4 = {{mul_ln1118_73_fu_1929_p2[20:7]}};

assign trunc_ln708_132_fu_330_p4 = {{mul_ln1118_74_fu_1852_p2[20:7]}};

assign trunc_ln708_133_fu_339_p4 = {{mul_ln1118_75_fu_1859_p2[20:7]}};

assign trunc_ln708_134_fu_348_p4 = {{mul_ln1118_76_fu_1866_p2[20:7]}};

assign trunc_ln708_136_fu_1145_p4 = {{mul_ln1118_78_fu_1943_p2[20:7]}};

assign trunc_ln708_137_fu_1154_p4 = {{mul_ln1118_79_fu_1950_p2[20:7]}};

assign trunc_ln708_141_fu_491_p4 = {{mul_ln1118_82_fu_1873_p2[20:7]}};

assign trunc_ln708_144_fu_1230_p4 = {{mul_ln1118_84_fu_1964_p2[20:7]}};

assign trunc_ln708_145_fu_1068_p4 = {{sub_ln1118_74_fu_1062_p2[19:7]}};

assign trunc_ln708_146_fu_316_p4 = {{add_ln1118_fu_310_p2[18:7]}};

assign trunc_ln708_147_fu_1132_p4 = {{mul_ln1118_77_fu_1936_p2[19:7]}};

assign trunc_ln708_150_fu_1297_p4 = {{mul_ln1118_86_fu_1971_p2[20:7]}};

assign trunc_ln708_151_fu_1306_p4 = {{mul_ln1118_87_fu_1978_p2[20:7]}};

assign trunc_ln708_152_fu_610_p4 = {{sub_ln1118_82_fu_604_p2[20:7]}};

assign trunc_ln708_153_fu_477_p4 = {{sub_ln1118_77_fu_471_p2[19:7]}};

assign trunc_ln708_154_fu_1186_p4 = {{mul_ln1118_83_fu_1957_p2[19:7]}};

assign trunc_ln708_155_fu_682_p4 = {{mul_ln1118_89_fu_1880_p2[20:7]}};

assign trunc_ln708_156_fu_1338_p4 = {{mul_ln1118_90_fu_1985_p2[20:7]}};

assign trunc_ln708_157_fu_1216_p4 = {{sub_ln1118_78_fu_1210_p2[18:7]}};

assign trunc_ln708_158_fu_542_p4 = {{sub_ln1118_80_fu_536_p2[18:7]}};

assign trunc_ln708_159_fu_709_p4 = {{mul_ln1118_91_fu_1887_p2[20:7]}};

assign trunc_ln708_161_fu_1283_p4 = {{sub_ln1118_81_fu_1277_p2[19:7]}};

assign trunc_ln708_162_fu_636_p4 = {{sub_ln1118_84_fu_630_p2[16:7]}};

assign trunc_ln708_163_fu_668_p4 = {{sub_ln1118_98_fu_662_p2[16:7]}};

assign trunc_ln708_164_fu_1505_p4 = {{sub_ln1118_90_fu_1499_p2[20:7]}};

assign trunc_ln708_165_fu_1532_p4 = {{sub_ln1118_91_fu_1526_p2[20:7]}};

assign trunc_ln708_166_fu_1353_p4 = {{add_ln1118_14_fu_1347_p2[18:7]}};

assign trunc_ln708_168_fu_875_p4 = {{mul_ln1118_93_fu_1901_p2[20:7]}};

assign trunc_ln708_169_fu_736_p4 = {{sub_ln1118_86_fu_730_p2[17:7]}};

assign trunc_ln708_171_fu_1600_p4 = {{mul_ln1118_94_fu_1992_p2[20:7]}};

assign trunc_ln708_173_fu_946_p4 = {{mul_ln1118_95_fu_1908_p2[20:7]}};

assign trunc_ln708_174_fu_1457_p4 = {{sub_ln1118_88_fu_1451_p2[18:7]}};

assign trunc_ln708_175_fu_848_p1 = data_0_V_read;

assign trunc_ln708_175_fu_848_p4 = {{trunc_ln708_175_fu_848_p1[13:1]}};

assign trunc_ln708_176_fu_1001_p4 = {{mul_ln1118_96_fu_1915_p2[20:7]}};

assign trunc_ln708_177_fu_1697_p4 = {{sub_ln1118_95_fu_1691_p2[20:7]}};

assign trunc_ln708_178_fu_1707_p4 = {{mul_ln1118_97_fu_1999_p2[20:7]}};

assign trunc_ln708_179_fu_862_p4 = {{mul_ln1118_92_fu_1894_p2[19:7]}};

assign trunc_ln708_180_fu_914_p4 = {{sub_ln1118_92_fu_908_p2[19:7]}};

assign trunc_ln708_181_fu_1586_p4 = {{add_ln1118_16_fu_1580_p2[18:7]}};

assign trunc_ln708_183_fu_973_p4 = {{add_ln1118_17_fu_967_p2[18:7]}};

assign trunc_ln708_184_fu_987_p1 = data_2_V_read;

assign trunc_ln708_184_fu_987_p4 = {{trunc_ln708_184_fu_987_p1[13:6]}};

assign trunc_ln708_185_fu_1739_p4 = {{sub_ln1118_97_fu_1733_p2[19:7]}};

assign trunc_ln_fu_200_p4 = {{mul_ln1118_fu_1824_p2[20:7]}};

endmodule //dense_resource_0_0_2
