// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_resource_0_0 (
        ap_clk,
        ap_rst,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [13:0] data_0_V_read;
input  [13:0] data_1_V_read;
input  [13:0] data_2_V_read;
input  [13:0] data_3_V_read;
input  [13:0] data_4_V_read;
input  [13:0] data_5_V_read;
input  [13:0] data_6_V_read;
input  [13:0] data_7_V_read;
output  [13:0] ap_return_0;
output  [13:0] ap_return_1;
output  [13:0] ap_return_2;
output  [13:0] ap_return_3;
output  [13:0] ap_return_4;
output  [13:0] ap_return_5;
output  [13:0] ap_return_6;
output  [13:0] ap_return_7;
input   ap_ce;

reg[13:0] ap_return_0;
reg[13:0] ap_return_1;
reg[13:0] ap_return_2;
reg[13:0] ap_return_3;
reg[13:0] ap_return_4;
reg[13:0] ap_return_5;
reg[13:0] ap_return_6;
reg[13:0] ap_return_7;

reg  signed [13:0] data_5_V_read_7_reg_2107;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
reg  signed [13:0] data_4_V_read_8_reg_2115;
reg  signed [13:0] data_3_V_read_8_reg_2121;
reg  signed [13:0] data_2_V_read_8_reg_2129;
reg  signed [13:0] data_1_V_read_8_reg_2138;
reg  signed [13:0] data_0_V_read_8_reg_2150;
reg   [13:0] trunc_ln708_4_reg_2159;
reg   [13:0] trunc_ln708_5_reg_2164;
wire   [13:0] add_ln703_130_fu_333_p2;
reg   [13:0] add_ln703_130_reg_2169;
reg   [13:0] trunc_ln708_12_reg_2174;
reg   [13:0] trunc_ln708_13_reg_2179;
wire   [13:0] add_ln703_138_fu_381_p2;
reg   [13:0] add_ln703_138_reg_2184;
wire   [13:0] add_ln703_146_fu_415_p2;
reg   [13:0] add_ln703_146_reg_2189;
reg   [12:0] trunc_ln708_111_reg_2194;
reg   [13:0] trunc_ln708_28_reg_2199;
reg   [13:0] trunc_ln708_29_reg_2204;
wire   [13:0] add_ln703_154_fu_477_p2;
reg   [13:0] add_ln703_154_reg_2209;
reg   [13:0] trunc_ln708_36_reg_2214;
reg   [13:0] trunc_ln708_37_reg_2219;
wire   [13:0] add_ln703_162_fu_525_p2;
reg   [13:0] add_ln703_162_reg_2224;
reg   [13:0] trunc_ln708_44_reg_2229;
wire   [13:0] add_ln703_170_fu_635_p2;
reg   [13:0] add_ln703_170_reg_2235;
reg   [10:0] trunc_ln708_119_reg_2240;
wire   [13:0] add_ln703_178_fu_743_p2;
reg   [13:0] add_ln703_178_reg_2245;
reg   [10:0] trunc_ln708_122_reg_2250;
wire   [13:0] add_ln703_185_fu_847_p2;
reg   [13:0] add_ln703_185_reg_2255;
wire  signed [13:0] sext_ln1118_116_fu_232_p0;
wire    ap_block_pp0_stage0;
wire  signed [20:0] mul_ln1118_4_fu_1848_p2;
wire  signed [13:0] sext_ln1118_118_fu_245_p0;
wire  signed [13:0] sext_ln1118_119_fu_249_p0;
wire  signed [20:0] mul_ln1118_5_fu_1855_p2;
wire  signed [13:0] sext_ln1118_120_fu_262_p0;
wire  signed [20:0] mul_ln1118_6_fu_1862_p2;
wire  signed [13:0] sext_ln1118_122_fu_279_p0;
wire  signed [13:0] shl_ln1118_58_fu_287_p1;
wire   [19:0] shl_ln1118_58_fu_287_p3;
wire  signed [13:0] shl_ln1118_59_fu_299_p1;
wire   [17:0] shl_ln1118_59_fu_299_p3;
wire  signed [20:0] sext_ln1118_124_fu_295_p1;
wire  signed [20:0] sext_ln1118_125_fu_307_p1;
wire   [20:0] sub_ln1118_49_fu_311_p2;
wire   [13:0] trunc_ln708_7_fu_317_p4;
wire   [13:0] add_ln703_129_fu_327_p2;
wire   [13:0] trunc_ln708_6_fu_270_p4;
wire  signed [20:0] mul_ln1118_12_fu_1869_p2;
wire  signed [20:0] mul_ln1118_13_fu_1876_p2;
wire  signed [20:0] mul_ln1118_14_fu_1883_p2;
wire  signed [20:0] mul_ln1118_15_fu_1890_p2;
wire   [13:0] trunc_ln708_15_fu_366_p4;
wire   [13:0] add_ln703_137_fu_375_p2;
wire   [13:0] trunc_ln708_14_fu_357_p4;
wire  signed [19:0] mul_ln1118_22_fu_1897_p2;
wire   [12:0] trunc_ln708_110_fu_387_p4;
wire  signed [20:0] mul_ln1118_23_fu_1904_p2;
wire   [13:0] trunc_ln708_23_fu_400_p4;
wire   [13:0] add_ln703_145_fu_409_p2;
wire  signed [13:0] sext_ln708_89_fu_396_p1;
wire  signed [13:0] trunc_ln708_111_fu_421_p1;
wire  signed [20:0] mul_ln1118_28_fu_1911_p2;
wire  signed [20:0] mul_ln1118_29_fu_1918_p2;
wire  signed [20:0] mul_ln1118_30_fu_1925_p2;
wire  signed [19:0] mul_ln1118_31_fu_1932_p2;
wire   [12:0] trunc_ln708_112_fu_458_p4;
wire  signed [13:0] sext_ln708_91_fu_467_p1;
wire   [13:0] add_ln703_153_fu_471_p2;
wire   [13:0] trunc_ln708_30_fu_449_p4;
wire  signed [20:0] mul_ln1118_36_fu_1939_p2;
wire  signed [20:0] mul_ln1118_37_fu_1946_p2;
wire  signed [20:0] mul_ln1118_38_fu_1953_p2;
wire  signed [20:0] mul_ln1118_39_fu_1960_p2;
wire   [13:0] trunc_ln708_39_fu_510_p4;
wire   [13:0] add_ln703_161_fu_519_p2;
wire   [13:0] trunc_ln708_38_fu_501_p4;
wire  signed [13:0] tmp_fu_531_p1;
wire   [19:0] tmp_fu_531_p3;
wire  signed [20:0] sext_ln1118_116_fu_232_p1;
wire  signed [20:0] sext_ln1118_217_fu_539_p1;
wire   [20:0] sub_ln1118_100_fu_543_p2;
wire  signed [20:0] mul_ln1118_43_fu_1967_p2;
wire  signed [13:0] shl_ln1118_72_fu_568_p1;
wire   [20:0] shl_ln1118_72_fu_568_p3;
wire  signed [13:0] shl_ln1118_73_fu_582_p1;
wire  signed [18:0] shl_ln1118_73_fu_582_p3;
wire   [20:0] sub_ln1118_60_fu_576_p2;
wire  signed [20:0] sext_ln1118_140_fu_594_p1;
wire   [20:0] sub_ln1118_61_fu_598_p2;
wire  signed [20:0] mul_ln1118_44_fu_1974_p2;
wire   [13:0] trunc_ln708_45_fu_559_p4;
wire   [13:0] trunc_ln708_46_fu_604_p4;
wire   [13:0] trunc_ln708_47_fu_614_p4;
wire   [13:0] add_ln703_169_fu_629_p2;
wire   [13:0] add_ln703_168_fu_623_p2;
wire  signed [13:0] trunc_ln708_116_fu_641_p1;
wire   [6:0] trunc_ln708_116_fu_641_p4;
wire  signed [13:0] trunc_ln708_119_fu_655_p1;
wire  signed [13:0] shl_ln1118_74_fu_665_p1;
wire   [17:0] shl_ln1118_74_fu_665_p3;
wire  signed [18:0] sext_ln1118_142_fu_673_p1;
wire   [18:0] sub_ln1118_62_fu_677_p2;
wire  signed [18:0] sext_ln1118_119_fu_249_p1;
wire   [18:0] sub_ln1118_63_fu_683_p2;
wire   [11:0] trunc_ln708_120_fu_689_p4;
wire  signed [20:0] mul_ln1118_48_fu_1981_p2;
wire  signed [20:0] mul_ln1118_49_fu_1988_p2;
wire  signed [13:0] sext_ln708_98_fu_699_p1;
wire   [13:0] trunc_ln708_54_fu_703_p4;
wire  signed [7:0] sext_ln1118_141_fu_651_p1;
wire   [7:0] add_ln703_176_fu_727_p2;
wire  signed [13:0] sext_ln703_fu_733_p1;
wire   [13:0] trunc_ln708_55_fu_712_p4;
wire   [13:0] add_ln703_177_fu_737_p2;
wire   [13:0] add_ln703_175_fu_721_p2;
wire  signed [13:0] trunc_ln708_122_fu_749_p1;
wire  signed [13:0] shl_ln1118_77_fu_759_p1;
wire   [16:0] shl_ln1118_77_fu_759_p3;
wire  signed [19:0] sext_ln1118_145_fu_767_p1;
wire  signed [19:0] sext_ln1118_139_fu_590_p1;
wire   [19:0] sub_ln1118_66_fu_771_p2;
wire   [12:0] trunc_ln708_124_fu_777_p4;
wire  signed [13:0] shl_ln1118_78_fu_791_p1;
wire   [18:0] shl_ln1118_78_fu_791_p3;
wire  signed [19:0] sext_ln1118_146_fu_799_p1;
wire  signed [13:0] shl_ln1118_79_fu_809_p1;
wire   [16:0] shl_ln1118_79_fu_809_p3;
wire   [19:0] sub_ln1118_67_fu_803_p2;
wire  signed [19:0] sext_ln1118_147_fu_817_p1;
wire   [19:0] sub_ln1118_68_fu_821_p2;
wire   [12:0] trunc_ln708_125_fu_827_p4;
wire  signed [13:0] sext_ln708_103_fu_837_p1;
wire   [13:0] add_ln703_184_fu_841_p2;
wire  signed [13:0] sext_ln708_102_fu_787_p1;
wire   [18:0] shl_ln_fu_856_p3;
wire  signed [19:0] sext_ln1118_102_fu_863_p1;
wire  signed [14:0] shl_ln1118_56_fu_873_p3;
wire   [19:0] sub_ln1118_fu_867_p2;
wire  signed [19:0] sext_ln1118_104_fu_884_p1;
wire   [19:0] sub_ln1118_47_fu_888_p2;
wire   [12:0] trunc_ln_fu_894_p4;
wire   [16:0] shl_ln1118_57_fu_917_p3;
wire  signed [17:0] sext_ln1118_108_fu_924_p1;
wire  signed [17:0] sext_ln1118_107_fu_914_p1;
wire   [17:0] sub_ln1118_48_fu_928_p2;
wire   [10:0] trunc_ln708_106_fu_934_p4;
wire  signed [20:0] mul_ln1118_2_fu_1995_p2;
wire  signed [20:0] mul_ln1118_3_fu_2002_p2;
wire  signed [13:0] sext_ln708_fu_904_p1;
wire  signed [13:0] sext_ln708_85_fu_944_p1;
wire   [13:0] trunc_ln708_2_fu_957_p4;
wire   [13:0] trunc_ln708_3_fu_975_p4;
wire   [13:0] add_ln703_126_fu_990_p2;
wire   [13:0] add_ln703_fu_984_p2;
wire   [13:0] add_ln703_128_fu_1002_p2;
wire   [13:0] add_ln703_131_fu_1006_p2;
wire   [13:0] add_ln703_127_fu_996_p2;
wire  signed [20:0] mul_ln1118_8_fu_2009_p2;
wire   [18:0] shl_ln1118_60_fu_1026_p3;
wire  signed [19:0] sext_ln1118_126_fu_1033_p1;
wire  signed [15:0] shl_ln1118_61_fu_1043_p3;
wire   [19:0] sub_ln1118_50_fu_1037_p2;
wire  signed [19:0] sext_ln1118_128_fu_1054_p1;
wire   [19:0] sub_ln1118_51_fu_1058_p2;
wire   [12:0] trunc_ln708_107_fu_1064_p4;
wire  signed [20:0] mul_ln1118_10_fu_2016_p2;
wire  signed [13:0] mul_ln1118_11_fu_1087_p0;
wire   [18:0] mul_ln1118_11_fu_1087_p2;
wire   [11:0] trunc_ln708_108_fu_1093_p4;
wire   [13:0] trunc_ln708_8_fu_1017_p4;
wire  signed [13:0] sext_ln708_86_fu_1074_p1;
wire   [13:0] trunc_ln708_10_fu_1078_p4;
wire  signed [13:0] sext_ln708_87_fu_1103_p1;
wire   [13:0] add_ln703_134_fu_1113_p2;
wire   [13:0] add_ln703_133_fu_1107_p2;
wire   [13:0] add_ln703_136_fu_1125_p2;
wire   [13:0] add_ln703_139_fu_1129_p2;
wire   [13:0] add_ln703_135_fu_1119_p2;
wire  signed [15:0] sext_ln1118_103_fu_880_p1;
wire   [15:0] sub_ln1118_52_fu_1140_p2;
wire   [8:0] trunc_ln708_109_fu_1146_p4;
wire  signed [20:0] mul_ln1118_17_fu_2023_p2;
wire   [19:0] shl_ln1118_62_fu_1169_p3;
wire  signed [20:0] sext_ln1118_129_fu_1176_p1;
wire  signed [16:0] shl_ln1118_63_fu_1186_p3;
wire   [20:0] sub_ln1118_53_fu_1180_p2;
wire  signed [20:0] sext_ln1118_131_fu_1197_p1;
wire   [20:0] sub_ln1118_54_fu_1201_p2;
wire  signed [20:0] mul_ln1118_19_fu_2030_p2;
wire   [16:0] shl_ln1118_65_fu_1233_p3;
wire  signed [20:0] sext_ln1118_132_fu_1240_p1;
wire   [20:0] shl_ln1118_64_fu_1226_p3;
wire   [20:0] sub_ln1118_55_fu_1244_p2;
wire   [19:0] shl_ln1118_66_fu_1260_p3;
wire   [15:0] shl_ln1118_67_fu_1271_p3;
wire  signed [20:0] sext_ln1118_134_fu_1278_p1;
wire  signed [20:0] sext_ln1118_133_fu_1267_p1;
wire   [20:0] add_ln1118_fu_1282_p2;
wire  signed [13:0] sext_ln708_88_fu_1156_p1;
wire   [13:0] trunc_ln708_17_fu_1160_p4;
wire   [13:0] trunc_ln708_18_fu_1207_p4;
wire   [13:0] trunc_ln708_19_fu_1217_p4;
wire   [13:0] add_ln703_142_fu_1304_p2;
wire   [13:0] add_ln703_141_fu_1298_p2;
wire   [13:0] trunc_ln708_20_fu_1250_p4;
wire   [13:0] trunc_ln708_21_fu_1288_p4;
wire   [13:0] add_ln703_144_fu_1316_p2;
wire   [13:0] add_ln703_147_fu_1322_p2;
wire   [13:0] add_ln703_143_fu_1310_p2;
wire  signed [20:0] mul_ln1118_24_fu_2037_p2;
wire  signed [20:0] mul_ln1118_25_fu_2044_p2;
wire  signed [20:0] mul_ln1118_27_fu_2051_p2;
wire   [13:0] trunc_ln708_24_fu_1333_p4;
wire   [13:0] trunc_ln708_25_fu_1342_p4;
wire  signed [13:0] sext_ln708_90_fu_1351_p1;
wire   [13:0] trunc_ln708_27_fu_1354_p4;
wire   [13:0] add_ln703_150_fu_1369_p2;
wire   [13:0] add_ln703_149_fu_1363_p2;
wire   [13:0] add_ln703_152_fu_1381_p2;
wire   [13:0] add_ln703_155_fu_1385_p2;
wire   [13:0] add_ln703_151_fu_1375_p2;
wire   [19:0] shl_ln1118_68_fu_1396_p3;
wire   [16:0] shl_ln1118_69_fu_1407_p3;
wire  signed [20:0] sext_ln1118_136_fu_1414_p1;
wire  signed [20:0] sext_ln1118_135_fu_1403_p1;
wire   [20:0] sub_ln1118_56_fu_1418_p2;
wire  signed [20:0] mul_ln1118_33_fu_2058_p2;
wire  signed [17:0] sext_ln1118_130_fu_1193_p1;
wire  signed [17:0] sext_ln1118_112_fu_954_p1;
wire   [17:0] sub_ln1118_57_fu_1443_p2;
wire   [10:0] trunc_ln708_113_fu_1449_p4;
wire  signed [20:0] mul_ln1118_35_fu_2065_p2;
wire   [13:0] trunc_ln708_32_fu_1424_p4;
wire   [13:0] trunc_ln708_33_fu_1434_p4;
wire  signed [13:0] sext_ln708_92_fu_1459_p1;
wire   [13:0] trunc_ln708_35_fu_1463_p4;
wire   [13:0] add_ln703_158_fu_1478_p2;
wire   [13:0] add_ln703_157_fu_1472_p2;
wire   [13:0] add_ln703_160_fu_1490_p2;
wire   [13:0] add_ln703_163_fu_1494_p2;
wire   [13:0] add_ln703_159_fu_1484_p2;
wire  signed [20:0] mul_ln1118_40_fu_2072_p2;
wire   [17:0] shl_ln1118_70_fu_1514_p3;
wire  signed [18:0] sext_ln1118_137_fu_1521_p1;
wire   [14:0] shl_ln1118_71_fu_1531_p3;
wire   [18:0] sub_ln1118_58_fu_1525_p2;
wire  signed [18:0] sext_ln1118_138_fu_1538_p1;
wire   [18:0] sub_ln1118_59_fu_1542_p2;
wire   [11:0] trunc_ln708_114_fu_1548_p4;
wire  signed [19:0] mul_ln1118_42_fu_2079_p2;
wire   [12:0] trunc_ln708_115_fu_1562_p4;
wire   [13:0] trunc_ln708_40_fu_1505_p4;
wire  signed [13:0] sext_ln708_93_fu_1558_p1;
wire  signed [13:0] sext_ln708_94_fu_1571_p1;
wire   [13:0] add_ln703_166_fu_1581_p2;
wire   [13:0] add_ln703_165_fu_1575_p2;
wire   [13:0] add_ln703_167_fu_1586_p2;
wire  signed [13:0] mul_ln1118_45_fu_1597_p0;
wire   [18:0] mul_ln1118_45_fu_1597_p2;
wire   [11:0] trunc_ln708_117_fu_1603_p4;
wire  signed [20:0] mul_ln1118_46_fu_2086_p2;
wire   [18:0] tmp_s_fu_1626_p3;
wire  signed [19:0] sext_ln1118_114_fu_969_p1;
wire  signed [19:0] sext_ln1118_218_fu_1633_p1;
wire   [19:0] sub_ln1118_101_fu_1637_p2;
wire   [12:0] trunc_ln708_118_fu_1643_p4;
wire  signed [13:0] sext_ln708_95_fu_1613_p1;
wire   [13:0] trunc_ln708_50_fu_1617_p4;
wire  signed [13:0] sext_ln708_96_fu_1653_p1;
wire  signed [13:0] sext_ln708_97_fu_1657_p1;
wire   [13:0] add_ln703_173_fu_1666_p2;
wire   [13:0] add_ln703_172_fu_1660_p2;
wire   [13:0] add_ln703_174_fu_1672_p2;
wire  signed [20:0] mul_ln1118_50_fu_2093_p2;
wire  signed [18:0] sext_ln1118_127_fu_1050_p1;
wire   [18:0] sub_ln1118_64_fu_1692_p2;
wire   [11:0] trunc_ln708_121_fu_1698_p4;
wire  signed [20:0] mul_ln1118_51_fu_2100_p2;
wire   [16:0] shl_ln1118_75_fu_1724_p3;
wire   [14:0] shl_ln1118_76_fu_1735_p3;
wire  signed [17:0] sext_ln1118_143_fu_1731_p1;
wire  signed [17:0] sext_ln1118_144_fu_1742_p1;
wire   [17:0] sub_ln1118_65_fu_1746_p2;
wire   [10:0] trunc_ln708_123_fu_1752_p4;
wire   [13:0] trunc_ln708_56_fu_1683_p4;
wire  signed [13:0] sext_ln708_99_fu_1708_p1;
wire  signed [13:0] sext_ln708_100_fu_1712_p1;
wire   [13:0] trunc_ln708_59_fu_1715_p4;
wire   [13:0] add_ln703_181_fu_1772_p2;
wire   [13:0] add_ln703_180_fu_1766_p2;
wire  signed [13:0] sext_ln708_101_fu_1762_p1;
wire   [13:0] add_ln703_183_fu_1784_p2;
wire   [13:0] add_ln703_186_fu_1789_p2;
wire   [13:0] add_ln703_182_fu_1778_p2;
wire   [13:0] add_ln703_277_fu_1011_p2;
wire   [13:0] add_ln703_278_fu_1134_p2;
wire   [13:0] add_ln703_279_fu_1327_p2;
wire   [13:0] add_ln703_280_fu_1390_p2;
wire   [13:0] add_ln703_281_fu_1499_p2;
wire   [13:0] add_ln703_282_fu_1592_p2;
wire   [13:0] add_ln703_283_fu_1678_p2;
wire   [13:0] add_ln703_284_fu_1794_p2;
wire  signed [13:0] mul_ln1118_4_fu_1848_p0;
wire   [7:0] mul_ln1118_4_fu_1848_p1;
wire  signed [13:0] mul_ln1118_5_fu_1855_p0;
wire  signed [20:0] sext_ln1118_118_fu_245_p1;
wire  signed [6:0] mul_ln1118_5_fu_1855_p1;
wire  signed [13:0] mul_ln1118_6_fu_1862_p0;
wire  signed [20:0] sext_ln1118_120_fu_262_p1;
wire   [7:0] mul_ln1118_6_fu_1862_p1;
wire  signed [13:0] mul_ln1118_12_fu_1869_p0;
wire  signed [7:0] mul_ln1118_12_fu_1869_p1;
wire  signed [13:0] mul_ln1118_13_fu_1876_p0;
wire   [7:0] mul_ln1118_13_fu_1876_p1;
wire  signed [13:0] mul_ln1118_14_fu_1883_p0;
wire  signed [7:0] mul_ln1118_14_fu_1883_p1;
wire  signed [13:0] mul_ln1118_15_fu_1890_p0;
wire  signed [20:0] sext_ln1118_122_fu_279_p1;
wire   [6:0] mul_ln1118_15_fu_1890_p1;
wire  signed [5:0] mul_ln1118_22_fu_1897_p1;
wire  signed [13:0] mul_ln1118_23_fu_1904_p0;
wire  signed [6:0] mul_ln1118_23_fu_1904_p1;
wire  signed [13:0] mul_ln1118_28_fu_1911_p0;
wire   [7:0] mul_ln1118_28_fu_1911_p1;
wire  signed [13:0] mul_ln1118_29_fu_1918_p0;
wire  signed [7:0] mul_ln1118_29_fu_1918_p1;
wire  signed [13:0] mul_ln1118_30_fu_1925_p0;
wire   [7:0] mul_ln1118_30_fu_1925_p1;
wire   [5:0] mul_ln1118_31_fu_1932_p1;
wire  signed [13:0] mul_ln1118_36_fu_1939_p0;
wire   [7:0] mul_ln1118_36_fu_1939_p1;
wire  signed [13:0] mul_ln1118_37_fu_1946_p0;
wire   [7:0] mul_ln1118_37_fu_1946_p1;
wire  signed [13:0] mul_ln1118_38_fu_1953_p0;
wire   [6:0] mul_ln1118_38_fu_1953_p1;
wire  signed [13:0] mul_ln1118_39_fu_1960_p0;
wire  signed [8:0] mul_ln1118_39_fu_1960_p1;
wire  signed [13:0] mul_ln1118_43_fu_1967_p0;
wire   [7:0] mul_ln1118_43_fu_1967_p1;
wire  signed [13:0] mul_ln1118_44_fu_1974_p0;
wire  signed [7:0] mul_ln1118_44_fu_1974_p1;
wire  signed [13:0] mul_ln1118_48_fu_1981_p0;
wire  signed [6:0] mul_ln1118_48_fu_1981_p1;
wire  signed [13:0] mul_ln1118_49_fu_1988_p0;
wire  signed [6:0] mul_ln1118_49_fu_1988_p1;
wire  signed [13:0] mul_ln1118_2_fu_1995_p0;
wire  signed [20:0] sext_ln1118_109_fu_948_p1;
wire  signed [6:0] mul_ln1118_2_fu_1995_p1;
wire  signed [13:0] mul_ln1118_3_fu_2002_p0;
wire  signed [20:0] sext_ln1118_113_fu_966_p1;
wire   [6:0] mul_ln1118_3_fu_2002_p1;
wire  signed [13:0] mul_ln1118_8_fu_2009_p0;
wire  signed [20:0] sext_ln1118_fu_853_p1;
wire   [7:0] mul_ln1118_8_fu_2009_p1;
wire  signed [13:0] mul_ln1118_10_fu_2016_p0;
wire  signed [7:0] mul_ln1118_10_fu_2016_p1;
wire  signed [13:0] mul_ln1118_17_fu_2023_p0;
wire  signed [20:0] sext_ln1118_105_fu_908_p1;
wire  signed [7:0] mul_ln1118_17_fu_2023_p1;
wire  signed [13:0] mul_ln1118_19_fu_2030_p0;
wire  signed [7:0] mul_ln1118_19_fu_2030_p1;
wire  signed [13:0] mul_ln1118_24_fu_2037_p0;
wire  signed [7:0] mul_ln1118_24_fu_2037_p1;
wire  signed [13:0] mul_ln1118_25_fu_2044_p0;
wire   [7:0] mul_ln1118_25_fu_2044_p1;
wire  signed [13:0] mul_ln1118_27_fu_2051_p0;
wire   [7:0] mul_ln1118_27_fu_2051_p1;
wire  signed [13:0] mul_ln1118_33_fu_2058_p0;
wire   [7:0] mul_ln1118_33_fu_2058_p1;
wire  signed [13:0] mul_ln1118_35_fu_2065_p0;
wire  signed [8:0] mul_ln1118_35_fu_2065_p1;
wire  signed [13:0] mul_ln1118_40_fu_2072_p0;
wire   [6:0] mul_ln1118_40_fu_2072_p1;
wire  signed [5:0] mul_ln1118_42_fu_2079_p1;
wire  signed [13:0] mul_ln1118_46_fu_2086_p0;
wire  signed [6:0] mul_ln1118_46_fu_2086_p1;
wire  signed [13:0] mul_ln1118_50_fu_2093_p0;
wire  signed [6:0] mul_ln1118_50_fu_2093_p1;
wire  signed [13:0] mul_ln1118_51_fu_2100_p0;
wire  signed [6:0] mul_ln1118_51_fu_2100_p1;
reg    ap_ce_reg;
reg   [13:0] ap_return_0_int_reg;
reg   [13:0] ap_return_1_int_reg;
reg   [13:0] ap_return_2_int_reg;
reg   [13:0] ap_return_3_int_reg;
reg   [13:0] ap_return_4_int_reg;
reg   [13:0] ap_return_5_int_reg;
reg   [13:0] ap_return_6_int_reg;
reg   [13:0] ap_return_7_int_reg;

example_mul_mul_1wdI #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1wdI_U1888(
    .din0(mul_ln1118_4_fu_1848_p0),
    .din1(mul_ln1118_4_fu_1848_p1),
    .dout(mul_ln1118_4_fu_1848_p2)
);

example_mul_mul_1ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1ocq_U1889(
    .din0(mul_ln1118_5_fu_1855_p0),
    .din1(mul_ln1118_5_fu_1855_p1),
    .dout(mul_ln1118_5_fu_1855_p2)
);

example_mul_mul_1wdI #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1wdI_U1890(
    .din0(mul_ln1118_6_fu_1862_p0),
    .din1(mul_ln1118_6_fu_1862_p1),
    .dout(mul_ln1118_6_fu_1862_p2)
);

example_mul_mul_1sc4 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1sc4_U1891(
    .din0(mul_ln1118_12_fu_1869_p0),
    .din1(mul_ln1118_12_fu_1869_p1),
    .dout(mul_ln1118_12_fu_1869_p2)
);

example_mul_mul_1wdI #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1wdI_U1892(
    .din0(mul_ln1118_13_fu_1876_p0),
    .din1(mul_ln1118_13_fu_1876_p1),
    .dout(mul_ln1118_13_fu_1876_p2)
);

example_mul_mul_1sc4 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1sc4_U1893(
    .din0(mul_ln1118_14_fu_1883_p0),
    .din1(mul_ln1118_14_fu_1883_p1),
    .dout(mul_ln1118_14_fu_1883_p2)
);

example_mul_mul_1ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1ncg_U1894(
    .din0(mul_ln1118_15_fu_1890_p0),
    .din1(mul_ln1118_15_fu_1890_p1),
    .dout(mul_ln1118_15_fu_1890_p2)
);

example_mul_mul_1rcU #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 20 ))
example_mul_mul_1rcU_U1895(
    .din0(data_6_V_read),
    .din1(mul_ln1118_22_fu_1897_p1),
    .dout(mul_ln1118_22_fu_1897_p2)
);

example_mul_mul_1ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1ocq_U1896(
    .din0(mul_ln1118_23_fu_1904_p0),
    .din1(mul_ln1118_23_fu_1904_p1),
    .dout(mul_ln1118_23_fu_1904_p2)
);

example_mul_mul_1wdI #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1wdI_U1897(
    .din0(mul_ln1118_28_fu_1911_p0),
    .din1(mul_ln1118_28_fu_1911_p1),
    .dout(mul_ln1118_28_fu_1911_p2)
);

example_mul_mul_1sc4 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1sc4_U1898(
    .din0(mul_ln1118_29_fu_1918_p0),
    .din1(mul_ln1118_29_fu_1918_p1),
    .dout(mul_ln1118_29_fu_1918_p2)
);

example_mul_mul_1wdI #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1wdI_U1899(
    .din0(mul_ln1118_30_fu_1925_p0),
    .din1(mul_ln1118_30_fu_1925_p1),
    .dout(mul_ln1118_30_fu_1925_p2)
);

example_mul_mul_1tde #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 20 ))
example_mul_mul_1tde_U1900(
    .din0(data_7_V_read),
    .din1(mul_ln1118_31_fu_1932_p1),
    .dout(mul_ln1118_31_fu_1932_p2)
);

example_mul_mul_1wdI #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1wdI_U1901(
    .din0(mul_ln1118_36_fu_1939_p0),
    .din1(mul_ln1118_36_fu_1939_p1),
    .dout(mul_ln1118_36_fu_1939_p2)
);

example_mul_mul_1wdI #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1wdI_U1902(
    .din0(mul_ln1118_37_fu_1946_p0),
    .din1(mul_ln1118_37_fu_1946_p1),
    .dout(mul_ln1118_37_fu_1946_p2)
);

example_mul_mul_1ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1ncg_U1903(
    .din0(mul_ln1118_38_fu_1953_p0),
    .din1(mul_ln1118_38_fu_1953_p1),
    .dout(mul_ln1118_38_fu_1953_p2)
);

example_mul_mul_1qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1qcK_U1904(
    .din0(mul_ln1118_39_fu_1960_p0),
    .din1(mul_ln1118_39_fu_1960_p1),
    .dout(mul_ln1118_39_fu_1960_p2)
);

example_mul_mul_1wdI #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1wdI_U1905(
    .din0(mul_ln1118_43_fu_1967_p0),
    .din1(mul_ln1118_43_fu_1967_p1),
    .dout(mul_ln1118_43_fu_1967_p2)
);

example_mul_mul_1sc4 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1sc4_U1906(
    .din0(mul_ln1118_44_fu_1974_p0),
    .din1(mul_ln1118_44_fu_1974_p1),
    .dout(mul_ln1118_44_fu_1974_p2)
);

example_mul_mul_1ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1ocq_U1907(
    .din0(mul_ln1118_48_fu_1981_p0),
    .din1(mul_ln1118_48_fu_1981_p1),
    .dout(mul_ln1118_48_fu_1981_p2)
);

example_mul_mul_1ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1ocq_U1908(
    .din0(mul_ln1118_49_fu_1988_p0),
    .din1(mul_ln1118_49_fu_1988_p1),
    .dout(mul_ln1118_49_fu_1988_p2)
);

example_mul_mul_1ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1ocq_U1909(
    .din0(mul_ln1118_2_fu_1995_p0),
    .din1(mul_ln1118_2_fu_1995_p1),
    .dout(mul_ln1118_2_fu_1995_p2)
);

example_mul_mul_1ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1ncg_U1910(
    .din0(mul_ln1118_3_fu_2002_p0),
    .din1(mul_ln1118_3_fu_2002_p1),
    .dout(mul_ln1118_3_fu_2002_p2)
);

example_mul_mul_1wdI #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1wdI_U1911(
    .din0(mul_ln1118_8_fu_2009_p0),
    .din1(mul_ln1118_8_fu_2009_p1),
    .dout(mul_ln1118_8_fu_2009_p2)
);

example_mul_mul_1sc4 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1sc4_U1912(
    .din0(mul_ln1118_10_fu_2016_p0),
    .din1(mul_ln1118_10_fu_2016_p1),
    .dout(mul_ln1118_10_fu_2016_p2)
);

example_mul_mul_1sc4 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1sc4_U1913(
    .din0(mul_ln1118_17_fu_2023_p0),
    .din1(mul_ln1118_17_fu_2023_p1),
    .dout(mul_ln1118_17_fu_2023_p2)
);

example_mul_mul_1sc4 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1sc4_U1914(
    .din0(mul_ln1118_19_fu_2030_p0),
    .din1(mul_ln1118_19_fu_2030_p1),
    .dout(mul_ln1118_19_fu_2030_p2)
);

example_mul_mul_1sc4 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1sc4_U1915(
    .din0(mul_ln1118_24_fu_2037_p0),
    .din1(mul_ln1118_24_fu_2037_p1),
    .dout(mul_ln1118_24_fu_2037_p2)
);

example_mul_mul_1wdI #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1wdI_U1916(
    .din0(mul_ln1118_25_fu_2044_p0),
    .din1(mul_ln1118_25_fu_2044_p1),
    .dout(mul_ln1118_25_fu_2044_p2)
);

example_mul_mul_1wdI #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1wdI_U1917(
    .din0(mul_ln1118_27_fu_2051_p0),
    .din1(mul_ln1118_27_fu_2051_p1),
    .dout(mul_ln1118_27_fu_2051_p2)
);

example_mul_mul_1wdI #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1wdI_U1918(
    .din0(mul_ln1118_33_fu_2058_p0),
    .din1(mul_ln1118_33_fu_2058_p1),
    .dout(mul_ln1118_33_fu_2058_p2)
);

example_mul_mul_1qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1qcK_U1919(
    .din0(mul_ln1118_35_fu_2065_p0),
    .din1(mul_ln1118_35_fu_2065_p1),
    .dout(mul_ln1118_35_fu_2065_p2)
);

example_mul_mul_1ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1ncg_U1920(
    .din0(mul_ln1118_40_fu_2072_p0),
    .din1(mul_ln1118_40_fu_2072_p1),
    .dout(mul_ln1118_40_fu_2072_p2)
);

example_mul_mul_1rcU #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 20 ))
example_mul_mul_1rcU_U1921(
    .din0(data_2_V_read_8_reg_2129),
    .din1(mul_ln1118_42_fu_2079_p1),
    .dout(mul_ln1118_42_fu_2079_p2)
);

example_mul_mul_1ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1ocq_U1922(
    .din0(mul_ln1118_46_fu_2086_p0),
    .din1(mul_ln1118_46_fu_2086_p1),
    .dout(mul_ln1118_46_fu_2086_p2)
);

example_mul_mul_1ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1ocq_U1923(
    .din0(mul_ln1118_50_fu_2093_p0),
    .din1(mul_ln1118_50_fu_2093_p1),
    .dout(mul_ln1118_50_fu_2093_p2)
);

example_mul_mul_1ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 21 ))
example_mul_mul_1ocq_U1924(
    .din0(mul_ln1118_51_fu_2100_p0),
    .din1(mul_ln1118_51_fu_2100_p1),
    .dout(mul_ln1118_51_fu_2100_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1))) begin
        add_ln703_130_reg_2169 <= add_ln703_130_fu_333_p2;
        add_ln703_138_reg_2184 <= add_ln703_138_fu_381_p2;
        add_ln703_146_reg_2189 <= add_ln703_146_fu_415_p2;
        add_ln703_154_reg_2209 <= add_ln703_154_fu_477_p2;
        add_ln703_162_reg_2224 <= add_ln703_162_fu_525_p2;
        add_ln703_170_reg_2235 <= add_ln703_170_fu_635_p2;
        add_ln703_178_reg_2245 <= add_ln703_178_fu_743_p2;
        add_ln703_185_reg_2255 <= add_ln703_185_fu_847_p2;
        data_0_V_read_8_reg_2150 <= data_0_V_read;
        data_1_V_read_8_reg_2138 <= data_1_V_read;
        data_2_V_read_8_reg_2129 <= data_2_V_read;
        data_3_V_read_8_reg_2121 <= data_3_V_read;
        data_4_V_read_8_reg_2115 <= data_4_V_read;
        data_5_V_read_7_reg_2107 <= data_5_V_read;
        trunc_ln708_111_reg_2194 <= {{trunc_ln708_111_fu_421_p1[13:1]}};
        trunc_ln708_119_reg_2240 <= {{trunc_ln708_119_fu_655_p1[13:3]}};
        trunc_ln708_122_reg_2250 <= {{trunc_ln708_122_fu_749_p1[13:3]}};
        trunc_ln708_12_reg_2174 <= {{mul_ln1118_12_fu_1869_p2[20:7]}};
        trunc_ln708_13_reg_2179 <= {{mul_ln1118_13_fu_1876_p2[20:7]}};
        trunc_ln708_28_reg_2199 <= {{mul_ln1118_28_fu_1911_p2[20:7]}};
        trunc_ln708_29_reg_2204 <= {{mul_ln1118_29_fu_1918_p2[20:7]}};
        trunc_ln708_36_reg_2214 <= {{mul_ln1118_36_fu_1939_p2[20:7]}};
        trunc_ln708_37_reg_2219 <= {{mul_ln1118_37_fu_1946_p2[20:7]}};
        trunc_ln708_44_reg_2229 <= {{sub_ln1118_100_fu_543_p2[20:7]}};
        trunc_ln708_4_reg_2159 <= {{mul_ln1118_4_fu_1848_p2[20:7]}};
        trunc_ln708_5_reg_2164 <= {{mul_ln1118_5_fu_1855_p2[20:7]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= add_ln703_277_fu_1011_p2;
        ap_return_1_int_reg <= add_ln703_278_fu_1134_p2;
        ap_return_2_int_reg <= add_ln703_279_fu_1327_p2;
        ap_return_3_int_reg <= add_ln703_280_fu_1390_p2;
        ap_return_4_int_reg <= add_ln703_281_fu_1499_p2;
        ap_return_5_int_reg <= add_ln703_282_fu_1592_p2;
        ap_return_6_int_reg <= add_ln703_283_fu_1678_p2;
        ap_return_7_int_reg <= add_ln703_284_fu_1794_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = add_ln703_277_fu_1011_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = add_ln703_278_fu_1134_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = add_ln703_279_fu_1327_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = add_ln703_280_fu_1390_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_4 = ap_return_4_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_4 = add_ln703_281_fu_1499_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_5 = ap_return_5_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_5 = add_ln703_282_fu_1592_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_6 = ap_return_6_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_6 = add_ln703_283_fu_1678_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_7 = ap_return_7_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_7 = add_ln703_284_fu_1794_p2;
    end
end

assign add_ln1118_fu_1282_p2 = ($signed(sext_ln1118_134_fu_1278_p1) + $signed(sext_ln1118_133_fu_1267_p1));

assign add_ln703_126_fu_990_p2 = (trunc_ln708_2_fu_957_p4 + trunc_ln708_3_fu_975_p4);

assign add_ln703_127_fu_996_p2 = (add_ln703_126_fu_990_p2 + add_ln703_fu_984_p2);

assign add_ln703_128_fu_1002_p2 = (trunc_ln708_4_reg_2159 + trunc_ln708_5_reg_2164);

assign add_ln703_129_fu_327_p2 = ($signed(trunc_ln708_7_fu_317_p4) + $signed(14'd16344));

assign add_ln703_130_fu_333_p2 = (add_ln703_129_fu_327_p2 + trunc_ln708_6_fu_270_p4);

assign add_ln703_131_fu_1006_p2 = (add_ln703_130_reg_2169 + add_ln703_128_fu_1002_p2);

assign add_ln703_133_fu_1107_p2 = ($signed(trunc_ln708_8_fu_1017_p4) + $signed(sext_ln708_86_fu_1074_p1));

assign add_ln703_134_fu_1113_p2 = ($signed(trunc_ln708_10_fu_1078_p4) + $signed(sext_ln708_87_fu_1103_p1));

assign add_ln703_135_fu_1119_p2 = (add_ln703_134_fu_1113_p2 + add_ln703_133_fu_1107_p2);

assign add_ln703_136_fu_1125_p2 = (trunc_ln708_12_reg_2174 + trunc_ln708_13_reg_2179);

assign add_ln703_137_fu_375_p2 = (trunc_ln708_15_fu_366_p4 + 14'd89);

assign add_ln703_138_fu_381_p2 = (add_ln703_137_fu_375_p2 + trunc_ln708_14_fu_357_p4);

assign add_ln703_139_fu_1129_p2 = (add_ln703_138_reg_2184 + add_ln703_136_fu_1125_p2);

assign add_ln703_141_fu_1298_p2 = ($signed(sext_ln708_88_fu_1156_p1) + $signed(trunc_ln708_17_fu_1160_p4));

assign add_ln703_142_fu_1304_p2 = (trunc_ln708_18_fu_1207_p4 + trunc_ln708_19_fu_1217_p4);

assign add_ln703_143_fu_1310_p2 = (add_ln703_142_fu_1304_p2 + add_ln703_141_fu_1298_p2);

assign add_ln703_144_fu_1316_p2 = (trunc_ln708_20_fu_1250_p4 + trunc_ln708_21_fu_1288_p4);

assign add_ln703_145_fu_409_p2 = (trunc_ln708_23_fu_400_p4 + 14'd160);

assign add_ln703_146_fu_415_p2 = ($signed(add_ln703_145_fu_409_p2) + $signed(sext_ln708_89_fu_396_p1));

assign add_ln703_147_fu_1322_p2 = (add_ln703_146_reg_2189 + add_ln703_144_fu_1316_p2);

assign add_ln703_149_fu_1363_p2 = (trunc_ln708_24_fu_1333_p4 + trunc_ln708_25_fu_1342_p4);

assign add_ln703_150_fu_1369_p2 = ($signed(sext_ln708_90_fu_1351_p1) + $signed(trunc_ln708_27_fu_1354_p4));

assign add_ln703_151_fu_1375_p2 = (add_ln703_150_fu_1369_p2 + add_ln703_149_fu_1363_p2);

assign add_ln703_152_fu_1381_p2 = (trunc_ln708_28_reg_2199 + trunc_ln708_29_reg_2204);

assign add_ln703_153_fu_471_p2 = ($signed(sext_ln708_91_fu_467_p1) + $signed(14'd19));

assign add_ln703_154_fu_477_p2 = (add_ln703_153_fu_471_p2 + trunc_ln708_30_fu_449_p4);

assign add_ln703_155_fu_1385_p2 = (add_ln703_154_reg_2209 + add_ln703_152_fu_1381_p2);

assign add_ln703_157_fu_1472_p2 = (trunc_ln708_32_fu_1424_p4 + trunc_ln708_33_fu_1434_p4);

assign add_ln703_158_fu_1478_p2 = ($signed(sext_ln708_92_fu_1459_p1) + $signed(trunc_ln708_35_fu_1463_p4));

assign add_ln703_159_fu_1484_p2 = (add_ln703_158_fu_1478_p2 + add_ln703_157_fu_1472_p2);

assign add_ln703_160_fu_1490_p2 = (trunc_ln708_36_reg_2214 + trunc_ln708_37_reg_2219);

assign add_ln703_161_fu_519_p2 = (trunc_ln708_39_fu_510_p4 + 14'd17);

assign add_ln703_162_fu_525_p2 = (add_ln703_161_fu_519_p2 + trunc_ln708_38_fu_501_p4);

assign add_ln703_163_fu_1494_p2 = (add_ln703_162_reg_2224 + add_ln703_160_fu_1490_p2);

assign add_ln703_165_fu_1575_p2 = ($signed(trunc_ln708_40_fu_1505_p4) + $signed(sext_ln708_93_fu_1558_p1));

assign add_ln703_166_fu_1581_p2 = ($signed(sext_ln708_94_fu_1571_p1) + $signed(trunc_ln708_44_reg_2229));

assign add_ln703_167_fu_1586_p2 = (add_ln703_166_fu_1581_p2 + add_ln703_165_fu_1575_p2);

assign add_ln703_168_fu_623_p2 = (trunc_ln708_45_fu_559_p4 + trunc_ln708_46_fu_604_p4);

assign add_ln703_169_fu_629_p2 = (trunc_ln708_47_fu_614_p4 + 14'd16);

assign add_ln703_170_fu_635_p2 = (add_ln703_169_fu_629_p2 + add_ln703_168_fu_623_p2);

assign add_ln703_172_fu_1660_p2 = ($signed(sext_ln708_95_fu_1613_p1) + $signed(trunc_ln708_50_fu_1617_p4));

assign add_ln703_173_fu_1666_p2 = ($signed(sext_ln708_96_fu_1653_p1) + $signed(sext_ln708_97_fu_1657_p1));

assign add_ln703_174_fu_1672_p2 = (add_ln703_173_fu_1666_p2 + add_ln703_172_fu_1660_p2);

assign add_ln703_175_fu_721_p2 = ($signed(sext_ln708_98_fu_699_p1) + $signed(trunc_ln708_54_fu_703_p4));

assign add_ln703_176_fu_727_p2 = ($signed(sext_ln1118_141_fu_651_p1) + $signed(8'd204));

assign add_ln703_177_fu_737_p2 = ($signed(sext_ln703_fu_733_p1) + $signed(trunc_ln708_55_fu_712_p4));

assign add_ln703_178_fu_743_p2 = (add_ln703_177_fu_737_p2 + add_ln703_175_fu_721_p2);

assign add_ln703_180_fu_1766_p2 = ($signed(trunc_ln708_56_fu_1683_p4) + $signed(sext_ln708_99_fu_1708_p1));

assign add_ln703_181_fu_1772_p2 = ($signed(sext_ln708_100_fu_1712_p1) + $signed(trunc_ln708_59_fu_1715_p4));

assign add_ln703_182_fu_1778_p2 = (add_ln703_181_fu_1772_p2 + add_ln703_180_fu_1766_p2);

assign add_ln703_183_fu_1784_p2 = ($signed(trunc_ln708_44_reg_2229) + $signed(sext_ln708_101_fu_1762_p1));

assign add_ln703_184_fu_841_p2 = ($signed(sext_ln708_103_fu_837_p1) + $signed(14'd16326));

assign add_ln703_185_fu_847_p2 = ($signed(add_ln703_184_fu_841_p2) + $signed(sext_ln708_102_fu_787_p1));

assign add_ln703_186_fu_1789_p2 = (add_ln703_185_reg_2255 + add_ln703_183_fu_1784_p2);

assign add_ln703_277_fu_1011_p2 = (add_ln703_131_fu_1006_p2 + add_ln703_127_fu_996_p2);

assign add_ln703_278_fu_1134_p2 = (add_ln703_139_fu_1129_p2 + add_ln703_135_fu_1119_p2);

assign add_ln703_279_fu_1327_p2 = (add_ln703_147_fu_1322_p2 + add_ln703_143_fu_1310_p2);

assign add_ln703_280_fu_1390_p2 = (add_ln703_155_fu_1385_p2 + add_ln703_151_fu_1375_p2);

assign add_ln703_281_fu_1499_p2 = (add_ln703_163_fu_1494_p2 + add_ln703_159_fu_1484_p2);

assign add_ln703_282_fu_1592_p2 = (add_ln703_170_reg_2235 + add_ln703_167_fu_1586_p2);

assign add_ln703_283_fu_1678_p2 = (add_ln703_178_reg_2245 + add_ln703_174_fu_1672_p2);

assign add_ln703_284_fu_1794_p2 = (add_ln703_186_fu_1789_p2 + add_ln703_182_fu_1778_p2);

assign add_ln703_fu_984_p2 = ($signed(sext_ln708_fu_904_p1) + $signed(sext_ln708_85_fu_944_p1));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign mul_ln1118_10_fu_2016_p0 = sext_ln1118_109_fu_948_p1;

assign mul_ln1118_10_fu_2016_p1 = 21'd2097059;

assign mul_ln1118_11_fu_1087_p0 = data_3_V_read_8_reg_2121;

assign mul_ln1118_11_fu_1087_p2 = ($signed(mul_ln1118_11_fu_1087_p0) * $signed('hD));

assign mul_ln1118_12_fu_1869_p0 = sext_ln1118_116_fu_232_p1;

assign mul_ln1118_12_fu_1869_p1 = 21'd2097067;

assign mul_ln1118_13_fu_1876_p0 = sext_ln1118_118_fu_245_p1;

assign mul_ln1118_13_fu_1876_p1 = 21'd91;

assign mul_ln1118_14_fu_1883_p0 = sext_ln1118_120_fu_262_p1;

assign mul_ln1118_14_fu_1883_p1 = 21'd2097078;

assign mul_ln1118_15_fu_1890_p0 = sext_ln1118_122_fu_279_p1;

assign mul_ln1118_15_fu_1890_p1 = 21'd39;

assign mul_ln1118_17_fu_2023_p0 = sext_ln1118_105_fu_908_p1;

assign mul_ln1118_17_fu_2023_p1 = 21'd2097043;

assign mul_ln1118_19_fu_2030_p0 = sext_ln1118_113_fu_966_p1;

assign mul_ln1118_19_fu_2030_p1 = 21'd2097063;

assign mul_ln1118_22_fu_1897_p1 = 20'd1048553;

assign mul_ln1118_23_fu_1904_p0 = sext_ln1118_122_fu_279_p1;

assign mul_ln1118_23_fu_1904_p1 = 21'd2097110;

assign mul_ln1118_24_fu_2037_p0 = sext_ln1118_fu_853_p1;

assign mul_ln1118_24_fu_2037_p1 = 21'd2097052;

assign mul_ln1118_25_fu_2044_p0 = sext_ln1118_105_fu_908_p1;

assign mul_ln1118_25_fu_2044_p1 = 21'd85;

assign mul_ln1118_27_fu_2051_p0 = sext_ln1118_113_fu_966_p1;

assign mul_ln1118_27_fu_2051_p1 = 21'd103;

assign mul_ln1118_28_fu_1911_p0 = sext_ln1118_116_fu_232_p1;

assign mul_ln1118_28_fu_1911_p1 = 21'd102;

assign mul_ln1118_29_fu_1918_p0 = sext_ln1118_118_fu_245_p1;

assign mul_ln1118_29_fu_1918_p1 = 21'd2097044;

assign mul_ln1118_2_fu_1995_p0 = sext_ln1118_109_fu_948_p1;

assign mul_ln1118_2_fu_1995_p1 = 21'd2097102;

assign mul_ln1118_30_fu_1925_p0 = sext_ln1118_120_fu_262_p1;

assign mul_ln1118_30_fu_1925_p1 = 21'd119;

assign mul_ln1118_31_fu_1932_p1 = 20'd26;

assign mul_ln1118_33_fu_2058_p0 = sext_ln1118_105_fu_908_p1;

assign mul_ln1118_33_fu_2058_p1 = 21'd99;

assign mul_ln1118_35_fu_2065_p0 = sext_ln1118_113_fu_966_p1;

assign mul_ln1118_35_fu_2065_p1 = 21'd2096988;

assign mul_ln1118_36_fu_1939_p0 = sext_ln1118_116_fu_232_p1;

assign mul_ln1118_36_fu_1939_p1 = 21'd70;

assign mul_ln1118_37_fu_1946_p0 = sext_ln1118_118_fu_245_p1;

assign mul_ln1118_37_fu_1946_p1 = 21'd75;

assign mul_ln1118_38_fu_1953_p0 = sext_ln1118_120_fu_262_p1;

assign mul_ln1118_38_fu_1953_p1 = 21'd54;

assign mul_ln1118_39_fu_1960_p0 = sext_ln1118_122_fu_279_p1;

assign mul_ln1118_39_fu_1960_p1 = 21'd2096996;

assign mul_ln1118_3_fu_2002_p0 = sext_ln1118_113_fu_966_p1;

assign mul_ln1118_3_fu_2002_p1 = 21'd55;

assign mul_ln1118_40_fu_2072_p0 = sext_ln1118_fu_853_p1;

assign mul_ln1118_40_fu_2072_p1 = 21'd42;

assign mul_ln1118_42_fu_2079_p1 = 20'd1048547;

assign mul_ln1118_43_fu_1967_p0 = sext_ln1118_118_fu_245_p1;

assign mul_ln1118_43_fu_1967_p1 = 21'd109;

assign mul_ln1118_44_fu_1974_p0 = sext_ln1118_122_fu_279_p1;

assign mul_ln1118_44_fu_1974_p1 = 21'd2097082;

assign mul_ln1118_45_fu_1597_p0 = data_1_V_read_8_reg_2138;

assign mul_ln1118_45_fu_1597_p2 = ($signed(mul_ln1118_45_fu_1597_p0) * $signed('hB));

assign mul_ln1118_46_fu_2086_p0 = sext_ln1118_109_fu_948_p1;

assign mul_ln1118_46_fu_2086_p1 = 21'd2097109;

assign mul_ln1118_48_fu_1981_p0 = sext_ln1118_120_fu_262_p1;

assign mul_ln1118_48_fu_1981_p1 = 21'd2097114;

assign mul_ln1118_49_fu_1988_p0 = sext_ln1118_122_fu_279_p1;

assign mul_ln1118_49_fu_1988_p1 = 21'd2097091;

assign mul_ln1118_4_fu_1848_p0 = sext_ln1118_116_fu_232_p1;

assign mul_ln1118_4_fu_1848_p1 = 21'd76;

assign mul_ln1118_50_fu_2093_p0 = sext_ln1118_fu_853_p1;

assign mul_ln1118_50_fu_2093_p1 = 21'd2097103;

assign mul_ln1118_51_fu_2100_p0 = sext_ln1118_113_fu_966_p1;

assign mul_ln1118_51_fu_2100_p1 = 21'd2097117;

assign mul_ln1118_5_fu_1855_p0 = sext_ln1118_118_fu_245_p1;

assign mul_ln1118_5_fu_1855_p1 = 21'd2097098;

assign mul_ln1118_6_fu_1862_p0 = sext_ln1118_120_fu_262_p1;

assign mul_ln1118_6_fu_1862_p1 = 21'd89;

assign mul_ln1118_8_fu_2009_p0 = sext_ln1118_fu_853_p1;

assign mul_ln1118_8_fu_2009_p1 = 21'd92;

assign sext_ln1118_102_fu_863_p1 = $signed(shl_ln_fu_856_p3);

assign sext_ln1118_103_fu_880_p1 = shl_ln1118_56_fu_873_p3;

assign sext_ln1118_104_fu_884_p1 = shl_ln1118_56_fu_873_p3;

assign sext_ln1118_105_fu_908_p1 = data_1_V_read_8_reg_2138;

assign sext_ln1118_107_fu_914_p1 = data_1_V_read_8_reg_2138;

assign sext_ln1118_108_fu_924_p1 = $signed(shl_ln1118_57_fu_917_p3);

assign sext_ln1118_109_fu_948_p1 = data_2_V_read_8_reg_2129;

assign sext_ln1118_112_fu_954_p1 = data_2_V_read_8_reg_2129;

assign sext_ln1118_113_fu_966_p1 = data_3_V_read_8_reg_2121;

assign sext_ln1118_114_fu_969_p1 = data_3_V_read_8_reg_2121;

assign sext_ln1118_116_fu_232_p0 = data_4_V_read;

assign sext_ln1118_116_fu_232_p1 = sext_ln1118_116_fu_232_p0;

assign sext_ln1118_118_fu_245_p0 = data_5_V_read;

assign sext_ln1118_118_fu_245_p1 = sext_ln1118_118_fu_245_p0;

assign sext_ln1118_119_fu_249_p0 = data_5_V_read;

assign sext_ln1118_119_fu_249_p1 = sext_ln1118_119_fu_249_p0;

assign sext_ln1118_120_fu_262_p0 = data_6_V_read;

assign sext_ln1118_120_fu_262_p1 = sext_ln1118_120_fu_262_p0;

assign sext_ln1118_122_fu_279_p0 = data_7_V_read;

assign sext_ln1118_122_fu_279_p1 = sext_ln1118_122_fu_279_p0;

assign sext_ln1118_124_fu_295_p1 = $signed(shl_ln1118_58_fu_287_p3);

assign sext_ln1118_125_fu_307_p1 = $signed(shl_ln1118_59_fu_299_p3);

assign sext_ln1118_126_fu_1033_p1 = $signed(shl_ln1118_60_fu_1026_p3);

assign sext_ln1118_127_fu_1050_p1 = shl_ln1118_61_fu_1043_p3;

assign sext_ln1118_128_fu_1054_p1 = shl_ln1118_61_fu_1043_p3;

assign sext_ln1118_129_fu_1176_p1 = $signed(shl_ln1118_62_fu_1169_p3);

assign sext_ln1118_130_fu_1193_p1 = shl_ln1118_63_fu_1186_p3;

assign sext_ln1118_131_fu_1197_p1 = shl_ln1118_63_fu_1186_p3;

assign sext_ln1118_132_fu_1240_p1 = $signed(shl_ln1118_65_fu_1233_p3);

assign sext_ln1118_133_fu_1267_p1 = $signed(shl_ln1118_66_fu_1260_p3);

assign sext_ln1118_134_fu_1278_p1 = $signed(shl_ln1118_67_fu_1271_p3);

assign sext_ln1118_135_fu_1403_p1 = $signed(shl_ln1118_68_fu_1396_p3);

assign sext_ln1118_136_fu_1414_p1 = $signed(shl_ln1118_69_fu_1407_p3);

assign sext_ln1118_137_fu_1521_p1 = $signed(shl_ln1118_70_fu_1514_p3);

assign sext_ln1118_138_fu_1538_p1 = $signed(shl_ln1118_71_fu_1531_p3);

assign sext_ln1118_139_fu_590_p1 = shl_ln1118_73_fu_582_p3;

assign sext_ln1118_140_fu_594_p1 = shl_ln1118_73_fu_582_p3;

assign sext_ln1118_141_fu_651_p1 = $signed(trunc_ln708_116_fu_641_p4);

assign sext_ln1118_142_fu_673_p1 = $signed(shl_ln1118_74_fu_665_p3);

assign sext_ln1118_143_fu_1731_p1 = $signed(shl_ln1118_75_fu_1724_p3);

assign sext_ln1118_144_fu_1742_p1 = $signed(shl_ln1118_76_fu_1735_p3);

assign sext_ln1118_145_fu_767_p1 = $signed(shl_ln1118_77_fu_759_p3);

assign sext_ln1118_146_fu_799_p1 = $signed(shl_ln1118_78_fu_791_p3);

assign sext_ln1118_147_fu_817_p1 = $signed(shl_ln1118_79_fu_809_p3);

assign sext_ln1118_217_fu_539_p1 = $signed(tmp_fu_531_p3);

assign sext_ln1118_218_fu_1633_p1 = $signed(tmp_s_fu_1626_p3);

assign sext_ln1118_fu_853_p1 = data_0_V_read_8_reg_2150;

assign sext_ln703_fu_733_p1 = $signed(add_ln703_176_fu_727_p2);

assign sext_ln708_100_fu_1712_p1 = $signed(trunc_ln708_122_reg_2250);

assign sext_ln708_101_fu_1762_p1 = $signed(trunc_ln708_123_fu_1752_p4);

assign sext_ln708_102_fu_787_p1 = $signed(trunc_ln708_124_fu_777_p4);

assign sext_ln708_103_fu_837_p1 = $signed(trunc_ln708_125_fu_827_p4);

assign sext_ln708_85_fu_944_p1 = $signed(trunc_ln708_106_fu_934_p4);

assign sext_ln708_86_fu_1074_p1 = $signed(trunc_ln708_107_fu_1064_p4);

assign sext_ln708_87_fu_1103_p1 = $signed(trunc_ln708_108_fu_1093_p4);

assign sext_ln708_88_fu_1156_p1 = $signed(trunc_ln708_109_fu_1146_p4);

assign sext_ln708_89_fu_396_p1 = $signed(trunc_ln708_110_fu_387_p4);

assign sext_ln708_90_fu_1351_p1 = $signed(trunc_ln708_111_reg_2194);

assign sext_ln708_91_fu_467_p1 = $signed(trunc_ln708_112_fu_458_p4);

assign sext_ln708_92_fu_1459_p1 = $signed(trunc_ln708_113_fu_1449_p4);

assign sext_ln708_93_fu_1558_p1 = $signed(trunc_ln708_114_fu_1548_p4);

assign sext_ln708_94_fu_1571_p1 = $signed(trunc_ln708_115_fu_1562_p4);

assign sext_ln708_95_fu_1613_p1 = $signed(trunc_ln708_117_fu_1603_p4);

assign sext_ln708_96_fu_1653_p1 = $signed(trunc_ln708_118_fu_1643_p4);

assign sext_ln708_97_fu_1657_p1 = $signed(trunc_ln708_119_reg_2240);

assign sext_ln708_98_fu_699_p1 = $signed(trunc_ln708_120_fu_689_p4);

assign sext_ln708_99_fu_1708_p1 = $signed(trunc_ln708_121_fu_1698_p4);

assign sext_ln708_fu_904_p1 = $signed(trunc_ln_fu_894_p4);

assign shl_ln1118_56_fu_873_p3 = {{data_0_V_read_8_reg_2150}, {1'd0}};

assign shl_ln1118_57_fu_917_p3 = {{data_1_V_read_8_reg_2138}, {3'd0}};

assign shl_ln1118_58_fu_287_p1 = data_7_V_read;

assign shl_ln1118_58_fu_287_p3 = {{shl_ln1118_58_fu_287_p1}, {6'd0}};

assign shl_ln1118_59_fu_299_p1 = data_7_V_read;

assign shl_ln1118_59_fu_299_p3 = {{shl_ln1118_59_fu_299_p1}, {4'd0}};

assign shl_ln1118_60_fu_1026_p3 = {{data_1_V_read_8_reg_2138}, {5'd0}};

assign shl_ln1118_61_fu_1043_p3 = {{data_1_V_read_8_reg_2138}, {2'd0}};

assign shl_ln1118_62_fu_1169_p3 = {{data_2_V_read_8_reg_2129}, {6'd0}};

assign shl_ln1118_63_fu_1186_p3 = {{data_2_V_read_8_reg_2129}, {3'd0}};

assign shl_ln1118_64_fu_1226_p3 = {{data_4_V_read_8_reg_2115}, {7'd0}};

assign shl_ln1118_65_fu_1233_p3 = {{data_4_V_read_8_reg_2115}, {3'd0}};

assign shl_ln1118_66_fu_1260_p3 = {{data_5_V_read_7_reg_2107}, {6'd0}};

assign shl_ln1118_67_fu_1271_p3 = {{data_5_V_read_7_reg_2107}, {2'd0}};

assign shl_ln1118_68_fu_1396_p3 = {{data_0_V_read_8_reg_2150}, {6'd0}};

assign shl_ln1118_69_fu_1407_p3 = {{data_0_V_read_8_reg_2150}, {3'd0}};

assign shl_ln1118_70_fu_1514_p3 = {{data_1_V_read_8_reg_2138}, {4'd0}};

assign shl_ln1118_71_fu_1531_p3 = {{data_1_V_read_8_reg_2138}, {1'd0}};

assign shl_ln1118_72_fu_568_p1 = data_6_V_read;

assign shl_ln1118_72_fu_568_p3 = {{shl_ln1118_72_fu_568_p1}, {7'd0}};

assign shl_ln1118_73_fu_582_p1 = data_6_V_read;

assign shl_ln1118_73_fu_582_p3 = {{shl_ln1118_73_fu_582_p1}, {5'd0}};

assign shl_ln1118_74_fu_665_p1 = data_5_V_read;

assign shl_ln1118_74_fu_665_p3 = {{shl_ln1118_74_fu_665_p1}, {4'd0}};

assign shl_ln1118_75_fu_1724_p3 = {{data_5_V_read_7_reg_2107}, {3'd0}};

assign shl_ln1118_76_fu_1735_p3 = {{data_5_V_read_7_reg_2107}, {1'd0}};

assign shl_ln1118_77_fu_759_p1 = data_6_V_read;

assign shl_ln1118_77_fu_759_p3 = {{shl_ln1118_77_fu_759_p1}, {3'd0}};

assign shl_ln1118_78_fu_791_p1 = data_7_V_read;

assign shl_ln1118_78_fu_791_p3 = {{shl_ln1118_78_fu_791_p1}, {5'd0}};

assign shl_ln1118_79_fu_809_p1 = data_7_V_read;

assign shl_ln1118_79_fu_809_p3 = {{shl_ln1118_79_fu_809_p1}, {3'd0}};

assign shl_ln_fu_856_p3 = {{data_0_V_read_8_reg_2150}, {5'd0}};

assign sub_ln1118_100_fu_543_p2 = ($signed(sext_ln1118_116_fu_232_p1) - $signed(sext_ln1118_217_fu_539_p1));

assign sub_ln1118_101_fu_1637_p2 = ($signed(sext_ln1118_114_fu_969_p1) - $signed(sext_ln1118_218_fu_1633_p1));

assign sub_ln1118_47_fu_888_p2 = ($signed(sub_ln1118_fu_867_p2) - $signed(sext_ln1118_104_fu_884_p1));

assign sub_ln1118_48_fu_928_p2 = ($signed(sext_ln1118_108_fu_924_p1) - $signed(sext_ln1118_107_fu_914_p1));

assign sub_ln1118_49_fu_311_p2 = ($signed(sext_ln1118_124_fu_295_p1) - $signed(sext_ln1118_125_fu_307_p1));

assign sub_ln1118_50_fu_1037_p2 = ($signed(20'd0) - $signed(sext_ln1118_126_fu_1033_p1));

assign sub_ln1118_51_fu_1058_p2 = ($signed(sub_ln1118_50_fu_1037_p2) - $signed(sext_ln1118_128_fu_1054_p1));

assign sub_ln1118_52_fu_1140_p2 = ($signed(16'd0) - $signed(sext_ln1118_103_fu_880_p1));

assign sub_ln1118_53_fu_1180_p2 = ($signed(21'd0) - $signed(sext_ln1118_129_fu_1176_p1));

assign sub_ln1118_54_fu_1201_p2 = ($signed(sub_ln1118_53_fu_1180_p2) - $signed(sext_ln1118_131_fu_1197_p1));

assign sub_ln1118_55_fu_1244_p2 = ($signed(sext_ln1118_132_fu_1240_p1) - $signed(shl_ln1118_64_fu_1226_p3));

assign sub_ln1118_56_fu_1418_p2 = ($signed(sext_ln1118_136_fu_1414_p1) - $signed(sext_ln1118_135_fu_1403_p1));

assign sub_ln1118_57_fu_1443_p2 = ($signed(sext_ln1118_130_fu_1193_p1) - $signed(sext_ln1118_112_fu_954_p1));

assign sub_ln1118_58_fu_1525_p2 = ($signed(19'd0) - $signed(sext_ln1118_137_fu_1521_p1));

assign sub_ln1118_59_fu_1542_p2 = ($signed(sub_ln1118_58_fu_1525_p2) - $signed(sext_ln1118_138_fu_1538_p1));

assign sub_ln1118_60_fu_576_p2 = (21'd0 - shl_ln1118_72_fu_568_p3);

assign sub_ln1118_61_fu_598_p2 = ($signed(sub_ln1118_60_fu_576_p2) - $signed(sext_ln1118_140_fu_594_p1));

assign sub_ln1118_62_fu_677_p2 = ($signed(19'd0) - $signed(sext_ln1118_142_fu_673_p1));

assign sub_ln1118_63_fu_683_p2 = ($signed(sub_ln1118_62_fu_677_p2) - $signed(sext_ln1118_119_fu_249_p1));

assign sub_ln1118_64_fu_1692_p2 = ($signed(sub_ln1118_58_fu_1525_p2) - $signed(sext_ln1118_127_fu_1050_p1));

assign sub_ln1118_65_fu_1746_p2 = ($signed(sext_ln1118_143_fu_1731_p1) - $signed(sext_ln1118_144_fu_1742_p1));

assign sub_ln1118_66_fu_771_p2 = ($signed(sext_ln1118_145_fu_767_p1) - $signed(sext_ln1118_139_fu_590_p1));

assign sub_ln1118_67_fu_803_p2 = ($signed(20'd0) - $signed(sext_ln1118_146_fu_799_p1));

assign sub_ln1118_68_fu_821_p2 = ($signed(sub_ln1118_67_fu_803_p2) - $signed(sext_ln1118_147_fu_817_p1));

assign sub_ln1118_fu_867_p2 = ($signed(20'd0) - $signed(sext_ln1118_102_fu_863_p1));

assign tmp_fu_531_p1 = data_4_V_read;

assign tmp_fu_531_p3 = {{tmp_fu_531_p1}, {6'd0}};

assign tmp_s_fu_1626_p3 = {{data_3_V_read_8_reg_2121}, {5'd0}};

assign trunc_ln708_106_fu_934_p4 = {{sub_ln1118_48_fu_928_p2[17:7]}};

assign trunc_ln708_107_fu_1064_p4 = {{sub_ln1118_51_fu_1058_p2[19:7]}};

assign trunc_ln708_108_fu_1093_p4 = {{mul_ln1118_11_fu_1087_p2[18:7]}};

assign trunc_ln708_109_fu_1146_p4 = {{sub_ln1118_52_fu_1140_p2[15:7]}};

assign trunc_ln708_10_fu_1078_p4 = {{mul_ln1118_10_fu_2016_p2[20:7]}};

assign trunc_ln708_110_fu_387_p4 = {{mul_ln1118_22_fu_1897_p2[19:7]}};

assign trunc_ln708_111_fu_421_p1 = data_2_V_read;

assign trunc_ln708_112_fu_458_p4 = {{mul_ln1118_31_fu_1932_p2[19:7]}};

assign trunc_ln708_113_fu_1449_p4 = {{sub_ln1118_57_fu_1443_p2[17:7]}};

assign trunc_ln708_114_fu_1548_p4 = {{sub_ln1118_59_fu_1542_p2[18:7]}};

assign trunc_ln708_115_fu_1562_p4 = {{mul_ln1118_42_fu_2079_p2[19:7]}};

assign trunc_ln708_116_fu_641_p1 = data_0_V_read;

assign trunc_ln708_116_fu_641_p4 = {{trunc_ln708_116_fu_641_p1[13:7]}};

assign trunc_ln708_117_fu_1603_p4 = {{mul_ln1118_45_fu_1597_p2[18:7]}};

assign trunc_ln708_118_fu_1643_p4 = {{sub_ln1118_101_fu_1637_p2[19:7]}};

assign trunc_ln708_119_fu_655_p1 = data_4_V_read;

assign trunc_ln708_120_fu_689_p4 = {{sub_ln1118_63_fu_683_p2[18:7]}};

assign trunc_ln708_121_fu_1698_p4 = {{sub_ln1118_64_fu_1692_p2[18:7]}};

assign trunc_ln708_122_fu_749_p1 = data_2_V_read;

assign trunc_ln708_123_fu_1752_p4 = {{sub_ln1118_65_fu_1746_p2[17:7]}};

assign trunc_ln708_124_fu_777_p4 = {{sub_ln1118_66_fu_771_p2[19:7]}};

assign trunc_ln708_125_fu_827_p4 = {{sub_ln1118_68_fu_821_p2[19:7]}};

assign trunc_ln708_14_fu_357_p4 = {{mul_ln1118_14_fu_1883_p2[20:7]}};

assign trunc_ln708_15_fu_366_p4 = {{mul_ln1118_15_fu_1890_p2[20:7]}};

assign trunc_ln708_17_fu_1160_p4 = {{mul_ln1118_17_fu_2023_p2[20:7]}};

assign trunc_ln708_18_fu_1207_p4 = {{sub_ln1118_54_fu_1201_p2[20:7]}};

assign trunc_ln708_19_fu_1217_p4 = {{mul_ln1118_19_fu_2030_p2[20:7]}};

assign trunc_ln708_20_fu_1250_p4 = {{sub_ln1118_55_fu_1244_p2[20:7]}};

assign trunc_ln708_21_fu_1288_p4 = {{add_ln1118_fu_1282_p2[20:7]}};

assign trunc_ln708_23_fu_400_p4 = {{mul_ln1118_23_fu_1904_p2[20:7]}};

assign trunc_ln708_24_fu_1333_p4 = {{mul_ln1118_24_fu_2037_p2[20:7]}};

assign trunc_ln708_25_fu_1342_p4 = {{mul_ln1118_25_fu_2044_p2[20:7]}};

assign trunc_ln708_27_fu_1354_p4 = {{mul_ln1118_27_fu_2051_p2[20:7]}};

assign trunc_ln708_2_fu_957_p4 = {{mul_ln1118_2_fu_1995_p2[20:7]}};

assign trunc_ln708_30_fu_449_p4 = {{mul_ln1118_30_fu_1925_p2[20:7]}};

assign trunc_ln708_32_fu_1424_p4 = {{sub_ln1118_56_fu_1418_p2[20:7]}};

assign trunc_ln708_33_fu_1434_p4 = {{mul_ln1118_33_fu_2058_p2[20:7]}};

assign trunc_ln708_35_fu_1463_p4 = {{mul_ln1118_35_fu_2065_p2[20:7]}};

assign trunc_ln708_38_fu_501_p4 = {{mul_ln1118_38_fu_1953_p2[20:7]}};

assign trunc_ln708_39_fu_510_p4 = {{mul_ln1118_39_fu_1960_p2[20:7]}};

assign trunc_ln708_3_fu_975_p4 = {{mul_ln1118_3_fu_2002_p2[20:7]}};

assign trunc_ln708_40_fu_1505_p4 = {{mul_ln1118_40_fu_2072_p2[20:7]}};

assign trunc_ln708_45_fu_559_p4 = {{mul_ln1118_43_fu_1967_p2[20:7]}};

assign trunc_ln708_46_fu_604_p4 = {{sub_ln1118_61_fu_598_p2[20:7]}};

assign trunc_ln708_47_fu_614_p4 = {{mul_ln1118_44_fu_1974_p2[20:7]}};

assign trunc_ln708_50_fu_1617_p4 = {{mul_ln1118_46_fu_2086_p2[20:7]}};

assign trunc_ln708_54_fu_703_p4 = {{mul_ln1118_48_fu_1981_p2[20:7]}};

assign trunc_ln708_55_fu_712_p4 = {{mul_ln1118_49_fu_1988_p2[20:7]}};

assign trunc_ln708_56_fu_1683_p4 = {{mul_ln1118_50_fu_2093_p2[20:7]}};

assign trunc_ln708_59_fu_1715_p4 = {{mul_ln1118_51_fu_2100_p2[20:7]}};

assign trunc_ln708_6_fu_270_p4 = {{mul_ln1118_6_fu_1862_p2[20:7]}};

assign trunc_ln708_7_fu_317_p4 = {{sub_ln1118_49_fu_311_p2[20:7]}};

assign trunc_ln708_8_fu_1017_p4 = {{mul_ln1118_8_fu_2009_p2[20:7]}};

assign trunc_ln_fu_894_p4 = {{sub_ln1118_47_fu_888_p2[19:7]}};

endmodule //dense_resource_0_0
